### ISSUE TITLE
Level bug

### ISSUE THREAD

**Issue by LabyStudio** [MineKits/MineKits#10]
http://puu.sh/gqia6/97e84103dc.png

**Comment by HDuck** [comment]
Wäre cool, wenn die Levelanzeige immer auf 0 Steht, außer bei der Cooldown anzeige, wenn das geht, denn es ist sehr verwirrend, wenn man immer ein Paar level hat, und als Mod verschwinden die Level auch nicht nach dem Tod.
@lukas81298

**Comment by LabyStudio** [comment]
fixed.
