### ISSUE TITLE
Kit Shapeshifter [MCPVP Like]

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#100]
Wie wäre das kit Shapeshifter wie bei MCPVP?

Oder ist das nicht Umsetzbar [..] weil das war ja mal irgentwie geplant egal:

Kit Item: Redstone Block

Wenn man mit dem RedstoneBlock ein Block rechtsklickt, dann verwandelt man sich zu diesem.
Aber dabei Muss man den Block in der Hand halten.
Wenn dich ein Gegner Schlägt, hat man einen Cooldown von 5 Sekunden (wie Grappler)

Wenn man insgesammt 15 Sekunden ein Block war, dann hat man Automatisch einen Cooldown von 30-40 Sekunden.
_________________________________________________
(definition von "Insgesammt 15 Sekunden Block war":
Wenn man z.B 
4 sekunden verwandelt war, dann 7 sekunden (= 11) und dann noch 2 sekunden verwandelt und dann kann man noch maximal 2 Sekunden ein Block sein, bis man ein Cooldown
___________________________________________________

Achtung: Es soll Blöcke  geben, wo man sich nicht verwandeln kann:

Alle, wo man rein kann:
bsp: Blumen, Gras, Schnee, Leitern 

Why: Man kann sich dann sozusagen in den Blöcken verstecken, was in KitPvP einen hohen vorteil verschafft

Hoffe es gefällt dir/euch und ist Umsetzbar.

**Comment by EinfachNiggo** [comment]
Gute Idde5 c:

**Comment by LabyStudio** [comment]
Ich denke das wird wieder so ein 1.7-1.8 problem aber wenn man es kann wird es einfach ;)

**Comment by CraftingExpertDE** [comment]
wir wollten doch  nicht mehr so viel klauen @HDuck

**Comment by HDuck** [comment]
Der Server stammt ja ursprünglich von MCPVP, daher nehmen wir auch die MCPVP Kits zum training, oder?
VIper, Snail, Viking, Levitator Turtle... alles mcpvp :D

Nur eben nicht besonders von Dojo oder anderen KitPvP servern klaun c:
