### ISSUE TITLE
Kit Sonic

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#101]
Kit Sonic:

Wenn man Sneakt, lädt man sich auf (wie bsp. Dwarf)

Wenn man dann auf 100% ist, dann wird man in die Richtung geschleudert, in die man gerade geschaut hat  (es klappt nicht wenn man auf 70%  oder 40% etc. ist).

Wenns geht: 
Dass man sich auch etwas in die Höhe Boosted, zwar nicht genau nach oben aber so ein wenig nach oben.

Hoffe das Kit gefällt dir/euch :)

**Comment by EinfachNiggo** [comment]
Klingt ganz cool, aber das Kit hat ja keine "Attacke".. das find ich dann bisschen komisch :D

**Comment by HDuck** [comment]
Stimmt man kann es entweder so als "Weglauf kit" Nehmen 

ODER:

Wenn man dann ein Spieler trifft, wird er noch etwas weggeknockt = Rückstoß = YAHH

**Comment by KnuddelPvPer** [comment]
Nice

**Comment by HDuck** [comment]
Knuddel da? o.o k. :O
