### ISSUE TITLE
Kit Trapper (alternative zu Freezer)

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#102]
Kit Trapper:

Item: Schwarzer Farbstoff
(anzahl: 3 + Upgrade)
WICHTIG: Verboten auf NoSoup

Wenn man mit Trapper einen Block Rechtsklickt wird er durch Schwarze Wolle ersetzt (Über der Wolle muss 2 Block freiraum (wie endermage) damit man auch auf die Wolle steigen kann.)

Wenn man auf die Wolle geht, bekommt man sofort Blindness und den Effekt, dass man sich nicht bewegen kann für [4-6 oder so] Sekunden.

Wenn man einen Tötet, bekommt man wieder einen Farbstoff dazu.

**Comment by EinfachNiggo** [comment]
Das ist die langweilige Version von Chewing Gum ;D
Finde ich nicht sooo :c

**Comment by HDuck** [comment]
What alter Dojo hat ja mal alle Abilitys da bekommt man keine ideen mehr xD Ich dacht ich sei der Erfinder

**Comment by EinfachNiggo** [comment]
@HDuck Das ist nicht von Dojo :D
Das war 'ne Idee von mir (Siehe Github ;))

**Comment by lukas81298** [comment]
chewing gum wurd gemacht
