### ISSUE TITLE
eZ, rekt.. etc.

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#103]
Kurze Idee.
Wie wäre es, wenn man einen "Ausdruck" (eZ rekt l2p ddoa hurensohn blabla..) in den Chat schreibt, dass dieser zwar nicht zensiert ist, aber man dafür 3 / 5 / 10 (?) Coins Abzug bekommt. Somit schreibt man es automatisch weniger und ich denke das ist ganz gut so für die Community..
Joa.. ciao!
~ Niggo c;

**Comment by lejaden** [comment]
Ich würde schon sagen, dass es weiterhin zensiert bleibt. Dennoch kann man das mit den coins als sogenannte "Strafe" einbauen.

**Comment by EinfachNiggo** [comment]
Geht natürlich auch so c:

**Comment by HDuck** [comment]
Wär auch dafür dass es Zensiert bleibt UND dass man gleichzeitig 10 Coins verliert :)

**Comment by lukas81298** [comment]
Nur was passiert, wenn man keine Coins mehr hat? :D

**Comment by HDuck** [comment]
Minus bereich? Idk xD

vlt. wird man dann einfach Automatisch gekickt oder so.. dann lernt man es schnell

**Comment by lejaden** [comment]
Srimmt lukas. Aber wie wärs mit einem automatischen tempban für 10 min oder so? ^^

**Comment by EinfachNiggo** [comment]
Ja, ein Kick wäre ja ganz cool :D Tempban übertrieben.. c:

**Comment by LabyStudio** [comment]
Wenn man schon 0 coins hat und das dann schreibt sollte man gebannt werden.
Weil wer 0 coins hat spielt auch nicht..

**Comment by HDuck** [comment]
Bisl Übertrieben.. wenn man 0 Coins hat, wäre ich dafür dass man einfach für sehr lange zeit gemutet ist bsp. 1Tag

**Comment by EinfachNiggo** [comment]
Gut. 1Tag! Dann viel Spaß beim coden c: xD
