### ISSUE TITLE
Von NoSoup zu Spawn Laufen => Man hat immernoch Compass

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#104]
Wie der titel schon alles erklärt:

Wenn man von NoSoup zum Spawn läuft, dann verliert man ja sein Eisenschwert und bekommt wieder die Suppen dazu,
aber man behält immernoch seinen Kompass.
Zwar kein Großer Bug dennoch ist es einer. :)

**Comment by lukas81298** [comment]
Das ist gewollt.
