### ISSUE TITLE
RandomKit-Sign  

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#107]
So:
Man muss zuerst die "2" drücken (weil meine Kit-Items da landen) dann einfach das Schild drücken.

Auf dem 2. Slot landet das Kit Item dann nicht.

bsp. Bekommt man bei Assassin den Power dust nicht aber den Zucker.
bsp. Bekommt man bei Levitator kein Item

**Comment by lukas81298** [comment]
Dann soll man eben nicht mit der 2 drauf drücken.
