### ISSUE TITLE
Fehler wenn man Kangaroo tötet

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#108]
Ein Spieler meint, dass wenn man einen Kangaroo tötet, und man sein Item bekommt 
(vlt. durch gladiator oder vlt bekommt man es auch einfach so) dann kann man das nicht Droppen.

(Report by KompetenzHG)

**Comment by HDuck** [comment]
EDIT:
Wenn man ein kangaroo Gladiatort, bekommt man die Rakete welche man nciht mehr weg bekommt

**Comment by lukas81298** [comment]
Íst gefixed
