### ISSUE TITLE
Neue spawn items!

### ISSUE THREAD

**Issue by LabyStudio** [MineKits/MineKits#110]
Änder die Spawn items:
http://puu.sh/gGDKM/f374bfbf1e.png

Neues Item:
-Compass (Wird "/warp" ausgeführt)

Items entfernt:
-Emerald (Ist jetzt im Warpmenü)

**Comment by EinfachNiggo** [comment]
Super! :)

**Comment by HDuck** [comment]
Dat find-isch Super
