### ISSUE TITLE
MineKits Clan System [MCPVP Like]

### ISSUE THREAD

**Issue by KnuddelPvPer** [MineKits/MineKits#112]
Wie wäre es mit einem Clan System wie auf MCPVP.
Jeder kann einen Clan ab einem bestimmten Level gründen (ich denke Lvl 5 ist gerecht).
Man kann in diesem Clan 2 Gruppen vergeben Clan-Admin und Clan-Mod.
Dieses System kann man über den Chat oder über ein Icon im Menü verwalten.
In jeden Clan können Maximal 50 Spieler.
Der Clan Tag vor dem Namen darf nur 5 Buchstaben haben.

Ich hoffe euch gefällt meine idee und ihr könnt sie gut umsetzen c:

**Comment by EinfachNiggo** [comment]
Wir hatten vor nicht mehr so viel zu klauen.. xD
Außerdem ist das doch so ↑ bisschen sinnlos auf Kitpvp oder?

**Comment by KnuddelPvPer** [comment]
kann sein aber wäre schon irgendwie nice xD

**Comment by HDuck** [comment]
Aber für KitPvP eigentlich unnötig, wennschon dann auch so Clanfights, aber das hat schon Dojo übernommen..

man muss sich überlegen: "Wenn man ein Clan hat, was soll man dann damit machen können?"
- Dojo: Clan FIghts
- MCPVP: Clan Ranking
- Wir: Neue Idee suchen :D

**Comment by lejaden** [comment]
Das einzigste was mit so einfällt, wären ein clanchat

**Comment by lukas81298** [comment]
Es wird auf jeden Fall ein Freundesystem geben.

**Comment by CraftingExpertDE** [comment]
@HDuck wie wäre es mit:

**Comment by HDuck** [comment]
@CraftingExpertDE  genau das meinte ich doch.
Das hat schon Dojo übernommen, wir sollten ne andere Idee anschaffen

**Comment by CraftingExpertDE** [comment]
hm, schade, hab das system von dojo nicht im kopf^^

**Comment by EinfachNiggo** [comment]
Clanchat wäre cool! und vielleicht in so 'ne Richtig Clan-Party? c:

**Comment by lukas81298** [comment]
Was soll man denn in der party machen?
