### ISSUE TITLE
TNT Schaden Optimieren

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#113]
Soweit ich weis, hat ja Laby dafür gesorgt, dass man den Schaden von TNT nun einstellen kann..

wie wäre es so:

TNT macht IMMER Halb soviel Schaden wie der Spieler Herzen hat.
Beispiel:
Spieler hat 10 Herzen: da ist TNT: Er bekommt 5Herzen schaden.
Spieler hat 4 Herzen: da ist TNT: Er bekommt 2 Herzen schaden.

Und dass sollte noch Per Radius eingestellt sein:

Wenn man innerhalb von 3 Blöcken Radius vom TNT ist, dann bekommt man immer die hälfte des Herzens schaden.
Die anderen die weiter weg als 3 Blöcke sind 0 Schaden

**Comment by LabyStudio** [comment]
Dumm oder so?
/mkeconfig tntdamage

**Comment by HDuck** [comment]
Ok ich bin dumm..
Woher sollte ich das wissen du kennst mich doch :D

Jedenfalls macht das TNT halt irgentiwe 1hit daswegen

**Comment by HDuck** [comment]
Ich weiß nicht wie man closed.
