### ISSUE TITLE
Kit Storm

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#114]
Kit Storm
Item: Ghastträne

*Was passiert wenn man das Item drückt?*

Wenn man sein Item Klickt, dann Spawn eine Wolke und Regen-Partikel über dir.
(Bild Beschreibung: http://prntscr.com/6j2ov5 )
Die Wolke sollte ca. 1 Blöck über dem Spieler sein. 
Die Wollke sollte etwas breit sein (ca. 3x3 wie z.B Spiderman Netzt bei MCPVP) (kann auch mit Radius berechnet werden)

*Was passiert anschließend?*

Wenn nun ein Spieler unter dieser Wolke geht, 
dann bekommt er einige Negative Effekte.
1. Er ist schwächer | Weil ihm Kalt ist                     | Weakness Effect (X Sekunden)
2. Er wird vergifftet | -//-                                          | Poison Effect (X sekunde)
3. Er wird Blitz getriffen | Gewitter                          | Blitz getroffen werden (1 mal)

*Weitere Informationen!*

- Der Cooldown beträgt 35 Sekunden
- Die Negativen Effekte sind "Upgrade-Able"

Hoffe das Kit gefällt dir/euch.

**Comment by CraftingExpertDE** [comment]
Gefällt mir und kenne ich nicht, good job ente =)

**Comment by KnuddelPvPer** [comment]
nice ente

**Comment by EinfachNiggo** [comment]
Cooool!

**Comment by lukas81298** [comment]
echt gut. ein problem gibts nur, wenn etwad über dem Spieler ist.

**Comment by HDuck** [comment]
Hmm,
dann sieht man halt die Wolke nicht..
aber ich glaube man würde sie ganz leicht noch sehen können .. ansonnsten fällt mir keine Idee ein
