### ISSUE TITLE
"/FAQ" Command verbessern & erweitern

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#115]
Kurz:
1.) - Erweitern: Mehr Themen bei /FAQ ansprechen.
2.) - Verbessern: Das Design ändern und einen Bug beheben.

*1.) Erweitern:*
Mehr Themen bei /FAQ ansprechen= :
- "1v1" - Themengebiet
- "Store" - Themengebiet
- "Support" - Themengebiet wo ein Buch wo der Command "/supp" zu finden ist
d.h alle Möglichen Themengebiete schreiben

*2.) Verbessern:*
- 1. Der Bug: http://prntscr.com/6j4dk3 - Die Zeichen [CR] [LP] werden immer angezeigt
- 2. Etwas Optisch verbessern (größtenteils durch Bugfix gemacht) teilweise werden die Zeilen nicht Linksbündig gezeigt, bzw da ist eine Leertaste am Satzanfang: http://prntscr.com/6j4gh3

Wäre auch nicht schlecht dass neue User anfangs dein "FAQ" Command eingeblendet bekommen, damit sie angfangs schon alles wissen

**Comment by lukas81298** [comment]
Kannst du eine neue Liste der faqs machen? Ich kümmer mich dann um die Bugfixes 😊

**Comment by HDuck** [comment]
Na klar! :)

**Comment by HDuck** [comment]
Ich schreib den Text lieber erst auf Deutsch, will kein Grammatikfehler einbauen, paar werde ich auch in Englisch schreiben

___

Gliederung: (Das wenn man FAQ eingibt)

1. Rules
2. Gameplay
3. 1v1
4. Applications
5. Store
6. TeamSpeak
7. Support

___

**1. Rules**

*Chat Rules:*

- Do not spam
- Do not capslock
- Do not advertise
- Do not insult players or staffmembers
- Do not threaten with ddos
- Do not abuse Bugs (da könnt ein englisch-fehler sein)
- Do not abuse the /report command

*Gameplay Rules:*

- Don*t use Hackclients
- Don*t try to team at EarlyHG (we have an anti-2vs1 plugin)       (da könnt ein englischfehler sein)
- Don*t use any modifications that provide unfair gameplay (Macros, Autoclicker.. )

*Allowed Mods:*

- Optfine
- LualMod
- 5zig PvP Mod
- Official MCPVP Mod
- Shader Mods
- Mods which don't affect the gameplay

___

**2. Gameplay:**

*Wo kann ich Spielen?*
Gebe /warps ein und drücke auf ein Item

*Wo kämpfen die meisten Spieler?*
Bei den warps "EarlyHG" und "Feast"

___

**3. 1v1**

*ReadMe*
Go to the 1v1 warp and read your Book

*What does the Diamond Sword?* (Do oder Does idk.)

- Schlage einen Spieler mit dem Schwert und lade ihn auf ein 1v1 ein.
- Wenn du eine EInladung bekommen hast, schlage diesen Spieler mit dem Schwert.

*What does the clock?* (Do oder Does idk.)

- Drücke auf die Uhr um alle laufenen Kämpfe zu sehen
- Drücke auf ein Item um den Kampf zuzusehen

*What does the feather* (Do oder Does idk.)

- Click the feather to open the custom battle menu.
- If you're in a Battle, you can see all people who are in.

___

**4. Applications**

*Where can I apply?
You can apply at http://minekits.eu/apply

*Do I have to write my Application in English?*
Yes.

*Do I need Skype*
Yes, you need Skype as well Teamspeak 3 to become moderator.

*How old I have to be to apply?*
You have to be 13 Years old or older

___


**5. Store**

*Wo kann ich mir einen Rang kaufen*
Auf [Website].

*Was kann man beim Store kaufen?
Gib /buy ein

*Kann man mit Paysafe Card Zahlen?*
Ja, [Text eingeben wie, weil neuer Shop]

___

**6. TeamSpeak**

*Was ist die IP Adresse?*
ts.minekits.eu

*Ich habe einen Rank, wie bekomme ich im Teamspeak einen Channel und einen Rang?*
Schreib einen TeamSpeak admin oder Owner an und frag ihn

___

**7. Support**

*Deine Frage wurde nicht beantwortet?*
Gib /Support ein, falls ein Teammitglied online ist, wird er dir weiter helfen

___

___

___

Puuh. Das war viel Arbeit :D

Hoff es schaut auch Design'isch gut aus :)
