### ISSUE TITLE
Kit Shadow

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#120]
Kit Shadow:
Item Beispiel: Kohle
*Wenn man sein Item Klickt, passiert Folgendes:*

- Spieler im Radius von 5 Blöcken haben "Blindness" (um es Realistischer darzustellen)
- Spieler im Radius von 3 Blöcken haben Effekt "nicht zu gehen" (Als wäre der typ mit dem Shadowkit                  schnell)
- Im Radius von 3 Blöcken sollen (wenn du es Hinbekomst) Partikel erscheinen, welche Schwarz sind, und genau auf der höhe wo der Kopf der User ist => Damit er kaum was sieht, sozusagen Rauchbombe)

*Nun die Ability:*

Er wird 3 mal in Folge in die Richtung Teleportiert in die er schaut.
(1 Teleportation = 3 Blöcke vorwärts) das passiert dann 3 mal

*Weitere Informationen zum Kit:*

- Cooldown für das Item: 45 Sekunden +Upgrade-Able
- Die Effektzeiten dürfen gerne geändert werden!!

Pros: 
Man kann weglaufen zum Recraft etc.
Man kann den Spieler der sich nicht bewegen kan einfach Hitten

Cons:
Der andere Spieler kann in der Zeit auch recraften etc. wird es aber nicht so schnell realizieren weggen den ganzen effekten

___

Ich hoffe du/ihr versteht, wie ich mir das Kit Vorstelle,
hoffentlich ist es auch so Umsetzbar  / gefällt dir/euch/uns/ente.

<2.

**Comment by EinfachNiggo** [comment]
Klingt cool ;D
