### ISSUE TITLE
Kit Snake

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#121]
Kit Snake | 
Ability:

Man muss nicht die Lehrtaste drücken, wenn man auf  ein Block springen will, sonder es ist wie eine Treppe, man kann einfach ohne Springen hoch.

beispiel:

Da ist ein Hügel:

Ohne Snake: Man muss immer leetaste drücken
Mit Snake: Man kann einfach mit Sprint durchlaufen und man muss nicht die Leertaste drücken, dann ist man auch schneller :)

Klein & Fein

**Comment by lejaden** [comment]
Gute Idee. Man muss dennich beachten, dass man das Kit nicht mit bestimmten HackClients verwechselt.

**Comment by HDuck** [comment]
Da hast du recht,
wie wäre es, dass wenn er auf eine Stufe geht, der Block unter ihm durch Dunkelgrüner Clay replaced wird (wie bei den Iron,Diamond,Gold,Emerald-Boots)

Dann kann man es Unterscheiden :)
