### ISSUE TITLE
kit Yoshi

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#122]
Kit Yoshi
Item: 1 Ei
___

Wenn man das Ei wirft, Spawn ein Baby-Schaf (wie bei Kit Grabber ein Baby-Schaf).

Dieses Schaf, verfolgt dich Durchgehend, aber dieses Schaf hat auch Sozusagen "Forcefield" er Hittet alle Spieler im Radius von [X] Blöcken.

Das Schaf sollte so sein, dass es nicht Schlagbar ist, sondern dass es nach [X] Sekunden Despawnt (+UPGRADE-Able)

Wenn man einen Spieler Tötet, bekommt man wieder 1 Ei (+UPGRADE ABLE)

___

Upgrades:

Upgrade 1: Bekomme 2 Eier nach einem Kill
Upgrade 2: Schaf lebt 5 Sekunden länger als Normal
Upgrade 3: Bekomme 3 Eier nach einem Kill

Ich hoffe das Kit gefällt euch.

**Comment by lejaden** [comment]
Ich finde den Namen nicht so sinnvoll gewählt und finde das Kit zu OP.

**Comment by lukas81298** [comment]
Wie kann ein Huhn bitte schlagen?

**Comment by HDuck** [comment]
Ich versteh die COder-Sprache nicht.. dachte das Klappt irgentwie naja war nur ne Idee :D

Und es geht um ein Schaf nicht um ein Huhn xD

**Comment by EinfachNiggo** [comment]
Vielleicht ja dass man auf ein grünes, großes Schaf draufkann (also reiten sozusagen xD) und dann hat man Haste 1, Speed 2 und nach 10Sekunden despwant das Schaf (= Yoshi) wieder und der Cooldown beginnt! 
@HDuck

**Comment by LabyStudio** [comment]
Ich schreibe Biker um zu Yoshi
