### ISSUE TITLE
Kit Supressor Buff!

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#124]
Kit Supressor ist sehr Schwach meiner Meinung:

Der derzeeitige Effekt den man bekommt:
- Slowness für 1 sekunde
- Arrow schaden

1 sekunde ist echt sehr wenig.

Ich würde sagen dass man 3 Sekunden Slowness hat und dass es noch Upgrade-Able. 
UND:

Wenn man ein Spieler tötet bekommt man 5 Spears zurück. 
(Derzeit bekommt man kein "Spear" zurück)

Ich hoffe du übernimmst das so, denn dann kann das Kit echt Konkurenz mit anderen machen :)

**Comment by lukas81298** [comment]
Ist jetzt etwas gebuffed
