### ISSUE TITLE
Kit Portal nach dem Tod Cooldown

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#125]
Wenn man ein Portal mit Kit Portal setzt, anschließend Stierbt, muss man immernoch warten bis die Portale we gehen.

Ist etwas nerfig..

Wie es Fixen gehen sollte:

Nach dem TOt sollen die Portale weg gehen und der Cooldown gleich mit

**Comment by LabyStudio** [comment]
fixed
