### ISSUE TITLE
Grandpa Verbesserung

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#127]
Grandpa ist ja ziemlich schlecht..
1. Könnte man das Upgrade "Knockback IV" hinzufügen. 
2. Könnte man machen, wenn man einen mit dem Stick hittet, bekommt er für 3Sekunden Blindness und 2Hezen DMG, dann sind 10Sekunden Cooldown

Hoffe das ist kuuuhl :)
~ Niggo c;

**Comment by HDuck** [comment]
Ich finds geil! :D
