### ISSUE TITLE
LMS' von Spielern

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#129]
Da viele sich viele Spieler mehrere LMS' wünschen und wir ja relativ wenige machen, könnten wir ja machen, dass Diamonds einmal am Tag ein beliebiges LMS hosten können. Dazu könnte man ja so ein kleines GUI machen wo man alles auswählen kann c: Außerdem vielleicht ein Preis von 500 Coins. Sollte vielleicht erst ab 20Spielern oder so starten.. yoa
~ Niggo c;

**Comment by HDuck** [comment]
Aber dann sollte man das noch einstellen:
- Die Credits die man gewinnen kann, werden von dem Diamond user abgezogen (wenn er nicht genug hat kann er es nicht erstellen)
Wie du gesagt hast:
- Soll erst ab 20 Usern starten können


Wäre eine Spitze Idee :D

**Comment by EinfachNiggo** [comment]
Yeahhhh :)<2

**Comment by lukas81298** [comment]
/lmsmanager

In Grundzügen ist dies bereits implementiert :)

**Comment by EinfachNiggo** [comment]
Oh echt? Das müsste man dann den Usern mal sagen :P

**Comment by lukas81298** [comment]
Die haben keine Rechte drauf und es ist vorerst nicht geplant, dass sie es nutzen.

**Comment by EinfachNiggo** [comment]
Alles klar.

**Comment by lejaden** [comment]
1 LMS am Tag. Zu viel. Und außerdem muss man bedenken, dass nicht nur einer Diamond hat.

**Comment by HDuck** [comment]
1 LMS pro Spieler am Tag so ist es gemeint denk ich

Ich geh mal davon aus, dass es ca. 10 Diamond user gibt idk.

Und die leute würden ja mit ihrem Money den Gewinn Zahlen

**Comment by lejaden** [comment]
Aber dann wär ein lms nichts besonderes mehr

**Comment by LabyStudio** [comment]
Wird durch falldown ersetzt (24/7 Spielbar)
