### ISSUE TITLE
Sehr WICHTIGER "Thor" Bug!

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#130]
Ich habe schon Thor detoggled:

Wenn man THor ist und auf eine Demoman Platte geht, Stiert man NICHT.
Man kann einfach drauf bleiben und es kommen Explosionen.

So wie Bei Tank undso damals.

Easy 2 Fix:

Wie bei Tank machen dass Thor keine Platten betätigt, oder es irgentwie beheben

**Comment by lukas81298** [comment]
fixed
