### ISSUE TITLE
Kit Lasso / CowBoy

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#131]
Kit Lasso / Cowboy
Kit Item: Leine (Renamed: Lasso)

Wenn du mit der Leine Klickst, wird eine Angel rausgeschossen (wie Grappler).
Wenn du dann einen Spieler auf der Angel hast, ziehst du ihn zu dir.
Wenn du einen Spieler auf der Angel hast, kann er nicht weiter als 5 Blöcke von dir weg laufen.
Doch wenn man dann den Slot wechselt, ist er immernoch an der Angel, bis die Maximale "festhalt Zeit" von 10 Sekunden vorbei ist.

-> Man kann Spieler Maximal 10 Sekunden mit der Angel halten, anschließend tritt ein Cooldown auf

Cooldowns:

Wenn man versucht einen Spieler zu angeln, aber man Trifft keinen: 5 Sekunden Cooldown.
Wenn man einen 10 Sekunden an der leine hatte: 35 Sekunden Cooldown

Ich hoffe das Kit ist irgentwie Codebar & das es euch gefällt :D

**Comment by EinfachNiggo** [comment]
Klingt richtig geilo! Meinst du schon, dass er spieler dann nicht instant bei dir ist, sondern so an dich hingezogen wird oder? (Gegenteil von Grappler sozusagen)

**Comment by HDuck** [comment]
Ja genau,
als wäre man ein Cowboy und Zieht ein Spieler :)

**Comment by EinfachNiggo** [comment]
Boah ich feier das richtig :D Muss auf jeden Fall umgesetzt werden! ;p

**Comment by lejaden** [comment]
Hä, gibts doch schon, also sowas in der Art. Fisherman. Ich finds unnötig

**Comment by EinfachNiggo** [comment]
Nein. Das ist geil, ok? Fisherman ist eh lw ..

**Comment by HDuck** [comment]
Fisherman:
Der Kerl wird einfach zu dir geportet:

Lasso:
Er wird zu dir Gezogen, er kann nicht sehr weit von dir weg laufen 
Wie ein Lasso eben :D

**Comment by lejaden** [comment]
Ok, dann hab ich das falsch verstanden, aber gute Idee

**Comment by LabyStudio** [comment]
Fertig.
Kommt morgen!

**Comment by HDuck** [comment]
Freut mich :-)
