### ISSUE TITLE
PvPDojo

### ISSUE THREAD

**Issue by lejaden** [MineKits/MineKits#133]
Hey, wie ihr in den laufenden Tagen bemerkt habt, waren PvPDojo Admins, Coder und sogar schmockyyy auf MineKits. Es ist denen zwar vollkommen egal, dass MineKits einbisschen klaut. Mir eigentlich auch. Aber ich denke, dass es bei den meisten Spielern nicht gut ankommen wird und auch den Ruf von MineKits zerstören wird. Ich höre schon häufig genug von anderen Spielern Sachen wie MineKits PvPDojo 3.0 MineKits klaut usw. Ich persönlich finde, dass wir den Bot entfernen sollten. Gegen die Kits habe ich nichts dagegen.
Andere Meinungen?

Ich weiss Laby, war vielleicht ein großer Aufwand, den Bot zu coden :c

**Comment by HDuck** [comment]
Bin ganz der selben meinung..
das mit dem Bot ist halt echt schon ziemlich Dojo-Haft, da sie auch die Idee hatten.. war ein großer aufwand, aber dann sollte es auch was "selbst-erfundenes" sein :) 

https://github.com/MineKits/MineKits/issues/82
Wurde auch da in den Kommentaren Disskutiert, das wir ab jetzt NICHTS mehr von anderen KitPvP Servern übernehmen (ja gut, waren ehh nur 3kIts von dojo)

**Comment by lukas81298** [comment]
Die Idee einen Bot zu haben ist nicht von PvPDojo sondern ganz simpel aus CS:GO. Ganz PvPDojo besteht aus dem gleichen Systen (Chests,Abilities,Marked...(

**Comment by HDuck** [comment]
Aber sie hatten die Idee dies auf MInecraft umzusetzen

**Comment by EinfachNiggo** [comment]
@HDuck die Idee hatte ich auch schon, aber keiner wollte die machen :D Habe dazu auch schon einen halben Roman zu geschrieben, aber das wäre halt nicht mehr so richtiges KitPvP ;)

Und ich bin auch dafür, dass wir *nix* klauen/abschauen!

**Comment by lejaden** [comment]
Ja, ist eingentlich Dojo ganz egal, aber wie gesagt, die anderen kitpvp server machen uns schlecht.

**Comment by LabyStudio** [comment]
Ich finde auch das es einfach übertrieben ist..

Die Idee vom Bot habe ich aber nicht von CS:GO mir ist das eingefallen als ich diese Wisp erstellt habe
das es viel cooler ist wenn man mit dennen auch fighten kann ;)

Und es ist doch echt egal was wir haben
Dojo hat ja auch alles von mcpvp geklaut (Bevor sie was zusammen gemacht haben)

Und unser Bot ist in der 1.8 und nicht für 1.7 also
haben  wir ja wieder was anderes ..

**Comment by LabyStudio** [comment]
PS: Schmockyyy hat ja bestätigt das es ihm scheiss egal ist

**Comment by LabyStudio** [comment]
Idee:
Wir nennen den Bot einfach 1v1 Simulator

**Comment by LabyStudio** [comment]
Überlegt euch nochmal:
Wir bieten dinge die Dojo nicht hat (1v1 bot in der 1.8)
Ja klar spielen wenige in der 1.8 aber dafür ist es up to date ;)

**Comment by HDuck** [comment]
Aber Ideenetechnisch ändert es ja nichts.

Da ist ja immernoch das Selbe Plugin wenn du es Umbenennst

Nunja, ist mir jetzt auch egal.
Du kannst ja irgentwas neues aus dem Bot zaubern, was es sonnst nicht gab.

z.B Man macht ein Bot vs Bot, und wettet auf einen (fürs Casino bsp.)
Oder ein Kit, wo ein Bot Spawnt und dann ist es so 2v1 oder so idk

**Comment by LabyStudio** [comment]
Wird durch Trap Escape Emulator ersetzt

**Comment by EinfachNiggo** [comment]
Yeahh Niggo hatte mal wieder ein tohle Idee c:
