### ISSUE TITLE
Trap-Bot

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#135]
Souuu..es meinte einer im Skype-Chat, dass wir den Bot doch für was anderes nutzen könnten. Hier meiner Meinung nach 'ne coole Idee!
Wir könnten verschiedene Traps aufbauen und dann wird man mit /trap oder so da hingeportet. Also in die Trap. Von unten (also der Traperplatz) hittet dich der Bot und du musst versuchen zu escapen. 
Um das ganze noch cooler und professioneller zu machen, kommt dann zuerst ein Gui, da waehlt man aus:
- Bot-Schwierigkeit (Woodsword, Stonesword,..)
- Die Trap (wir bauen verschiedene, bekannte Traps nach)
- Andere Schwierigkeit.. xD (Also ob man Steinpicke und Axt hat, oder Holz, oder nix und wie viele Soups)

Dann spawnt man da drinnen und muss die Trap abbauen - also rauskommen - ubd den Bot noch killen, der nicht soo viele Suppen haben sollte.
Währenddessen wird dann noch die Zeit gemessen. 
Ich fände das ultra cool!! :)
~ Niggo c;

**Comment by HDuck** [comment]
BOA das wäre richtig geil :D

Und gleichzeitig vlt so machen dass man bei der Stelle blöcke abbauen kann!
Das ist ne Hammer Idee, perfektes HG-Trap-Training, 
gabs bisjetzt in keinem server (soweit ich weis)

**Comment by HDuck** [comment]
Man könnte doch auch Bei warp Lava statt Lava Hinzusetzen einfach 2-4 Bots in nen Kasten stellen (je nach Schwierig keit) das wird dann irgentwie 2v1 so ein Training dafür,
wenn man 2v1 oder 3v1 Wird
(die Bots sollten Unzerstörbar sein)
oder iwie so :D

**Comment by EinfachNiggo** [comment]
Danke :D Blöcke darf man natürlich abbauen, dass man aus der Trap kommt ;)
Gab's bis jetzt nur auf Dreamkits.. :P - Also hopp auf Minekits! :3

**Comment by LabyStudio** [comment]
Ich finde dafür brauch man kein Bot

**Comment by LabyStudio** [comment]
ups

**Comment by LabyStudio** [comment]
Du kannst auch ganz normal so dmg bekommen..
es sollte was sein wo du auch gegen den bot kämpfen musst

**Comment by LabyStudio** [comment]
Aber das man den bot dann noch killen muss ist halt wieder dojo
..........
Aber coole idee!

**Comment by LabyStudio** [comment]
Mache ich ;)

**Comment by EinfachNiggo** [comment]
lol :D
