### ISSUE TITLE
"Shop-Item" im Inv am Spawn.

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#136]
- Ich fände es praktischer, wenn es ein allgemeines "Shop-Item" im Inv gibt. Da es so überall "verstreut" Zeug zu kaufen gibt.. :p also boots kits..
- Dann kann man das ja so machen:
Man öffnet das Buch und es kommt sozusagen als Gui 'ne kleine Chest. Da gibt's dann:
- Boots
- Kits
- Exp Boost (oder wie das heißt)
- Extras
Klickt man dann da drauf, wird dann alles aufgelistet mit Preis etc. :) Ich glaube das wäre gerade für neue User praktischer. 

PS: Kann mir auch gerne mal paar "Extras" ausdenken, dies zum kaufen geben könnte ;)
~ Niggo c;

**Comment by HDuck** [comment]
Es gibt doch /menu (der Stern im Inv) 

yaa gut da sind noch Stats achivments etc dabei:D

**Comment by lukas81298** [comment]
Lässt sich machen. Hab ich auch schon drüber nachgedacht

**Comment by EinfachNiggo** [comment]
Nice :) Wir könnten ja nicht nur das, sondern allgemein das Spawnzeug bisschen aufpeppen ;) zB Battle ist meiner Meinung nach unnötig (ich weiß nicht mal genau was das macht xD)
Vielleicht Menu bisschen strukturierter. Und dann wars das
Quickplay, Enderpearl, Shop, Menu c:

**Comment by HDuck** [comment]
Find ich auch, einfach mal bisl anders damit nicht so viel Crap da ist.

Achja, das BattleItem: Da wirst du zu 1v1 Teleportiert

**Comment by WhitestoneMafia** [comment]
Wäre ne tolle idee xP

**Comment by LabyStudio** [comment]
Super!

**Comment by LabyStudio** [comment]
Mach mal xD

**Comment by EinfachNiggo** [comment]
:)
