### ISSUE TITLE
Extras für den Shop | Idee | Frage

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#137]
Extras für den Shop!

Eigene Killnachricht:
Es kommt ja, wenn man einen killt so über dem Boden "BlaBlaBla 5,9263 Coins bekommen".
Wenn man eine "Killnachricht" für sagen wir 1000Coins kauft, kann man diesen Text individuell ändern. (Höchstens irgendwie 20 Buchstaben.) Und dann kann man das aktivieren und wenn man einen killt, kommt das.
Für 500 Coins kann man die Nachricht ändern. Für 1000 eine neue, zweite kaufen und dann kann man halt zwischen den beiden wechseln, oder das Standart nehmen c:

Leather-Chestplate:
So.. eigentlich sinnlos, aber wir die Kleinigkeiten machen's aus :D (Ok.. die nicht).
Also man kann sich 'ne Chest (Leder) für so ca. so viel wie die Boots kosten kaufen. Die kann man dann mit /chest anziehen. Wenn man die anhat, schreibt man automatisch in dieser Farbe im Chat (Halt nur am Spawn.)  Wenn man zB Gold-Rang ist, hat man die orangene umsonst. 

Anderes Zeug:

Kit-Sponsoring
So 'ne spontane Idee: Man kann einem anderen ein Kit sponsoren, d.h. man kauft es ihm, bekommt aber so 30% der Coins, die der der das Kit hat mit diesem Kit halt an Kills macht.

Frage:
Das mit dem 1v1 auf der ganzen Map fandet ihr nicht so cool oder? Fände ich ganz kuhl :P

~ Niggo c;

**Comment by EinfachNiggo** [comment]
Beitrag: /chestplate oder so lieber. Und man kauft halt die Chest, die die Farbe hat in der man schreiben mag.
Und man kann die Killnachricht nur einmal ändern, außer man kauft sich das für 500.

**Comment by LabyStudio** [comment]
Eigene killnachricht ist ne coole idee ^^
Leather chestplate brauch man nicht und ist komisch
kit sponsering nicht so cool
1v1 auf der ganzen map würde zu viel verändert am 1v1 system

**Comment by LabyStudio** [comment]
Ich lasse es offen wegen der Custom killMSG

**Comment by EinfachNiggo** [comment]
Fand eigentlich den Rest auch scheisse :D Aber cool, dass du die Killmessage machst c:

**Comment by LabyStudio** [comment]
Vllt das es wie auf Raid ist das die schwerter einen namen haben?
In der kill msg könnte man den namen anzeigen lassen

**Comment by HDuck** [comment]
Das mit den Custom Nachrichten finde ich gut :D
VOrallem weil die Nachrichten so lang sind,
man will eigentlich nur wissen:

Herzen: (leben)

Verdient: (geld)

Verdient: (XP)

mehr braucht man auch nicht xD

**Comment by lukas81298** [comment]
Es wird bald möglich sein den Namen des Schwertes zu ändern. Der wird dann auch in der Kill msg angezeigt.

**Comment by EinfachNiggo** [comment]
Nice!
