### ISSUE TITLE
Wünsche zu Falldown?

### ISSUE THREAD

**Issue by LabyStudio** [MineKits/MineKits#138]
Bald kommt Falldown und ich wollte fragen ob ihr nicht ein paar Ideen und wünscht habt die
nicht fehlen sollten!

Also ab in die comments! ;)

**Comment by lejaden** [comment]
Am besten keine riesige Map oder vielleicht dass jeder ein Kompass bekommt :)

**Comment by LabyStudio** [comment]
@lejaden wird mit einem Blitz sein und die Map ist r=100

**Comment by EinfachNiggo** [comment]
'Ne Käse-Map! ;) (Baut spielt auf einem Schweizer Käse mit so Löchern wo man rein kann ;D)

**Comment by LabyStudio** [comment]
Update kommt Heute!
Deswegen ist es jetzt zu spät für Ideen.. sorry!
