### ISSUE TITLE
Neue 1v1 Maps! @Builder

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#139]
Meiner Meinung nach, sollte dieser Server neue 1vs1 Maps haben.
Am besten 4 mal so groß wie die Jetzigen.

Die jetzigen Maße: 31x31

Da wir nicht die Timolia Maps nicht so "klauen" wollen,
hab ich mir überlegt vlt. runde Maps zu machen.

So:

//Hcyl <Block> <Raduis bsp. 31> <Höhe ideal 20)
also:
//hcyl <Block> 31 20

(veranschaulichung: http://prntscr.com/6l89al )

Und die Builder könnten ihrer Kreativität ein freien lauf geben, wie die Maps sind.

Bsp. Schneelandschaft, Gebierge, Plants, Nether, End ...

Die jetzigen Maps sind für viele User unter anderem mir oder Schweini viel zu klein.
(Ich weiss, dass man auch andere Maps z.B "Default" nehmen kann.)

Wäre jemand dagegen?
Wer lust hat darf gerne bauen :D  (besonders an die Builder gerichtet)

___
Anil

**Comment by LabyStudio** [comment]
Wurde schon angefangen.. haben aber keine Builder mehr

**Comment by HDuck** [comment]
Wäre es okey, wenn ich das irgentwo auf der Map mache,
falls es dir/euch gefällt übernehmt ihr es - wenn nicht - dann nicht
