### ISSUE TITLE
LMS "Fallingblocks"

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#140]
LMS IDEE:
"Fallingblocks" - Name kann geändert werden

Das ist so aufgebaut wie das Anvil event.

- Alle Spieler werden in ein viereckigen ca. 50x50 Raum teleportiert.
- Von Oben fallen so wie beim Anvil event blöcke (keine Anvils)
- Der letzte der überlebt gewinnt.

Sozusagen: Von der luft fällt Falling sand (aber schaut nicht aus wie sand sondern Wolle falls es geht)
Wenn man von dem Sand getroffen wird, stierbt man.

So soll das Ungefähr ablaufen:

Im chat steht:

"Nun fallen 15 Blöcke" (+Übersetzt auf Englisch)

dann fallen random bei dieser arena die 15 Blöcke runter.

Wenn einer getroffen wird, ist er ausgeschieden.

Das kommt dann so oft, bis nurnoch einer lebt.

Hoffe ihr versteht wie ich das beschreibe xD.

___

Anil

**Comment by LabyStudio** [comment]
Finde ich gut. Werde ich Morgen machen

**Comment by EinfachNiggo** [comment]
Klingt cool :) ist das nicht einfach dieses anvil lms mit sand? :D

**Comment by HDuck** [comment]
Ja :D
Aber Anvil ist zu Mainstream :D

Und HALLO Sand das aussieht wie Bunte wolle :D Was will man mehr xD
