### ISSUE TITLE
Im Gladiatorkasten geht kein Ninja (falsche region?)

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#141]
Im Gladiatorkasten kann man seine Ninja Fähigkeit nicht benutzen!*

Ist die Region Falsch gesetzt  @LabyStudio ?

Bug found by Ni© (nico)

**Comment by LabyStudio** [comment]
Sonst könntest du dich raus tpn?

**Comment by HDuck** [comment]
Nein Laby, früher ging das auch,
das ist ja die Ability von Ninja,

dass der auch im Gladiatorkasten gegen den Gladiator Ninja'en kann.
Selbst bei MCPVP geht es sich damit rauszuporten, das ist ja auch ein Zweck der Ability.

Easy2fix

Regionen weiter oben setzen, wo Gladiatorkösten dabei sind.

(Ich wollte das nicht machen, weil du am in der Luft so schilder gemacht hast, wo die Regionen auf Schildern steht (Bild: http://prntscr.com/6lc9ya ) und wollte es nicht Kaputt machen oder sonnstiges.

Daher bitte beheben :)

**Comment by LabyStudio** [comment]
Die Schilder bleiben auch so wie sie sind
Sorry aber dafür müssen wir uns was anderes überlegen
Ich frage mal lukas
