### ISSUE TITLE
Kit: Suffocater

### ISSUE THREAD

**Issue by CraftingExpertDE** [MineKits/MineKits#145]
- Kit Item = Bedrock
- Cooldown = 50 seconds
- Ability = Wenn mit deinem Bedrock einen Spieler schlägst/rechtsklickst wird er 3 Blöcke unter die Erde tpt und suffocated dort und wird nach 30 seconds wieder hochtpt, du kannst diese chance nutzen um zu recraften/refillen, wenn dein gegner oben spawned bekommt er 10 sekunden recistance 100, damit er sich sortieren kann und der Kampf geht weiter.

**Comment by lejaden** [comment]
30 Sekunden finde ich übertrieben, denn dann würde jeder aus langeweile combatloggen. Vllcht könnte man es so wie Prisoner machen, also die Zeit und den Schaden, halt nur unter der Erde.

**Comment by LabyStudio** [comment]
Das Kit würde nerven :o
