### ISSUE TITLE
Prisoner Bug! Fallschaden

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#146]
Wenn man Kit Prisoner ist, und Gladiatort wird, 
muss man den Gladiator Prisonern.

Wenn er dann in der Lava war, und runter kommt, FÄLLT er runter.

-> Er bekommt Fallschaden und Stierbt instand.

How 2 Fix:

Nachdem man Gladiatort wird, bekommt man [X] Sekunden kein Fallschaden

**Comment by LabyStudio** [comment]
@lukas81298
