### ISSUE TITLE
4 Kits

### ISSUE THREAD

**Issue by CraftingExpertDE** [MineKits/MineKits#147]
==================================================================================
KIT MAGNET
- Kit Item: Iron Ingot
- Ability: Wenn du dein Iron Ingot rechtsklickst werden alle spieler im radius von 5 blöcken an dich herangezogen.
- Cooldown: 30 Seconds

==================================================================================
KIT SUN
- Kit Item: Yellow Wool
- Ability: Wenn du deine Yellow Wool rechtsklickst, bekommen alle spieler die dich hitten in der Zeit Feuer. Runtime: 15 seconds
- Cooldown: 25 Seconds

==================================================================================
KIT NEPTUN
- Kit Item: -
- Ability: Wenn du im Wasser bist und einen Gegner hittest fliegt er 10 blöcke weg egal welche Richtung. 
Cooldown: -

==================================================================================
KIT BLOCKER
- Kit Item: -
- Ability: Wenn man mit dem Schwert blockt bekommt man 1 Herz weniger Schaden
- Cooldown: -

==================================================================================
by Weihnachsmann.

**Comment by LabyStudio** [comment]
"Kit Blocker ist mit Blockhit glaube zu OP muss man schaun :D"
~Anil

Ich glaube es ist eig. richtig nice
Weil du kannst ja in der Zeit nichts machen ^^

Wir könnten Blockhitten für dieses Kit auch disablen!

**Comment by LabyStudio** [comment]
Ich mache Blocker
