### ISSUE TITLE
Kit Thor bei NoSoup verbieten

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#148]
Kit Thor ist bei "Toggle Kits".

Ich glaube das liegt daran, wegen NoSoup, dass es da funkt, bin mir aber nicht sicher.

--> Thor in Blacklist bei NoSoup 
......     => Problem gelöst

**Comment by HDuck** [comment]
Ich weis nicht als was ich das Labeln soll, daher "bug".

**Comment by lukas81298** [comment]
Ist, geht beim nächsten Update live.
