### ISSUE TITLE
Kit Aura zu OP für NoSoup!

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#149]
Wenn man KIt Aura hat, und in NoSoup ist, kann man auf die Druckplatte gehen, die dir leben gibt,
seine "Aura" aktivieren und immer volle herzen holen.

Wenn man 40 von den Items hat
kann man das schon 4 Mal + machen

=> Toggle bei NoSoup

**Comment by HDuck** [comment]
Ich weis nicht als was ich das Labeln soll, daher "bug".

**Comment by lukas81298** [comment]
Die Druckplatten haben nen Cooldown von 20 Sekunden.
