### ISSUE TITLE
Kit Biker Buff

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#150]
Meiner meinung ist das Kit Biker etwas "Mangelhaft".

Man kann nicht richtig über Halfsleps/ Treppen fahren

kannst du das einstellen, dass das geht?

Kit Biker bringt eigentlich nur was, wenn man ein Berg hochfährt, im normalen boden ist man langsamer als eine normale person

**Comment by LabyStudio** [comment]
Ich bin noch am überlegen.. Minecarts können nichts schneller fahren :/

**Comment by HDuck** [comment]
Bei Dojo haben die's hinbekommen

**Comment by LabyStudio** [comment]
ES IST AUCH DOJO XD

**Comment by EinfachNiggo** [comment]
Haha :D

**Comment by HDuck** [comment]
Könntest du wenigstens einstellen,

dass Biker kein Damage von Suffucation/Fallschaden bekommt?

Wenn man bsp. gegen einen Hohen berg fährt um Hochzufahren, bekommt man Fallschaden (teilweise)

Und wenn man gegen die Häuser beim Village Fährt kommt auch irgentwie Suffucation schaden.
