### ISSUE TITLE
Kit Golem Eisenhelm in EarlyHG cheaten!

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#151]
Man kann ein Eisenhelm zu EarlyHG cheaten:

___

1. Kit Golem wählen

2. Geh zu /warp Feast oder /waro NoSoup

3. Drücke die Blume und gebe dann /warp EarlyHG ein

4. Laufe etwas weiter in EarlyHG rein, damit du in der EarlyHG arena bist

5. Warte ein Paar sekunden und du hast deinen Helm

___

Woran das liegt:

Weil man einen "EisenKopf" bekommt, wenn man im Iron mode ist.

Wie kann man es Fixen:

=> Helm Entfernen

Statt dem helm fände ich dann sowas wie Silberne Partikel oder das der Boden wo man geht zu Eisenblöcken wird gut.

___

Ich weiss, es ist kein Großer bug, aber man kann sich halt rüsstung Cheaten.

Habs vorsichthalber getoggled bevor es jemand rausfindet oder so

**Comment by LabyStudio** [comment]
Das ist kein toggle wert.
Bin am fixen

**Comment by LabyStudio** [comment]
fixed
