### ISSUE TITLE
Kit MLG - Nach Tod wasser Bekommen - Wie bsp Endermage

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#152]
Wie wir ja wissen:

Wenn man Endermage ist sein Portal setzt und Stierbt, dann bekommt er nach dem Tod sein Portal.

Das selbe geht auch Mit Kit MLG.

Wenn man bei MLG sein Wasser setzt, aber halt Stierbt, und das "Death-Menü" schnell Quittet, bekommt man sein Eimer zurück.

Dann hat man sozusagen 2 Kits

jemand hatte diesen Fix vorgeschlagen:

Wenn man in der Arena Spawn ist, bekommt man nach dem Tod keine Kit Items (ich bin mir nicht wirklich sicher ob dieser satz weiter hilft)

**Comment by LabyStudio** [comment]
Sehr schwer zu fixen
ist auch unwichtig finde ich

**Comment by HDuck** [comment]
Das Problem ist halt besonders bei MLG da,
wenn man als ENdermage das Portal hat bringts ja nichts,
aber als MLG kann man den Eimer immernoch nutzen^^
