### ISSUE TITLE
Kit Neo änderungen! +/-

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#154]
So:

Wie wir ja wissen, ist Neo nicht gerade das "Favoriten" Kit.
daher würde ich diese Changes Vorschlagen:

- Es umbenennen zu "Reflector" "Mirror" oder "Anti-Kit"(=Mein Favorit)

Was ist neu?

Das Kit Reflektiert alle Kit Abilitys! bzw. bekommt den Effekt von den Kits nicht.

Beispiel:

Jemand Monkt dich, aber weil du Reflektor bist, wird er gemonkt.

Bei dem Monk erscheint die Nachricht "Er ist <KitName> du kannst ihn nicht blablabla.."

___

Hier die Liste aller Kits und ihre Reflektionen: (Nicht bei allen Kits, damit es nicht zu OP ist.)

Anchor: Er macht dir Knockback

 Fisherman: Er hookt sich selbst

Gladiator: Er kann dich nicht rechtsklicken (ist bereits so)

Golem: Er fliegt nach oben bei einem Hit

Grappler: Er kann dich nicht Hooken

Monk: Er monkt sich selbst

Prisoner: Er Jailt sich selbst

Reaper / Pyro / Snail / Viper: Er gibt sich selbst den Schaden

Kit Snowman: Der Schneeball trifft dich nicht

Stomper: Er macht dir kein Schaden (aber ihm selbst idk ob das geht)

Supressor: Der Pfeil trifft dich nicht

Switcher: Der Schneeball Trifft dich nicht

Zeus: Die Axt trifft dich nicht

___

Ich hoffe das ist Möglich zu machen.

**Falls** es zu OP ist, dann macht es dass man ein Item drückt, und dann der "ANTI-KIT Modus" startet, aber nur falls es zu OP ist

Hoffe das Kit gefällt dir/euch

**Comment by LabyStudio** [comment]
Wird nicht funktionieren weil das Kit system anderst ist :/
