### ISSUE TITLE
Kit Gladiator nerf

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#155]
Wie wäre es, wenn man bei einem Gladiator Kampf auch Abhauen kann?

Undzwar wenn man Ein Gladiator Kasten Erstellt,
soll das Passieren:

a) Random auf Irgenteiner Seite Spawnt ein Loch 2x1 Loch wo man Runterspringen kann.

b) Man kann dass Glass an der Seite Abbauen (aber nicht so schnell)

c) Es spawnt Automatisch an der Seite eine art "Treppe" und oben ist kein Dach
(Screenshot: http://prntscr.com/6mc4ka )

oder irgentwie anders, wo man ne Chance hat rauszukommen.

1.2)

Der Gladiator muss dich mit seinem Item 5 Sekunden gedrückt halten,
damit der Kasten spawnt. Als hinweis steht auch im Chat wie lange man ihn noch rechtsklicken muss (countdown)

___

Gut oder vlt zu OP?

ps. Wenn der Typ es schafft raus zu kommen, kann er immernoch an Fallschaden sterben, daher muss man auf einer Liane, Wasser etc landen

**Comment by LabyStudio** [comment]
Sorry aber ist echt scheisse xD
