### ISSUE TITLE
3 Kits 

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#156]
**KIT VAMPIRE**

Wenn man einen Tötet bekommt man einen "Instand Damage" 1 oder 2 Pot. (kannst du entscheiden)

TIPP: Damage 1: 3 Herzen schaden || Damage 2: 6 Herzen schaden

Man kann diesen Instand Damage Pot auf eine Person werfen und er bekommt schaden. Wenn du dich selbst Triffst, bekommst du Regeneration 2 für [X] Sekunden.

Upgraden: Damage bzw Regeneration Zeit.

___

**Kit Sorter(=Sortierer)**

Name kann geändert werden.

Wenn man sein Item drückt, wird das Inventar Sortiert:

Alle Pilze und Bowls gehen Oben Rechts,
das Schwert in den 1. Slot, und deine Suppen werden auch sortiert und in die Hotbar gesteckt.

Beispiel:

Früher: http://prntscr.com/6mchrk

Nachher: http://prntscr.com/6mchx3

COOLDOWN: 1 Minute

___

**Kit Sender** 

Name kann geändert werden.

Wenn man einen Spieler Rechtsklickt, wird er weit Weg teleportiert für 5 Sekunden, dann wieder her teleportiert.

-> Suprise Attak / Recraft etc.

Während er weg Teleportiert wird, sieht er garnichts (das "opfer") 
 -> Er hat Blindness und Übelkeit

___

Hoff es gefällt euch

**Comment by LabyStudio** [comment]
1. Zu OP?
2. Mache ich
3. idk

**Comment by lukas81298** [comment]
2. Ich machs. Man kann das ja an die Kit Settings anpassen

**Comment by LabyStudio** [comment]
Lukas das ist zu op
ist ja wie autosoup xD

**Comment by lukas81298** [comment]
meinte 2.

**Comment by HDuck** [comment]
Kit Vampire hatten wir ja damals fällt mir grad auf.. irgentwann wurde es removed weils nicht geklappt hat xD

**Comment by lukas81298** [comment]
Also kit Sorter hab ich gemacht. Die anderen sind glaub ich nicht so toll.
