### ISSUE TITLE
Kit Dragon

### ISSUE THREAD

**Issue by CraftingExpertDE** [MineKits/MineKits#157]
- Kit Item: Fireball
- Ability: Wenn du dein Fireball rechtsklickst spawnt eine Aura, diese fliegt in die richtung die du schaust aus Feuer(Soll das Feuerspeien eines Drachens darstellen) mit partikel, die auch kommen wenn du einen Spieler brennenden Spieler hittest. 
-Cooldown: 30s
- Immer: Und man bekommt von Crits keinen Schaden(soll der Drachenschweif darstellen mit dem            man die sozusagen ablenken tut.

**Comment by lukas81298** [comment]
neeee
