### ISSUE TITLE
Von Feast zu EHG laufen => Man behält die sachen in den Kisten

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#159]
Wenn man vom Feast aus,
paar Kisten looted, (TNT,Cobweb,Bogen,Pfeil etc.)
kann man zu EarlyHG laufen.

Das ist sehr OP, da man im Feast eine höhere Item Rate hat..
man kann sich also bsp. 9 TNT oder so einfach vom Feast und Mini feast ergattern.

**Comment by lukas81298** [comment]
Ist mir wurscht
