### ISSUE TITLE
1v1 - Ideen zur leicheren bedinung

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#162]
Hey Lukas,
mir ist aufgefallen wieso viele das 1v1 System nicht verstehen.
Ich habe gerade ca. 5-10 Stück gespielt mit verschiedenen Leuten und hab das Festgestellt:

___

- Sie wissen nicht wie man ein Battle Leaved.

Nachricht die Sie bekommen: You're alredy in a Battle"

Wie man es machen kann:

Ein Item im Inventar mit dem TItel "Leave current battle" wenn man in einem ist. (Sie kennen die Funktion in der Feder nicht)

___

- Sie wissen nicht wie man ein 1v1 annimt

Viele versuchen ein 1v1 mit der Hand anzunehmen

Mit der Hand 1v1 Anfragen annehmen 

___

- Immer wenn die Kleinen Maps kamen, sind sie ausflippt und meinten es sei zu klein.

=> Builder der mal was Baut.

___

Ich hoffe da wäre was Umsetzbar (Außer das build, dass ist für die Builder)

Jedenfalls wäre es einfacher zu bedienen :)

**Comment by lejaden** [comment]
Ehrlich gesagt, finde ich das alte 1v1 system trotzdem besser. Vorallem das random 1vq

**Comment by HDuck** [comment]
Das ganz ganz ganz alte?

**Comment by LabyStudio** [comment]
Die User hoste aber öfters auch 2v2 usw
