### ISSUE TITLE
Feuer Partikel wenn man Brennt @Laby

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#163]
Vielen gefallen die Partikel nicht wenn man Brennt. 

Es nimmt anscheinend "Zu viel Sicht" weg. 

Bitte entfernen für das Normale Spielen :)

@LabyStudio

**Comment by lejaden** [comment]
welche feuerpartikel O.o 
Es gibt dafür geeignete texturepacks.

**Comment by HDuck** [comment]
*Geh mal in MIneKits, und spring ins feuer.*

Da kommen so Partikel ^^ (nicht vom Texturepack) Laby muss schon wissen was i mein

**Comment by HDuck** [comment]
* Wurde gemacht.
