### ISSUE TITLE
Prisoner Gladiator bug!

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#164]
Wenn man im Gladiator Prisoner benutz, stierbt dieser an Fallschaden.

Ich hatte eig. das Kit Getoggled, aber der Bug wurde vorhin von vielen Abgeused.

Bitte einstellen, dass man im Gladiator Kampf nicht Prisonern kann (wie Jumper/Escaper)

**Comment by lukas81298** [comment]
du musst issues nicht zweimal aufmachen (ist auch schon gefixed)
