### ISSUE TITLE
Grappler änderungen?

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#165]
Sehr viele (wie du bestimmt auch bemerkt hast) hassen den Grappler cooldown.
Ich hätte da eine Idee wie es vlt. noch Fair sein kann:

- Wenn man sich zu dem Spieler Grappled der dich zuletzt gehittet hat: 1 Sekunde Cooldown (nach hit)

- Wenn man sich zu einem Block Grapplen will: [So wie jetzt] Sekunden Cooldown (nach einem Hit)

> der dich zuletzt gehittet < 
Falls das nicht geht kanns auch ganz normal Spieler sein :) 

Wäre das möglich zu machen? Oder willst du es lieber so lassen? 

Anil ;3

**Comment by lukas81298** [comment]
ne :3
