### ISSUE TITLE
Kit Zeus = Kit Puncher

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#168]
MIr ist aufgefallen, dass Kit zeus genau das selbe wie Puncher ist.

Zeus: Axt Werfen + Punch + Damage
Puncher: Pfeil schießen + Punch + Damage

Daher sollte man das irgentwie so machen, dass es nicht so ähnlich ist.

Vlt irgentwas dazu machen,
oder von kit Zeus den "Punch" effect weg machen. (Punch effect => Rückstoß) 

Noch dazu ist Zeus im gegenstz viel Stärker - da Zeus weniger Cooldown hat

**Comment by lukas81298** [comment]
Puncher = Pfeil schießen, Punch minimal Damage und Effekte
