### ISSUE TITLE
Wichtiger Mute Bug!

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#169]
Wie wir ja schon wissen,
wenn man /mute <player> macht,
wir man automatisch 45 Jahre gemuted.

Ich habe gerade einen Spieler für 5 minuten gemuted (/mute <player> 5m)

Es hat mich im TS angeschrieben, dass er 45 Jahre gemuted ist.

!!@MODS: Keinen Muten!!

Das was ich sehe: http://prntscr.com/6oiggr
Das was er sieht: http://gyazo.com/9923a920bc9f930513b2b0c7052344f2

**Comment by lukas81298** [comment]
ist bereitd bekannt und gefixed
