### ISSUE TITLE
Gladiator wie MCPVP - Man muss Spieler zuerst Hitten

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#170]
Hey Lukas,

MCPVP hat Gladiator UPDATE gemacht, sodass das Kit nicht mehr so nervig für die Spieler ist:

Man muss den Gladiator erst 3 mal Hitten, bis er dich Gladiatoren kann.

Wenn er dich noch nicht 3 mal gehittet hat, kommt so eine nachricht: "You haven't been hit enought!"

Das würde vielen Spielern denke ich mal "erleichtern".

-> Weniger Killsteals

-> Man kann sozusagen Entscheiden ob er dich Gladiatoren wird 

Hoffe dir gefällt das so, und dass es Umsetzbar ist

**Comment by lejaden** [comment]
Diesen MCPVP Update gibts schon seit ewig :D Aber gute Idee.

**Comment by HDuck** [comment]
Ich find das halt übels nerfig bei MineKits:

Man tötet fasst einen, und dann kommt so'n Spacko von Hinten und Gladiatort dich oder den anderen
 :(

=> Kill weg

**Comment by lejaden** [comment]
Da fällt mir etwas ein
