### ISSUE TITLE
Kit Cowboy Linksklick = lasso Release

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#174]
Mit kIt Cowboy:

Wenn man mit dem Kit Lasso einen Trifft, kann man auch mit Linksklick das Lasso "loslassen", obwohl das nur mit rechtsklick gehen sollte.

Da kommt nichtmal eine Nachricht "lasso released".

Daher einfach machen, dass man nur mit Rechtsklick das Lasso loslassen kann

**Comment by LabyStudio** [comment]
fixed
