### ISSUE TITLE
Kit: Anti

### ISSUE THREAD

**Issue by lejaden** [MineKits/MineKits#175]
Wir der Name schon sagt, ist das ein Kit, um sich zu "schützen". Eigentlich eine Erweiterung zu Neo.
Gladiator: Man kann nicht gladiatort werden.
Prisoner: Der Prisoner, prisont sich selbst
Viper: Gibt sich selbst vergiftung.
 
Updates vielleicht: immer bei verschiedenen Abilties.

Ich weiss nicht ob es zu OP ist.

Bonuspunkt für Jaaaden

**Comment by lukas81298** [comment]
Hm, klingt interessant, ist aber glaube ich zu op. Mal schauen wie man das balancen kann  ;)

**Comment by HDuck** [comment]
https://github.com/MineKits/MineKits/issues/154

Hatte auch sowas schon vorgeschlafen

also eine Erweiterung von Neo.

Laby hatte aber gemeint:

Zitat: "Wird nicht funktionieren weil das Kit system anderst ist :/" 

Aber ne geile Idee

ps. man kann mit Neo auch nicht Gladiatored werden

**Comment by lukas81298** [comment]
Naja, man kann nicht automatisch jede kit ability 'umkehren', aber man kann das manuell machen.
