### ISSUE TITLE
1v1 Zombie aussehen wie der eigener Skin

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#177]
hey,

Wie wäre es, wenn der 1v1 Zombie bei Battle so aussieht wie Du?

Würde das überhaupt gehen? Also damit meine ich:

Spieler "ABC" schaut den Zombie an:

Der ZObie hat den Skin von "ABC" heißt aber immernoch "1v1 Zombie"

und das für jeden anders.

Könnte man das so irgentwie einstellen? Wenn ja wäre es doch schon recht gut,
da manche auch behaupten wir klauen von Timolia weil sie ja auch die Zombies haben.

Falls das mit dem Skin nicht geht, einfach lassen ^^ :)

**Comment by lukas81298** [comment]
Wird für die 1.8 nicht möglich sein, 1.7 schon

**Comment by HDuck** [comment]
Du hast ja sowieso getwittert, dass wir nicht vollständig auf die 1.7 Updaten, oder nicht?

Letzendlich auch deine Entscheidung ob du's haben willst dass sie die Skins haben..

oder du kannst doch vlt machen, für die 1.8 User werden Steve skins gezeigt, oder im Zweifelfall Villager ohne Sounds wenn nicht deine Entscheidung

**Comment by lejaden** [comment]
Klauen, klauen, klauen... Man kann ehrlich gesagt nichts mehr selber erfinden. Und solche Sachen wie Zombie oder so, finde ich ehrlich gesagt nicht geklaut, das haben viele Server, Timolia, Gomme ...
Aber wär eine gute Idee :)

**Comment by HDuck** [comment]
Stimmt, bsp auch MinePlex hat z.B die Mobs um "Kits" zu wählen ^^ Naja war nur'n Vorschlag weil das einer in den Chat geschrieben hatte

**Comment by EinfachNiggo** [comment]
Wäre cool :) Wenigstens in der 1.7 c;
