### ISSUE TITLE
NoSoup Bug

### ISSUE THREAD

**Issue by lejaden** [MineKits/MineKits#178]
Also ziemlich schwer zum Erklären, deshalb in Stichpunkten:

- /warp nosoup
-/clicktest
- bei 8xp Schwert verzaubern
- fire aspect oder sharp 2

Taadaaaaa bonuspunkt für Jaden

**Comment by lukas81298** [comment]
oke

**Comment by HDuck** [comment]
Einfach einstellen, dass man beim Clicktest nicht auf Enchantment Table zugreifen kann, bzw sie nicht rechtsklicken kann, oder?

@LabyStudio
