### ISSUE TITLE
Event

### ISSUE THREAD

**Issue by lejaden** [MineKits/MineKits#179]
Wie wärs mit einem Parkour / Jump'n'run Event?
Ganz einfach, man baut verschiedene Maps mit einem Ziel, dabei muss man an verschiedenen Hindernissen, Kleine Jump'n'runs, kurze Lavachallange, mlg, (vllcht könnte man hier den Bot einsetzten als Hinderniss). Und der erste, der ans Ziel kommt, gewinnt. Ich finde die Idee nice und ist auch gut umsetzbar.
Außerdem gibts sowas ähnliches noch auf keinem Server.
Ich hoffe die Idee wird umgesetzt.

Tadaaaa und schon wieder Bonuspunkte für Jaden :)

**Comment by lukas81298** [comment]
Das ist bereits geplant  :)

**Comment by EinfachNiggo** [comment]
Klingt super :) 
Toll gemacht Jaden x:

**Comment by lukas81298** [comment]
Was haltet ihr davon, wenn man über ein Schild jederzeit joinen kann und es ein ranking gibt?

**Comment by EinfachNiggo** [comment]
Gute Idee! ;)

**Comment by HDuck** [comment]
Find ich cool

aber wenn man das mit dem Schild macht, könnte es sein, dass es nach der Zeit kaum mehr gespielt wird (wie falldown)
Aber als LMS wäre das schon supa :D
