### ISSUE TITLE
Level-System 'aufpeppen'.

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#180]
Wie wäre's wenn wir mal das Levelsystem bisschen aufpeppen und mehr in den Vordergrund stellen? Dann sollten wir mal die Level von allen Spielern reseten und dann sagen wir 5 Aufgaben machen, die man erledigen muss (die man auch irgendwo sieht) und wenn man die erfüllt steigt man auf. Bekommt 'ne Belohnung zB coins und sowas..
Die Daily Quests kann man zusätzlich so weitermachen.
Und dann könnte man auch machen, dass bisschen OPere Kits erst mit zB lvl 5 freischaltbar sind, oder Boots/Upgrades erst nach einem bestimmten lvl.
Somit gibt's noch mehr 'Sinn' MK zu spielen ;) Man kann dann auch im Menu sehen, was man tun muss, um aufzusteigen und was man dann bekommt. 
Wenn es eine gute Idee ist, dann überleg ich mir mal die Belohnungen und was man dann freischaltet :)
~ Niggo c;

**Comment by CraftingExpertDE** [comment]
Infect 3.0

**Comment by EinfachNiggo** [comment]
Infect hat das Level System nach Kills gemacht und man konnte nur Kits freischalten..

**Comment by EinfachNiggo** [comment]
Ich würde das voll feiern, und man hätte außerdem noch nen "Grund" noch mehr MK zu spielen.
Außerdem ist das nicht von Infect, sondern Subway Surf geklaut ;) :DDD
