### ISSUE TITLE
Mixed Kit verlieren!

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#181]
Man kann sein MixedKit verlieren.

Es bugt irgentwie weg, ich habe keine ahnung wie.

Beispielsweise Mir, BadRefill (länger her), und _WarriorMC ist das passiert,
aber ich kann mit vorstellen das es öffter passiert ist.

Kann man irgentwie nachschauen ob er das Mixed Kit mal hatte? 

Bsp. command:

/CheckMixedKit <player>

-> dann wird gezeigt wie lange er das Kit noch hätte und ob er MixedKit 2 oder 3 gekauft hat

und dann kann man es ihm Manuel mit dem Command geben: 

/GiveMixedKit <player> <2-3> <länge>

oder du findest den Bug raus, je nachdem :)

**Comment by lukas81298** [comment]
Das Problem ist, daas es eigentlich noch da ist aber iwie nicht geladen wird.

**Comment by lukas81298** [comment]
Sollte gefixed sein
