### ISSUE TITLE
Kit Sorter Recraft automatisch?

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#182]
Hay Lukas,

könntest du machen, dass Kit Sorter noch automatisch Recraftet? (falls die person Pilze hat)

Wenn man das Sort Item benutzt hat man sowieso eine 5sec-Stillstand-Frist, daher ist es nicht wirklich OP und dank dem 1min-Cooldown ist es eigentlich nicht wirklick zu OP.

Ich fänds schon nice wenn du es machen könntest

:)

**Comment by EinfachNiggo** [comment]
Sehr gute Idee! :3

**Comment by lukas81298** [comment]
Mit sorter recrafted man jetzt automatisch
