### ISSUE TITLE
Endlich mal 1v1 Arenen.. :/

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#183]
Wurde zwar schon öfter angesprochen, aber nie umgesetzt.
- Könnten biitte mal die Builder mal paar größere 1v1 Maps bauen. Am besten ganz schlicht gehalten, dass man schön Platz ohne großes Schinck Schnack hat ;)
Man kann das ja auch wie die kleinen machen, dass man alle Biomarten baut; bloß größer :P

**Comment by HDuck** [comment]
Redstone hatte schon angefangen mit einer RIEßIGEN Arena: http://prntscr.com/6qimf5

Aber ich glaub bis die fertig ist dauerts noch ein Bisschien.

Am besten einfach sowelche Maps wie wir sie jetzt haben nur ~6x größer 
also mit Biomen wie du meinst^^

Beispielsweise Funetix ist beschäfftigt mit der Falldown map zu bauen :s 

1v1 maps könnten wir aber echt mal gebrauchen :O

**Comment by LabyStudio** [comment]
Dauert noch
