### ISSUE TITLE
Kit Mixing: Creeper + Kit = Nein

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#185]
Beim Kitmixing soll man Kit Creeper nicht MIxen können:

Creeper + Kangaroo

Creeper + Grappler

CReeper + Ninja

Sogut wie alle Kits womit man sich richtig transportiert.

Generell ist Creeper schon ziemlich OP; kannst du nicht machen, dass man IMMER mit 3 Herzen überlebt oder so?

Ende

**Comment by lukas81298** [comment]
Ich mach es so dass man sich entlädt wenn man tpt wird.

**Comment by EinfachNiggo** [comment]
Creeper und Turtle auch!
