### ISSUE TITLE
TexturePack on Join

### ISSUE THREAD

**Issue by HardcorePvPerDE** [MineKits/MineKits#188]
Habe ich schonmal in den ReportChat gepostet, hier trd. nochmal:

An alle Coder / TexturePackmacher:
Ich hab eine Idee! (idea)
Ok mal ernst:
Es wäre cool wenn jemand von den Tp Machern ein "MineKits" Pack machen könnte. Falls wer Headshot auf McPvP kennt, wird man gefragt wenn man joined, ob das RP durch das alternative ersetzt wird. D.h. Dass der Server ein Tp als Vorlage gespeichert hat, man muss nur auf "Use Tp" gehen und das ist sofort drinnen. Wenn man leaved, alles wieder wie vorher. Jetzt ist die Frage, ob wir sowas auch auf MineKits anbieten. Dass wenn man joined einem angeboten wird ob man das MineKits Pack benutzen möchte. (Man kann in den Settings ausstellen dass das Beim joinen gefragt wird). Was haltet ihr davon?

**Comment by lukas81298** [comment]
Meines Wissens nach hat Schweini damit angefangen. Technisch gesehen ist es kein Probkem

**Comment by lukas81298** [comment]
Wenn es ein pack gibt, wird es hinzugefügt
