### ISSUE TITLE
TempBan - Bug

### ISSUE THREAD

**Issue by HardcorePvPerDE** [MineKits/MineKits#190]
Wenn ein Spieler tempbanned wird, und man /baninfo <name> macht, wird angegeben, dass er ohne Reason gebannt wurde. (Zeit auch nicht)

**Comment by lukas81298** [comment]
sollte gefixed sein

**Comment by SchweiniPlaysMC** [comment]
immer noch nicht gefixt

**Comment by lukas81298** [comment]
sollte nun wirklich gefixed sein
