### ISSUE TITLE
LMS Bug @LabyStudio

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#192]
Riesen Bug!

Ich hatte vorhin ein LMS gehostet:

Als es gestartet ist, war einer von ihnen Kit Creeper und hatte sich aufgeladen weil er zuvor bei Warp EarlyHG war.

Danach hat er bei LMS los gelassen und hat alle in die Luft gesprengt, trotz NoKit-<> Region.

Wie man weitere Bugs fixen kann:

**Wenn ein LMS anfängt hat jeder 7 Sekunden Unsterblichkeit**

**Wenn ein LMS anfängt öffnet sich automatisch das Inventar oder eine andere GUI, hauptsache man Sneakt nicht**

p.s. Das war ein Custom LMS sprich einfach nur Kämpfen

@LabyStudio

**Comment by lukas81298** [comment]
gefixed => charge wird resettet wenn man sich tpt
