### ISSUE TITLE
Enderpearl buggen.

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#194]
Wenn man 'ne Enderpearl wirft, dann Quickplay anklickt und wartet bis man ein Kit nimmt, bekomm man die Enderpearl zurück und man hat dann halt eine Enderperle.. :D

**Comment by HDuck** [comment]
Generell gibts viel zu viele Bugs mit Enderpearls .. bsp. vom LMS weg Buggen

Sollte man die lieber removen?

**Comment by HDuck** [comment]
Sollten wir lieber die Enderpearls removen? Es gibt auch andere Bugs mit Enderpearls beispielsweise sich vom LMS weg buggen

**Comment by LabyStudio** [comment]
gefixt
