### ISSUE TITLE
Portal Gladiator bug

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#199]
Wegen den neuen Gladiator Kasten kann man sich mit Portal in die Gladiator Arena buggen.

How 2 Fix

Statt die ID von Glass (ID: 20) zu nehmen, nehmt Farbiges Glass (ID: 95:0-15)

@LabyStudio
@lukas81298

**Comment by lukas81298** [comment]
1. Duplikat
2. Gefixed
