### ISSUE TITLE
Man kann /pay Spamen! [/pay <player> 0]

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#201]
Manche Spamen mit dem Command /pay.

Beispielsweise Überweisen sie immer 0 Credits
=> Unendlich lange Spamen

Das ist schon etwas nerfig, wie wäre es damit:

Man hat immer ein 10 Sekunden Cooldown wenn man jemanden Geld Payt (so wie bei /suicide)

**Comment by lukas81298** [comment]
Cooldown + mind 20 coins
