### ISSUE TITLE
Ninja - Gladiator

### ISSUE THREAD

**Issue by HardcorePvPerDE** [MineKits/MineKits#202]
Ninja funktioniert im Gladiator - Fight nicht (gewollt?).

**Comment by HDuck** [comment]
Ist schon Bekannnt

DIe Region von Warp Feast,Early,NoSoup ist nicht so weit oben wie der Gladiator kasten,
daswegen kann man sich nicht NInja'en, weil die region nicht so weit oben ist


Laby möchte die regionen nicht neu Setzen, weil alles "geordnet" mit dem Glasss in der Luft..

Wenn es einer Fix'ed dann müsste es Laby machen (weil er alle Regionen undso gesetzt hat)

**Comment by lukas81298** [comment]
Ist gewollt
