### ISSUE TITLE
Bei /FAQ gibts noch paar Bugs

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#205]
Hey Lukas hab gesehen dass du /FAQ gefixt hast und es auch Optisch anders gemacht hast! Super

Aber es gibt noch paar Antworten wo im Satz einfach ein "%" ist:
___
Bei **Reports**:

Beide Bücher
___
Beim Buch **Applications**:

Buch: 1 und 3
___
Ansonnsten ist da jetzt alles Richtig

**Comment by lukas81298** [comment]
Sollte jetzt klappen. Wied nach einem reload aktiv
