### ISSUE TITLE
Kit Shadow Cooldown change und spawn Bug!

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#206]
Kit: Shadow

**Bug:**

Wenn man sein Item drückt (dann kommen die ganzen Partikel sounds etc.) und gleich daraufhin Stierbt (egal ob /suicide oder schwert) dann:
Alle am Spawn haben dann diesen Shadow effekt was sehr nervig ist und auch Laut.

**Cooldown:**

Das Kit hat nur 20 Sekunden Cooldown. Allein die Shadow Animation dauert 10 Sekunden Cooldown.

Ich würde vorschlagen, dass man einen 45 Sekunden Cooldown Rein macht,
aber man kann es Upgraden dass es nurnoch 30 Sekunden Cooldown sind

**Comment by lukas81298** [comment]
sollte gefixed sein
