### ISSUE TITLE
./cBan Command? DDOS Drohung

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#208]
Hey Lukas,
wollte dich fragen, ob du sowas wie ein /cBan command machen könntest:

Wenn man einen Spieler so bant, kommt die Nachricht, dass er von der Console gebannt wurde.
Das ist Praktisch wenn leute mit DDOS drohen und was weis ich z.B sagen "Wenn du mich Banst DDOS ich dich" oder so..

Wäre nicht schlecht ¯\_(ツ)_/¯

**Comment by EinfachNiggo** [comment]
Gute Idee! Sehr praktisch :D

**Comment by LabyStudio** [comment]
Kann abused werden aber nice

**Comment by HDuck** [comment]
Dann soll halt durch Abuse-Kontrolle das gemacht werden:

Wenn man dann /cBaninfo oder so macht, sieht man wer ihn gebannt hat oder sou :)

**Comment by lukas81298** [comment]
./ban player -a test
