### ISSUE TITLE
KOTH! Event Vorschlag:

### ISSUE THREAD

**Issue by HardcorePvPerDE** [MineKits/MineKits#209]
Hey Leute,

Ich hab einen Vorschlag für ein Event-Gamemode:
Es geht darum, wie der Name schon sagt, "King of the Hill", einen Hügel zu erklimmen.
Man hat das Kit: PvP-Feast oder KnockbackStick 1 mit Reg 1000 [Mehr Infos unten]
Der Hügel muss gebaut werden, die Spitze besteht aus 2x2 Blöcken. Wenn man oben angekommen ist, ohne dass man heruntergeschlagen wird, muss man für x = time [Vorschlag 7 Sec.] oben stehen bleiben -> Spiel gewonnen!

Kurze Infos:
- kein Fallschaden 
- Durchgehend Regeneration x = Stärke der Reg. [Vorschlag 1000] damit man keine Herzen verliert, oder KitPvP ohne Regeneration 

Hoffe euch gefällt es, gab es damals auf kkits.tk aber ich glaube jetzt nicht mehr ^^
Sagt mal eure Meinung :)

**Comment by HDuck** [comment]
Ich finds geil ;3..,
aber das selbe hat KingsPvP auch ;c  
Wäre dann eine "Kopie" :/

Aber man kanns ja irgentwie anders machen dass es nicht so wie bei KingsPvP ist ;3 Im prinzip ist das LMS aber schon tull :D

**Comment by HardcorePvPerDE** [comment]
Ja, da muss noch was geändert werden, ist bei diesem Spielmodus aber relativ schwierig :D

**Comment by EinfachNiggo** [comment]
Ich bin ja immer noch für mein kompliziertes SchachLMS :-)
