### ISSUE TITLE
Kit Meteor 

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#210]
**Kit Meteor**
___

**Item:** Magma Cream
___

**Ability:**

- Wenn man sein Item Rechtsklickt, fallen von **10** Blöcken über dem Spieler Sandblöcke welche ausschauen wie *Obsidian*.

- Die Blöcke fallen von einem Radius von 5 Blöcken von dem Spieler runter

- Die Blöcke fallen nach einander Runter (delay: paar Ticks) & Insgesammt 30 fallen

- Ein "Meteor" macht 2 Herzen Schaden 

- Der Typ mit dem Meteor Kit bekommt kein Schaden von dem Meteor und hat dabei einen Orangenen  Lederhelm mit Haltbarkeit 1 (bis der Meteor-Regen vorbei ist, kann er nicht kaputt gehen)

- Wenn über dem Meteor-Typ Blöcke sind (bsp. er ist in einer Höhle) dann steht im Chat "Über dir sind Blöcke hier kannst du das nicht machen" oder halt so ein Satz ^^
___

**Andere Informationen:**

- Cooldown: 50 Sekunden

- Man kann den Cooldown oder den Schaden *Upgraden*

___

Hoffe dir gefällt das Kit und dass es Umsetzbar ist =D

**Comment by EinfachNiggo** [comment]
Klingt riiichtig cool!

**Comment by EinfachNiggo** [comment]
Ich fände es besser, wenn man 5 Herzen Schaden bekommt.

**Comment by HDuck** [comment]
Naja aber wenn 2 Metore auf dich fallen bist du ja instand tot, oder? :0
aber so 3 - 3,5  Herzen gehen klar denk ich

**Comment by EinfachNiggo** [comment]
Achsoo jetzt hab ich's verstanden :D 
Passt!
