### ISSUE TITLE
Wichtiger Endermage Fallschaden-Bug! 

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#211]
Wenn man mit endermage jemanden Maged, bekommt man immernoch Fallschaden innerhalb der Unsterblichkeits-Zeit.

EDIT: Wenn man jemanden Teleportiert, kommt nur die nachricht "Teleportiert", nichts von Unsterblichkeit oder sonnst was.
Gewollt? 

Habe das Kit getoggled, da es sehr viele Fallschaden Traps gemacht werden!

**Comment by lukas81298** [comment]
gefixed
