### ISSUE TITLE
Kit Gravedigger Bugs + Bei Quickplay geht NoSoup nicht

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#212]
Paar Gravedigger Bugs:

- Wenn man jemanden als Gravedigger Tötet - kann man die Kiste auch ohne den Holzstick öffnen.

- Man kann aus der Kiste das Kit-Item bekommen (Ich habe ein MLG-Typ gekillt und habe ein Wassereimer bekommen)

___

Und mit Quickplay kann man immernoch nicht in Nosoup.
Da steht einfach "Arena not found." => bitte die "Arena" festlegen :)

**Comment by lukas81298** [comment]
Es ist sind und zweck das auch ohne stick öffnen kann. Er dient zum suto equipment

**Comment by HDuck** [comment]
Aber auch die anderen Spieler können diese Kiste öffnen

**Comment by lukas81298** [comment]
Ja

**Comment by HDuck** [comment]
Ohh,
was bringt denn dann dieser "Loot" stick?

Naja das Problem scheint gelöst zu sein, falls Quickplay für NoSoup gesetzt ist :)

**Comment by lukas81298** [comment]
Wenn man die Kiste mit dem loot stick klickt wird die beste rüssi angezogen and die pilze nachgefüllt

**Comment by HDuck** [comment]
Ohh tut mir leid das wusste ich nicht
