### ISSUE TITLE
Iron Rüsstung Buggen!

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#213]
Hey Lukas,

badeshka1 hat eine Möglichkeit gezeigt, wie man sich Eisenrüsstung Bugt.
Ich habe das als Video aufgenommen, da es schwer ist zu beschreiben:

**Link:** http://youtu.be/Wt9XB3R8n9g
___

**Wie kann man es Fixen:**

- Wenn man Items von der NoSoup-Region zur EarlyHG-Region Droppt, werden diese Items Instand removed.

Und dass dan bei Allen Regionen machen:

Spawn-Region=>EarlyHG-Region
Feast-Region=>EarlyHG-Region

___

Ich habe sicherhalts halber ALLE Trapdoors in der Region Spawn entfehrnt!
Leider kann ich nichts gegen die Enderpearls machen, daher war das meine "Not-Entscheindung".

**Comment by lukas81298** [comment]
=> man kann keine ironrüssi in ehg aufheben

**Comment by HDuck** [comment]
ahh, auch eine lösung super

**Comment by HDuck** [comment]
Funktuniert immernoch trotz Update..
oder wurde das nicht mit eingefügt?

Jedenfalls kann man es anziehen
