### ISSUE TITLE
Runner LMS - Sneaken

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#215]
Man kann beim Runner LMS am Block einfach sneaken und man fällt nicht.

Vorallem wenn nurnoch 3 leben ist das sehr OP

Wie man es fixt: Wenn sich eine Person in einem LMS nicht bewegt, fallen im radius von 3 Blöcken alle Blöcke runter oder so wenns geht :D

**Comment by lukas81298** [comment]
Das ist leider ein Minecraft bug.
