### ISSUE TITLE
Kit Follower

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#221]
**Kit Follower**
___

**Item:** Faden (ID: 287)
___

**Beschreibung:**

- Wenn man jemanden mit dem Faden rechtsklickt, 
hat man sich sozusagen an den Spieler "angekettet".
- Es entsteht wie bei einer Angel ein Seil der bei dem Spieler gebunden ist 
- Man kann maximal 5 Blöcke von dem Spieler weg gehen, sonnst wird man immer zu ihm gezogen
- Man ist maximal 10 sekunden an dem Spieler, bis dieses Seil automatisch kaputt geht
- Wenn man den Spieler nochmal Rechtsklickt, dann wird man nicht mehr an ihn gezogen                    (= Loslassen)
- Das Seil kann nicht abreißen wie bei Cowboy (wenn jemand auf ein Sponge geht), sondern man wird immernoch an den Spieler gezogen. Ausnahme: Wenn er sich Teleportiert oder Gladiatort, Prisonert wird.

*Es ist sozusagen wie Cowboy, aber andersrum, und man wirft nicht das seil, sondern rechtsklickt den Spieler.*
___

**PROS:**

- Spieler kann nicht vor dir weglaufen => PvP

**CONS:**

- Man kann genauso nicht vor dem anderen Weglaufen 

___

**Sonnstiges:**

- Cooldown: Nachdem man jemanden an der Leine hatte: 40 Sekunden
- Upgrade: 
   1. Cooldown niedriger
   2. Länger an dem seil sein (statt 10 sekunden mehr, siehe 4 Stichpunkt)

___

Hoffe dir gefällt das Kit :D

**Comment by EinfachNiggo** [comment]
Cooool! :)
