### ISSUE TITLE
Man kann Kit Prisoner bei NoSoup sein!

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#225]
Ist es gewollt?

Man kann wieder Prisoner, Relaxo etc. bei NoSoup nutzen!

**Comment by lukas81298** [comment]
@LabyStudio hats verkackt. Mach bitte mal ne liste dann änder ich es

**Comment by HDuck** [comment]
Creeper, Prisoner, THor, Releaxo, 

ich denke das waren alle, sonnst fallen mir  keine ein, da ich off muss.. 

falls es noch was gibt, werde ich das Kit togglen oder so ;)
