### ISSUE TITLE
minekits.eu/stats/kit-stats aktuallisieren?

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#226]
Hey Lukas,
wollte dich fragen ob es möglich ist, das zu Aktuallisieren:

https://minekits.eu/stats/kit-stats

Da sind noch Kits, die nichtmal mehr Existieren undso..
also die Liste einfach auf 0 setzen und die Stats von neu starten, falls du verstehst was ich mein ^-^

Falls das nicht geht oder schwer ist pi pa po kanns auch so bleiben, wollt es nur damit es etwas aktueller ist

**Comment by lukas81298** [comment]
Das geht nicht so ohne  weiteres Möglichkeit. Ich könnte die alten kits höchstens ausblenden.
