### ISSUE TITLE
Random 1v1

### ISSUE THREAD

**Issue by lejaden** [MineKits/MineKits#227]
Die beliebteste Funktion der User. Wie wärs, sowie früher, mit einem random 1v1. Ich finde es selber hilfreich.

**Comment by HDuck** [comment]
Ich glaube Lukas wollte das Plugin sowieso verändern wie Früher

Items: Diamantschwert, 1v1 Quliqe Redstone

Also so wie früher.. nur etwas besser also mit 2v2 etc 

jedenfalls wollte er ein item dafür machen .. es gibt ja schon den 1v1 Zombie, nur funktuniert er nicht richtig xD

**Comment by LabyStudio** [comment]
Gibt es schon.
