### ISSUE TITLE
Suppen Buggen in noSoup!

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#230]
Wie bugt man die suppe:

Einfach vor der Grenze zwischen Spawn und NoSoup die Suppen droppen,
dann zu noSoup laufen und die Suppen aufheben. Schon hat man die Suppen

Wie kann man es fixen:

a) In der Region NoSoup kann man keine Suppen rechtsklicken 
b) In der Region kann man keine Suppen aufheben

**Comment by HDuck** [comment]
Es gibt generell viele wege an Suppen zu kommen oder sie glitchen einfach

daher einfach machen dass man sie nicht trinken kann

**Comment by lukas81298** [comment]
Man kann sie aber nicht essen o.o

**Comment by HDuck** [comment]
doch kann man .. vlt können das nur mods, jedenfall gehts bei mir :o

**Comment by lukas81298** [comment]
gefixed
