### ISSUE TITLE
/admin Uhr Bugg.

### ISSUE THREAD

**Issue by SchweiniPlaysMC** [MineKits/MineKits#232]
Wenn man im Admin Mode auf die Uhr rechtsklickt hat man noch die Check-FF Redstonefackel im Inventory. Wenn man dann die Redstonfackel rechtsklickt hat man seine normalen Kit Selector/Quickplay Sachen etc.

**Comment by LabyStudio** [comment]
Wollte lukas nicht fixen idk frag ihn nochmal
