### ISSUE TITLE
1v1 bug

### ISSUE THREAD

**Issue by lejaden** [MineKits/MineKits#235]
Man kann als Donator zur Map Default fliegen bzw laufen. Dann, wenn zwei fighten, gehst du auf die 1v1 Arena und wählst Thor, Tornado und nervst somit die anderen, die fighten wollen!

**Comment by HDuck** [comment]
**Fly Abuse ** http://prntscr.com/6yqh0h
=> Fly rechte werden entzogen

benutz bei der Person einfach /warn - bis der fehler behoben ist

___

Wie man es manuell fixen kann:

So wie bei dem neuen Border Plugin von @LabyStudio einfach ein Border um die 1v1 Map machen, so kann keiner in die nähe der Spieler

**Comment by HDuck** [comment]
Laby: "das ist Fly abuse, dagegen kann man nichts machen,
wenn man zufuß geht, geht es  nicht, da da eine region ist, man kann nur von oben rein fliegen..

Kann man nicht wirklich fixen "

**Comment by lukas81298** [comment]
Dann müssen änderungen an der map vorgenommen werden
