### ISSUE TITLE
feast: Kakteen mit Cobweb zerstören

### ISSUE THREAD

**Issue by lejaden** [MineKits/MineKits#236]
Bei /Warp feast sind Kakteen geplacet. Wenn man daneben, ein Cobweb placet, werden die Kakteen zersört. Ganze Wüste zerstören!

**Comment by HDuck** [comment]
@lukas81298 
vlt. könnte man es so machen, dass man **Cobwebs nicht neben Kakteen setzen kann**,
oder wenn es irgentwie geht, dass Kakteen nicht kaputt gehen

**Comment by lukas81298** [comment]
müsste nun gefixed sein
