### ISSUE TITLE
Prisoner Gladiator bug! (immernoch)

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#237]
Der Bug wurde eigentlich mal gefixt aber er ist anscheinend immernoch da:

**Wenn man im Gladiator jemanden Prisonert, stierbt er an fallschaden instant.**

Fix Möglichkeit:

- Im Gladiator kasten kann man keinen Prisonern

___

(außerdem finden viele das Kit zu OP, okey, geschmackssache, ich wollte es nur gesagt haben)

MFG :D

**Comment by lukas81298** [comment]
fixed
