### ISSUE TITLE
Man kann Iron schwerter zu EarlyHG buggen

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#238]
Hey Lukas,

du hast ja bereits gefixt, dass man keine Eisenrüssi aufheben kann, aber ich glaube das Eisenschwert hast du vergessen:

Wenn man seine Iron Items zu EarlyHG droppt, kann man nichts aufheben außer das Eisenschwert, das kann man aufheben.

**eZ 2 fix:**

- So wie bei der Rüssi: Man kann kein Eisenschwert aufheben

**Comment by lualzockt** [comment]
ok

**Comment by lukas81298** [comment]
falscher acc :D

**Comment by HDuck** [comment]
ok haha :D lual
