### ISSUE TITLE
Copycat bug (kitmixing), Quickplay Bug

### ISSUE THREAD

**Issue by xBlackJack** [MineKits/MineKits#239]
Wenn man Copycat ist und einen tötet der ein gemixtes Kit hatte, Kann man die Items (z.B. Die Kangaroo Rocket) nicht benutzen! 

Wenn man bei Quickplay "last Kit" eingestellt hat  (und man vorher ein Mixed Kitt hatte) und dann zu z.B. ehg geht, bekommt man die Items / Fähigkeiten nicht.

**Comment by lukas81298** [comment]
fixed
