### ISSUE TITLE
MixedKit: Kit Item Slots bestimmen

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#240]
Hey Lukas,

man kann ja bei /settings einstellen das die Kit Items beispielsweise im "9" Slot ist:
Kannst du das machen, dass es auch mit dem MixedKit-Item so ist? 

oder dass man bei /kitmixing irgentwie die Position der Kit Items setzen kann.

___

Ich weiss, das ist nicht wirklich notwendig, aber es wäre halt nicht schlecht, wenn es sowas geben würde, falls du zeit und lust hast kannst du es ja machen :D

**Comment by lukas81298** [comment]
Das ist leider nicht möglich :(
