### ISSUE TITLE
Gladiator Problem(e )

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#248]
Ich kann nicht genau sagen, ob es gewollt ist oder nicht, aber manches ist sehr nerfig bei Gladiator:

___

Wenn man es schafft in den Gladiator kasten zu kommen (bsp. ein Ninja oder Phantom),
dann kann er uns nicht hitten und aber die Person im Gladiator kann ihn Hitten
(wahrscheinlich gewollt)
___

Ich nehme an es ist gewollt, dass die anderen uns nicht hitten können, aber man bekommt trotzdem als Gladiator Kämpfer den Schaden von den Kits (beispielsweise Airstrike Explosion Schaden)

**Comment by lukas81298** [comment]
Man ist selbst schuld wenn man sich reinbugged
