### ISSUE TITLE
Kit Items haben ihre ganz normale Fähigkeit!

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#25]
Damit sind beispielsweise diese Items betroffen:
Schneeball (Kit Snowman)
Pfeile (Kit Archer)
Enderpearl (Kit Jumper)
etc.

Fix:

Das man keine Schneebälle, Pfeile, Kit-Enderpearlen schmeisen kann in der region "Spawn"

**Comment by LabyStudio** [comment]
Er meint damit das man die Items normal am Spawn verwerfen kann
