### ISSUE TITLE
Mixed Kit: Nicht Mixbar- Kits

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#253]
Es gibt wieder OP möglichkeiten für MixedKits:

- Tank + Fisherman

- Turtle+FIsherman [#EDIT schon gefixt]

FIshereman Portet jemand zur demoman Platte und er bekommt kein schaden

**Comment by lukas81298** [comment]
Was ist an Tank + Fisherman schlimm?

**Comment by HDuck** [comment]
Tank bekommt von der Demoman Platte kein schasden bzw. kann sich einfach drauf stellen.

Wenn er also Tank und Fisherman ist, teleportiert er einfach einen und er explodiert
