### ISSUE TITLE
Ideen, wie findest du die?

### ISSUE THREAD

**Issue by xBlackJack** [MineKits/MineKits#254]
http://puu.sh/hwphj/eb6187ad66.png

**Comment by HDuck** [comment]
Zusammenfassung:

- Gambler mehr cooldown
- Ninja Cooldown weg machen [KEINE Gute Idee!]
- bei /battle ein warp setzen *(*/setwarp 1v1**)
- Mehr Credits für ein Kill (deine entscheidung.) 
- Bei warp feast hohes grass entfernen
