### ISSUE TITLE
1v1 Battle Bugs

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#26]
Bugs bei dem 1v1 System:

- Wenn man jemanden Invited und er dich zum Annehmen Schlägt bekommt man 4 Herzen schaden vom Diamantschwert

- Nach einem 1v1 kampf, wenn jemand gestorben ist, bekommt man die Items vom Spawn und nicht die Battle Items.
(Man hat Kit Selector etc. und kein Invite 1v1 Schwert etc.)

**Comment by lukas81298** [comment]
Fixed
