### ISSUE TITLE
Jemand ist im Spectate Mode und da kommt die nachricht.. 

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#260]
Wenn man diese Person hittet (er is im /watch mode), kommt diese nachricht: http://prntscr.com/70129a

Laby meint, dass das nicht mit seinem /watch plugin zu tun hat,
ist diese nachricht gewollt? 

~Report by @LabyStudio

**Comment by LabyStudio** [comment]
Diese Nachricht ist nicht in meinem Plugin also sollte von lukas kommen

**Comment by lukas81298** [comment]
macht ja auch sinn
