### ISSUE TITLE
LMS Bug

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#268]
Man hat nachdem ein LMS gestartet wird immer noch sein vorher ausgewähltes Kit, d.h. in Bracktes kann man dann mit Viper/Pyro spielen..
Am besten einfach machen, dass das Kit vor dem LMS resettet wird.

Außerdem kann man bei Runner in die Mitte von 4 Blöcken stehen und es fallen keine runter, es kommt nur teilweise die Animation, aber es passiert nix.. kp ob man das fixen kann :P

**Comment by HDuck** [comment]
1. Das mit den Kits: Du musst einfach den Bereich Makieren wo das LMS ist, 
und dann **/rg define nokit-<zahl>**

2. Das mit dem Runner LMS ist leider nicht fixbar laut Lukas,
aber du kannst wenn es jemand macht ihn einfach Spleefen damit er wieder läuft 
( https://github.com/MineKits/MineKits/issues/215 )
