### ISSUE TITLE
Liste der Toggled Kits + Grund

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#269]
Hier kurz die liste der getoggled Kits:

**Levitator**

Grund: Ich glaube weil das Lags verursacht hat

___

**sorter**
(#EDIT)
Grund: Hat den Server zum Crashen gebracht 

___

**Prisoner**

Grund: Man kann im Gladiator jemand Prisonern, sodass der Gladiator an fallschaden stierbt 

___

**Hulk**

Grund: Hulk hat kein Cooldown => Man kann es Spamen

___

**Tank**

Grund: Der Tank stierbt selbst wenn er einen Tötet. => Er bekommt TNT schaden

**Comment by LabyStudio** [comment]
Sorter hat den Server zum crashen gebracht
