### ISSUE TITLE
Items in Kisten bei EarlyHG gehen nicht [Bug]

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#27]
Die Items welche in den Kisten bei EarlyHG sind, funktunieren nicht,
bzw. die Items "Launcher" (Slimeball) und "Cobweb" kann man nicht Nutzen

**Comment by LabyStudio** [comment]
Ich glaube weil die region noch nicht umbenannt wurden.
@lukas81298 Wenn das so ist nenn die Region bitte zu EarlyHG und feast

**Comment by lukas81298** [comment]
Sollte gefixed sein.
