### ISSUE TITLE
Schneebälle lassen einen Teleportieren

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#274]
Statt Enderpearl Plugin gibt es jetzt ein Plugin, womit man mit Schneebällen werfen teleportiert wird,
doch da gibts jetzt paar bugs:

- Man hat am Spawn kein Schneeball (also für alle spieler) 

- Man kann Kit Switcher (oder ein anderes Kit was ein Schneeball hat) nehmen und sich so am Spawn teleportieren - das  ist nicht das Schlimme doch:
Wenn man bei EarlyHG ist kann man sich mit dem Schneeball einfach zum Spawn teleportieren

**Comment by EinfachNiggo** [comment]
Wie bekommt man die Schneebälle? :D

**Comment by HDuck** [comment]
Mit Kit Switcher oder ein anderes was Schneebälle hat ^.^
