### ISSUE TITLE
Kit Rocket 

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#276]
**Kit Rocket** *(kann auch geändert werden)*
___

**Ability**

- Man hat eine Rakete als Item
- Wenn man damit einen Rechtsklickt, wird **der gegner** in die Luft geschossen und er bekommt Fallschaden.
- Er fliegt genau 14 Blöcke hoch (=> 5,5 Herzen Fallschaden) 
- Während er in die Luft fliegt, bekommt er durchgehend ein halbes Herz Schaden (in der Geschwindigkeit, wie wenn man auf einem Kaktus ist oder im Void)
- Während er hochfliegt soll es noch mit Partikeln geschmückt werden (Benutze deine Kreativität :3) 

___

**Andere Infos**

- Cooldown: 50 sec.
- Upgrade: 

1. Er fliegt 16 Blöcke hoch (=> 6,5Herzen FallDMG)
2. Cooldown auf 40-45

*PRO:*
- Dem gegner Schaden geben
- Dabei Schnell recraften 
- Er kann nicht recraften weil er beschäftigt ist suppen nachzufüllen
- Man kann bsp. aus Gladiator fliehen

*CON*
- Falls er Stomper ist gibt er dir Schaden
- Falls er ein anti-fallschaden Kit ist, bekommt er nur leichten damage  

___

Hoffe dir/euch gefällt das Kit :3

**Comment by lukas81298** [comment]
Eher nicht, find ich echt nicht so toll :(
