### ISSUE TITLE
Kit Earthquake

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#279]
**Kit Earthquake** *(by ERROR201notfound)* +meine Ideen
___
Item: Feder
___

**Ability**

- Rechtsklicke deine Feder und du wirst automatisch hoch geflogen aber man kann sich dabei noch nach vorne,hinten,rechts,links bewegen (maximaler Radius: 7) (wenns geht sollte man etwas schneller in die luft fliegen als normales fly) 
- Während man hoch fliegt bekommt man immer etwas schaden damit es keine konkurenz mit Phantom macht
- Wenn man jetzt ca 20 Blöcke in der luft ist, fällt man runter:
- Wenn man landet, fliegen alle Spieler im Radius von ~3 Blöcken in die Luft und erleiden fallschaden
- Die gegner fliegen 15 Blöcke in die luft => 6 Herzen schaden 
- Am Boden erscheinen auch diese Animationen wie bei dem TNT, sodass die Blöcke nur ganz leicht hoch fliegen

___

**Andere Infos**

Cooldown: 50 Sec.
Upgrade:
1. Cooldown
2. Radius von 7 auf 10 ändern (bei der bewegung)
3. Radius von 3 auf 4 ändern (beim auffallen)

___

Hoff das Kit gefällt dir :D #standartsatz

**Comment by lukas81298** [comment]
Ist doch so was wie Bomber?

**Comment by HDuck** [comment]
Ouh Stimmt, ist mir garnicht in den Sinn gekommen ._.

- Closed -
