### ISSUE TITLE
Kit Sniper 

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#281]
**Kit Sniper** *(by _F_L_Y_B_Y_) +Meine änderungen
___

Item: Magmacream 

___

**Ability**

- Rechtsklicke deine Magma Cream und dann bekommt man Slowness 259 (sodass es aussieht, als würde man Zielen)
- Wenn man jetzt das Item klickt, schießt man Magma creams (sie fliegen so wie Schneebälle)
- Man kann nur 3 Stück schießen, dann Cooldown
- Wenn man ein Spieler im Radius von 6 Blöcken trifft, macht der Schuss 3 herzen Schaden
- Wenn man ein Spieler weiter weg als im Radius von 6 trifft bekommt er 5 herzen Schaden 

- Wenn man 3mal geschossen hat, geht das Blindness weg und man kann wieder kämpfen man hat aber noch 5 sekunden übelkeit)
- (während man im Sniper modus ist, kann man nicht Fighten sondern nur Schießen)

___

**andere Infos**

- Cooldown: 45 sekunden
- Upgrade: 

1. Cooldown weniger
2. schuss macht 0,5 Herzen mehr schaden
3. keine Übelkeit nach dem Snipen

**Comment by EinfachNiggo** [comment]
Dojo..
