### ISSUE TITLE
Kit Rogue Buff 

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#282]
Könnte man vlt. Rogue einen BUff geben?

Das Kit nimmt ~10 Sekunden die Kit Ability vom gener weg, dann hat man ein 1 minute Cooldown

Könnte man dass nicht auf 40 oder 45 einstellen?
oder dass man das Upgraden kann - wäre toll :3

**Comment by lukas81298** [comment]
ich füg gleich ein paar upgrades hinzu
