### ISSUE TITLE
Tolle, komplizierte MK-Idee! :D

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#283]
→ Neue MK-Idee!
[Aufbau an GTA V orientiert.]
MAP:
Es gibt eine einzige Map, die dafür ziemlich groß ist. Der "Spawn" ist in einer Stadt. Diese erstreckt sich dann ca. über die Hälfte der Map. Es gibt in der Stadt verschiedene Läden, Rathäuser, Freizeitaktivitäten etc. Weiter draußen kommt dann noch Natur/Gebirge/Wald und so.

ALLGEMEIN: 
Wenn man den Server joint spawnt man am letzten Punkt, an dem man disconnected ist. Dann kann man in der kompletten Map frei rumlaufen und PvP'n. Es gibt nur ein paar Zonen wo kein PvP ist [Haus,Shops etc.]. Dabei gibt es ein "Reichenviertel" und ein "Armenviertel". Das Reiche ist sozusagen, wo man mit Eisenrüstung und Diaschwert kämpfen kann. Das Arme ist eHG-Stuff, d.h. man kämpft mit Steinschwert. Man startet außerdem mit Stack Stack.

1V1 & "EVENTS":
Man kann mit /create irgendwo auf der Map ein "Event" eröffnen. Durch den Command öffnet sich ein GUI, in dem man zw. verschiedenen Spielmodi entscheiden kann. Z.B. 1v1/2v2/J&R/etc. Dort kann man alles dafür einstellen [Rüssi, Zeit, Spieleranzahl..], wie auch andere Spieler einladen. Hat mal alles ausgewählt, drückt man auf "Ok" und kann erstmal weiter PvPen. Beim Schließen des GUI's kommt aber noch ein Kreis aus Partikeln, wo man das "Event" erstellt hat. Diese sind so 1/2 Block hoch und wenn da dann andere Spieler reinlaufen und 3Sek. drinnen stehen bleiben, joinen sie dem "Event". Ist die ausgewählte Spielerzahl erreicht, startet es. Die Gewinner bekommen natürlich XP/Credits.

SHOPS ETC.
In der Stadt gibt es verschiedene Läden. Es gubt z.B. Klamottenladen (Boots), Kitshop (kp, wie man den nennt) zum Kits kaufen. Dann Infohäuser mit Regeln/Staff und Freizeitaktivitäten! Da gibt's dann zB Bogenschießen, MLG, Lava..
Da ist dann kein PvP an. Man kann die Aktivitäten alleine, aber auch mit Freunden machen. 

Außerdem kann man sich Häuser kaufen, in denen man sicher ist, "Autos" (> Pferde, Minecarts=Fahrrad, die man auch in Geschäften kaufen kann) abstellen bzw. abholen kann, und mit diesen schneller vorrankommt. Außerdem kann man Partys createn und was weiß ich noch. 

Das war's. Ist wohl mega kompliziert, aber hatte halt die Idee, lel.
Tschüß! :)

**Comment by HDuck** [comment]
Mega Idee!
Gefällt mir sehr wäre echt cool wenn das Umgesetzt wird,
dann ist es kein normales KitPvP mehr sondern auch mit "Struktur" und allem
Ich kann mir das richtig gut vorstellen!
Klar kann das sehr schwer sein zu coden aber die Idee ist doch richtig nice ;3

**Comment by CraftingExpertDE** [comment]
@HDuck die meisten Spieler haben dann keine orientierung und laufen planlos rum und rage quitten wenn sie sterben, entweder wir verlieren spieler oder gewinnen sie, ich tippe auf verlieren.

**Comment by lukas81298** [comment]
Das Prinzip hört sich gut an, ist aber leider viel zu kompliziert wie Crafting bereits sagte. Vielleicht könnten wir ja trotzdem einzelne Sachen umzusetzen.

**Comment by EinfachNiggo** [comment]
Yo :)

**Comment by HDuck** [comment]
Im Prinzip ist das ja nicht "soo viel": 

Der Spawn ist eigentlich eine Riesen Stadt aber da gibts halt noch die Features:

- Wenn man das "Rathaus" betritt, sind da halt regeln
- Wenn man den "Klammoten Laden" Betritt, kann man halt Boots klicken und dann kauft man sich sie
- Wenn man zu "Freizeit Aktivitäten" geht, bekommt man halt ein MLG Eimer bzw man ist im Lavasee zum Soupen

Nur dass es auch Optisch gut ausschaut - also nicht dass sich da einfach eine GUI für /Boots öffnet

Rein Theoretisch haben wir das ja schon: Wenn man bei MineKits die region "Lava" Betritt, bekommt man Suppen und da ist ein Lava See 
=> Läden kann man sozusagen mit Regionen machen 


___

**Die neuen Features sind eigentlich:**

- Autos fahren in der großen Stadt /buycar (um sich schneller fort zu bewegen) (Wir haben eig. auch /bike) 
- /create command
- Haus Kaufen 

/create ist eigentlich auch etwas mit /battle zu vergleichen von der GUI her:
- Spielmodus wählen: 1v1, 2v2, Team Deathmatch, etc.
- Spieler einladen
- Rüssi Setzen

etc.
und dann erscheinen wie du schon gesagt hast Partikel wo dann auch andere Spieler deinem Spiel joinen können.

Sozusagen ist man ein Host (Server für andere hosten)

___


**So kann man sich das Bildlich vorstellen glaube ich:
http://prntscr.com/75sox7**
(ist nur **Improvisorisch** gebaut, die Stadt sollte natürlich sehr groß sein zum rumlaufen und natürlich auch schön nicht wie meins. xD ) 


Ich finde, so wäre alles miteinander verknüpft - finde ich persönlich richtig cool

Natürlich ist es doch schon schwer das zu coden (besonders /create) Props an dich Lukas wenn du es schaffst da was umzusetzen! <2 
Und wir bräuchten natürlich noch die Builder die eine Stadt bauen (selbstverständlich) 

Wäre aber echt tull wenn es gemacht wird :)

**Comment by EinfachNiggo** [comment]
Super erklärt Anil! :D <2
Ich denke es würde bestimmt gut ankommen.. da es sozusagen einfach bisschen "moderner" und hochwertiger ist, wie normales KitPvP c:

**Comment by EinfachNiggo** [comment]
@CraftingExpertDE das macht keinen Sinn.. ^^ Wir könnten ja auch ein "Review" oder so machen und so schwer ist das doch nicht :P

**Comment by HDuck** [comment]
Ich würd mich auch bereit erklären (vor dem release) ein Review / Tutorial zu machen ^-^

**Comment by EinfachNiggo** [comment]
Me2! <2 :D (@Ente, lass es uns durchsetzen!! Aber pssst!)

**Comment by HDuck** [comment]
Man kann ja vlt. auch noch den warp EarlyHG bzw Feast lassen oder?

Oder ist dieses Thema jetzt abgehakt? ^^

**Comment by lukas81298** [comment]
eher nicht, mal schauen
