### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#284]
Das ganze wurde schon mal in Skype kurz angesprochen, aber hier nochmal. 

Wie wäre es, wenn wir ein Scoreboard machen (vll. mit /SB oder /Scoreboard aufrufbar). Und jeden Monat (oder jeden zweiten/dritten) wird dieses resettet und die ersten 3 (mit den meisten Kills) bekommen ein "Geschenk".
Beispiel:
1. 1609 Kills: 1Woche Gold
2. 1567 Kills: 1Woche Emerald
3. 1345 Kills: 1Wochw Iron

Da gibt's dann nochmal so einen extra Reiz auf MK zu spielen, und die Ränge zu verschenken tut uns ja nicht weh :D

**Comment by lukas81298** [comment]
das hat doch schon wer vorgeschlagen und das werden wir irgendwann auch machen
