### ISSUE TITLE
/Wichtig - Maintenance Kits mit einem MixedKit spielen

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#286]
Crafting hatte glaube sowas schonmal reportet, doch es geht immernoch:

Man kann Immernoch Maintenance Kits benutzen
bsp. ist Kit Creeper in Maintenance aber mit einem MixedKit kann man es immernoch Spielen.

Bitte schnell beheben, da man nichts dagegen machen kann :s

**Comment by lukas81298** [comment]
sollte gefixed sein
