### ISSUE TITLE
Spieler können keine Boots kaufen

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#287]
Man kann sich keine Boots kaufen (Ich als Mod+ nicht und auch Default user)

Wenn man /boots eingibt, und dann zum Bootshop geht - und auf ein Schuh drückt, passiert nichts - weder verliert man Geld noch bekommt man den Schuh

Ich glaube Laby meinte das liegt an dem PermissionPlugin von djd

**Comment by lukas81298** [comment]
sollte nun gefixed sein
