### ISSUE TITLE
Viele verschiedene Ideen und Features für Minekits [5]

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#288]
Hab ein paar Ideen gesammelt für MineKits, villeicht gefällt dir das ein oder andere: 

**Gliederung:**
1. Auto-Respawn
2. "Money Time" 
3. 1v1 Zombies am Spawn
4. Challenges
5. /party mit freunden

___

**Auto-Respawn**

Das ist ein kleines Feature:
Man hat am Spawn ein Item(Skelett Kopf), welches "Auto-Respawn" heißt. (Kann auch im Menu sein)
Wenn man  das Aktiviert, respawnt man Automatisch, wenn man Stierbt bei EarlyHG bzw. feast,nosoup 
Aber nicht genau vor dem Warp sondern so wie bei Quickplay irgentwo Random.
Wenn man Respawnt ist, ist man aber 3 Sekunden Unverwundbar, damit man schnell ein Kit wählt.
Man kann das Autorespawn einfach ausschalten, innerhalb der 3 Sekunden Unverwundbarkeit, da man im Inventar wieder ein item hat womit man es deaktiviert.

Rein theoretisch ist das so wie Quickplay, doch ich glaube das "fesselt" einen weiter zu Spielen ohne kurze Pause geht es sofort los.
Man kann auch den Skelett Kopf Shift+Rechtsklicken, um den Respawn ort und das Kit (wie bei Quickplay) zu ändern.

Mein Persönliches Rating: 2/5 - Wäre aber ein gutes Feature find ich

___

**"Money Time":**

Ich glaube sowas hatte mal Niggo in so einer art vorgeschlagen bin mir aber nicht sicher:
Jeden Tag um eine (oder Zwei) bestimmten Zeiten, gibt es das "Money Time".
Sagen wir es ist immer um 15 Uhr und um 20 Uhr:

Wenn es 15 Uhr ist, gibt es am Spawn einen bestimmten ort, 
wo von der luft Emeralds fallen (der Radius sollte schon ca. 10 sein damit jeder was abbekommt). Man kann diese Emeralds nicht weg schmeißen (damit es nicht dein Freund bekommt oder so).
Am Ende werden dir die Emeralds durch Credits umgetauscht.
Ich hoffe du hast dieses Prinzip in dieser Art verstanden.
Außerdem:
Iron,Emerald, und Golduser haben hier einen vorteil:
Iron bekommt beispielsweise 10% mehr Credits als Normale user
Emerald 20% und Gold 30% (oder andere Zahlen)
und dieses "Money Time" sollte auch immer angekündigt sein:
Beispielsweise:
1 Stunde vor dem Event wird die MOTD geändert zu "Money Time: 15 O'clock GMT+1" oder so
Im Chat wird das auch bescheidgegeben:
"In 30 Minuten startet "Money Time am Spawn"
"In 15 Minuten startet "Money Time am Spawn"
" [...] " 
oder eben irgentwie so, damit jeder es mitbekommt.
(Money Time kann man auch durch was anderes benennen, mir ist nichts anderes eingefallen)
Mein Persönliches Rating: 4/5 - da es auch mehr User anlockt 

___

**1v1 Zombies am Spawn:**

Der Name sagt eigentlich schon viel:

Am Spawn sind einfach ein paar 1v1 Zombies die rumlaufen (sie können nicht aus der Region raus!!) Am besten nochdazu fixen, dass sie nicht Despawnen.

Wenn man diesen Zombie am Spawn hitted, wird man in die 1v1 Warteschleife hinzugefügt und wenn nocheiner HItted, startet das 1v1. Wir haben ja schon dieses System, nur es wäre eben toll wenn sie Automatisch Spawnen.
Ich glaube das ist nicht so Aufwendig, aber ich finde das eig. richtig cool, vorallem das am Spawn auch sehr viele immer rumlaufen - so kann man einfach kurz ein Zombie schlagen und schon ist man in einem 1v1 und kann ein "Quick-Fight" machen :) 

Mein Persönliches Rating: 3/5 - Nicht sehr aufwenig aber toll 

___

**Challenges:**

Wenn man /challenge eingibt (oder anderer weg), muss man verschiedene Challenges machen, ohne zu sterben.
Beispielsweise:
Ich gebe /challenge ein, dann werde ich in einen Lavasee geportet und muss darin 10 Sekunden überleben. Wenn ich es geschafft habe, kommt die nächste Challenge:
- Mache 2 MLG's
- Dann wird man in eine Stelle geportet wo ein Bot drinnen ist, die Challenge: Töte diesen Spieler
- Man wird zu einem Jump and Run geportet - nicht runterfallen - bis checkpoint 1 schaffen
- [und viele Weitere Challenges, bei anfrage kann ich noch mehr schreiben, man kann auch bei /form den Usern fragen]

Wenn man einmal alle Challenges geschafft hat, 
wird es noch schwieriger:
"Überlebe 20 Sekunden in der Lava"
"Mache 4 MLG's"
"Töte 2 Bots"
"Schaffe es beim Jump and Run bis Checkpoint 2"
usw.

am ende, wenn man gestorben ist, bekommt man je nachdem wie weit man war einen Preis von Credits
Wenns geht sollten dafür auch Stats geben wer in den TOP 10 ist oder so

Mein Persönliches Rating: 5/5 - Ich find sowas richtig nicht - bestonders mit noch weiteren Challenges)

___

**/party mit Freunden:**

Das ist kein Gewönliches Party sondern etwas anders, da man bei EarlyHG sowieso nicht teamen darf etc:

Wenn man /party eingibt, öffnet sich eine GUI wie bei /battle.

Hier ausfürlich:
(Hier ein Screenshot um sich es Bildlich vorzustellen: http://prntscr.com/77qrgw ) 
- /party eingeben - Es öffnet sich eine Chest GUI (man kann nicht mit "E" aus der GUI, man muss es mit dem Roten Glass Closen)
- Wenn man auf ein Witherkopf drückt, werden alle Spieler angezeigt, man muss dan auf die Person drücken mit der man Spielen will.
- Wenn man eine Anfrage gesendet hat, wird er als Zombiekopf in der GUI angezeigt
- Wenn er die Anfrage angenommen hat, wird er als SteveKopf in der GUI angezeigt.

- Mit der Chest kann man die Rüsstung, Schwerter, Inventar setzen wie bei /battle
- Mit dem Amboss kann man noch kleine einstellungen machen wie bei /battle. Beispielsweise Dubblejump oder die Map
- Mit dem Papier kann man das Game Setzen beispielsweise Teamdeathmatch (50% des Teams vs 50%) oder FreiFürAlle oder Survival (Es spawnen immer mehr Bots und man muss als Team überleben bis alle Tot sind) und ganz viele andere Spiele.

Wenns geht, sollte für jede Party eine eigene Map vorhanden sein wie bei Timolia, damit die Bots den anderen nicht nerven oder andere Bugs vermeiden.
(=> Einfach paar Maps bauen und sie 15 mal Copy+Paste machen) 

Wenn alles gesetzt ist, nurnoch das Grüne Glass drücken und alle werden Teleportiert.

Ich denke man hat das Prinzip so verstanden, im endeffekt kannst du es auch gestalten wie du willst. :D

Meine Persönliche Rating: 6/5 - Einfach cool mit freunden sein Privat-Spiel zu haben - würde bestimmt auch paar Freunde von Spielern anlocken .. aber ist bestimmt sehr sehr Kompliziert zu coden

___

So.. wenn du bis hier gelesen hast - Props an dich
Hoffentlich sind da paar sachen dabei die dir gefallen :D
Besonders gefällt mir das Party System ^-^ aber auch Challenge und MoneyTime finde ich toll :D 
Autorespawn und 1v1 ZOmbies am Spawn kann man ja so nebenbei machen falls es gut ankommt ^-^

__

Ende Ente

**Comment by lukas81298** [comment]
gute ideen

**Comment by HDuck** [comment]
Freut mich sehr! :D

**Comment by lukas81298** [comment]
Das mit der Party wird auf nem externen Server gemacht. De Rest machen wir vielleicht mal irgendwann............
