### ISSUE TITLE
1v1 mit Kits!

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#29]
Wie der Titel schon sagt:
1v1 mit Kits:
Wie wäre es, wenn man 1v1's machen könnte aber dass man auch noch Kits nehmen kann?
Also man wird dann abgefragt
"Welches Kit wollen sie nehmen?"
Dann kann man eben entscheiden
"None" oder eben Kits wie beim Kit Selector,
ABER:
Es gibt auch Kits in der Blacklist die man nicht benutzen kann,
z.B Kit Nuker, Grappler, Aura, Endermage, Vacuum, Turtle, Magma, etc.

Also es gibt nur bestimmte Kits die man nehmen kann, welche die anderen Spieler die auch im 1v1 sind nicht belästigt:
z.B Snail, Viper, Kangaroo, Glider, Prisoner etc.

Ich hoffe du hast das Prinzip verstanden

Das könnte schon sehr schwer werden das zu coden, daher kann ich verstehen, das du es nicht machst. :)

**Comment by lukas81298** [comment]
Mal schauen. Das lässt sich einbauen.

**Comment by HDuck** [comment]
*(ich wollte nicht extra das selbe wieder schreiben, daswegen OPEN'e ich diesen "Issue")*

Die Trialmods (Stark & Stan) hatten letztens auch sowas vorgeschlagen mit 1v1's mit bestimmten Kits 
(Genau so wie ich es oben beschrieben hab)

___

**Der Text von ihnen:**
So me and stark were skyping, doing some 1v1's, and we came up with the idea, that it might be cool if there were some kits being added into 1v1. 2 examples:

-Speed
-Anchor

It's just a suggestion, but in our opinion it would make the 1v1's a bit more interesting and more fun to play. Please leave your opinion and more ''1v1 kits'' idea's!

___


Wir haben ja jetzt ein völlig neues 1v1 System als vor 6 Monaten, daher meine Frage, könntest du sowas einbauen? Wäre schon cool find ich, beim StaffChat haben auch alle zugestimmt:

- Sure, why not?
- Cool idea
- Nice
- good idea (ich)


~ Ente

**Comment by lukas81298** [comment]
Ich werde mich am Wochenande dransetzten

**Comment by HDuck** [comment]
Großartig :3

**Comment by lukas81298** [comment]
Ok, es jetzt einigermaßen implementiert. Ein paar kleine Bugs gibt es noch.
