### ISSUE TITLE
/lavachallenge Command Remove

### ISSUE THREAD

**Issue by CraftingExpertDE** [MineKits/MineKits#294]
Der Command bringt ums genau zu sagen nix mehr, es gibt bugs wenn man die lavachallenge macht, sodass man spawn items bekommt und im großen und ganzen kann man auch bei /warp lava trainieren und es ist genau so sinnvoll wie /lavachallenge

**Comment by HDuck** [comment]
Da sind halt coole Features dabei, dass man noch Rüssi und alles ändern kann aber im prinzip ist es ja auch /warp lava - stimmt..

Man kann es ja auch durch dieses /challenge ersetzen, was ich mal vorgeschlagen hatte: https://github.com/MineKits/MineKits/issues/288
4. Punkt  ^-^
