### ISSUE TITLE
Berserker Buff? + /givekit permissions

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#296]
Hey lukas, könntest du den Mods wieder /givekit permissions geben? Damit man sieht, welches Kit jemand hat, der sein MixedKit benutzt (Seitdem neuem Permissions plugin hat man nichtmehr darauf rechte ^^)

und:

Du hattest ja mal Berserker leicht verbessert (Stärke für 1 Sekunde)
Mir ist aufgefallen, dass das Überhaupt nichts bringt, könntest du das auf 3 erweitern?

und zu berserker hatte ich noch eine Upgrade Idee:

1. Upgrade: länger die Effekte haben (außer Stärke)
2. Upgrade: Stärke +1 sekunde länger //oder 2//

**Comment by lukas81298** [comment]
Meinst du /getkit?

**Comment by HDuck** [comment]
Ja sry
