### ISSUE TITLE
Angel in NoSoup

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#297]
Yo Lukas,
mich hatte jemand gefragt, ob man bei NoSoup nicht noch eine Rod (Angel) bei NoSoup hinzufügen kann, daher wollt ich dich fragen, ob du das machst

Wär eig. garnicht so schlecht, weil viele dieses RodPvP machen :D Hive-Spieler undso 

Ist ja auch nicht viel aufwand denke ich

**Comment by lukas81298** [comment]
NEIN.
