### ISSUE TITLE
Viele Achivment Ideen [26]

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#298]
- "**Mixer**"
Mache 10 Kills mit einem MixedKit

- "**Good Fight**"
Schreibe nach einem Fight (frist ca. 10 sekunden) "Good Fight" "GF" oder "GG" bzw. "Goodgame"

- "**Winner**"
Gewinne ein LMS

- "**Spiderman**"
Platziere 20 Cobwebs (von den Kisten)

- "**Bomber**"
Platziere 5 TNT (von den Kisten)

- "**Bow Master**"
Töte 1 Spieler mit einem Bogen

- "**Noob**"
Sterbe 5 mal hintereinander ohne ein Kill zu machen 

- "**10**"
Töte einen Spieler und hab 10 Herzen
*(also genau da wo der Gegner dann getötet wird muss die Person (die das Achivment bekommt) 10 Herzen haben) *

- "**Magician**"
Verzaubere dein Schwert *(ja ich weis, man kann kein Sharpness undso bekommen)

- "**#FallDMG**" *(kann auch anders genannt werden mir fällt nix ein)*
Sterbe an Fallschaden 

- "**Killsteal**"
Töte einen Spieler 1 Hit

- "**Grilled**"
Sterbe an Feuer 
(Nicht an Lava, das gibts schon - falls man das nicht unterscheiden kann - dann dieses Achivment nicht machen)

- "**Fish**"
Sei 1 Minute am Stück im Wasser ohne raus zu gehen

- "**Quest**" *(kann auch anders heißen)*
Schaffe alle 3 Quests 

- "**Need Help**" *(kann auch anders heißen)*
Öffne das /faq 

- "**Naked**" 
Töte einen Spieler bei Feast/NoSoup ohne Rüsstung

- "**Ooh baby it's a triple**" 
Mache 3 Kills nacheinander 
*(Nach einem Kill hat man eine 30-60 sekunden Frist bis man den Nächsten Tötet)*

- "**Spoilsport**" *(übersetzt Spielverderber)
Töte eine Person, welche eine Killstreak von 10 oder mehr hat

- "**Assassin**"
Töte einen Spieler von Hinten (sein Rücken schlagen) 

- "**Sneak**" *(oder anders)*
Töte einen Spieler während man Sneakt

- "**Focus**" *(oder anders!!)*
Töte 3 mal den selben Spieler hintereinander
(also man tötet ihn => Er kommt wieder zu dir, du tötest ihn ... bis man ihn 3x hintereinander gekillt hat)

- "**Afterlife**" 
Töte ein Spieler wenn du bereits tot bist
(beispielsweise jmd. tötet dich, aber du hast tnt gesetzt und er Stierbt, oder du hast im selbn Moment geschlagen, oder hast ein Pfeil geschossen...)

- "**Payback**"
Töte den Spieler welche dich vorhin getötet hat

- "**Air Kill**" *(oder anders!)*
Töte einen Spieler während er in der Luft ist
(Beispielsweise jemand hat nurnoch wenig leben und Springt vom Tower und du Hittest ihn dann in der Luft)

- "**Do not Team**"
Blocke mit dem Schwert 10 Sekunden während ein gegner vor dir ist (bzw. im Radius von ~7), und dann Töte ihn 

- "**Surprise**" *(oder anders)*
Töte ein Spieler während er in die Kiste schaut 
___

Yo das wars ^-^
Villeicht ist ja das ein oder andere Gute dabei 

Aber mach lieber das als nebensache - also zuerst auf MineHG oder andere "guten" features konzentrieren :D

**Comment by CraftingExpertDE** [comment]
Das Achievement "Quest" gibt es schon, es heißt "Tryharder"

**Comment by HDuck** [comment]
Ohh kk - hab ich noch nicht

**Comment by lukas81298** [comment]
Ich werde sicherlich viele in Zukunft umsetzten

**Comment by HDuck** [comment]
Freut mich =D

**Comment by HDuck** [comment]
Wenn wir schon beim Thema Achivments sind, wäre dieses Feature auch nicht schlecht, falls es das nochnicht gibt:

Wenn man das Achivment Menu sieht, muss man auf ein Achivment Rechtsklicken, welches man noch nicht hat:

Dann zahlt man für XXX Credits die Information, wie man dieses Achivment bekommt
=> Keiner Fragt andere wie man ein Achivment bekommt

**Comment by HDuck** [comment]
Von den 26 wurden nur 8 genommen? :0 
Oder kommen da noch irgentwann weitere? ^^
Naja egal
