### ISSUE TITLE
Battle Queue

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#299]
Hey Lukas, wir wollten ja mal sowas wie die Queue wieder einführen, so wie früher, aber dann würde es keine 2v2's,3v3's,4v4's.. mehr geben (oder irgentwie so). Ich habe mir dafür ein kleines Design ausgedacht villeicht gefällt es dir ja.. :)
(Ich hoffe es heißt "Queue" bin mir nicht sicher)
___

So kannst du es dir Bildlich vorstellen: http://prntscr.com/7ab52e

Also man hat bei /battle ein Grauen Farbstoff (beispielsweise).
Wenn man diesen Rechtsklickt öffnet sich die GUI wie bei dem Screenshot.

**Die erklärung dazu:**

- Der Graue Farbstoff ganz oben hat keine bedeutung, einfach eine Deko

- Das Holzschwert fügt dich in die 1v1 Queue ein
- Das Goldschwert fügt dich in die 2v2 Queue ein
- Das Steinschwert fügt dich in die 3v3 Queue ein
- Das Eisenschwert fügt dich in die 4v4 Queue ein
- Das Diamantschwert fügt dich in die 5v5 Queue ein

- Das Rote Glas entfehrnt dich wieder von der Queue 

**Außerdem:**

Das Holzschwert heißt "1v1 Queue" aber als "untertitel" steht da, wie viele Spieler bereits in der Queue sind
und dass genau so wie bei den anderen Queue'n

beispielsweise:

Das Eisenschwert: 
Titel bzw der Nametag vom Schwert: **4v4**
als "Untertitel": **5/8 Players**

___

Wär echt nice wenn du es irgentwie es machen könntest, dass es wieder Queuen gibt beim 1v1 :D
Hoff das dieses "Design" nicht zu schwer ist und es iwie umsetzbar, hab drauf geachtet, dass es wirklich jeder Spieler verstehen kann und nicht zu Kompliziert ist

**#EDIT
Unten in den Comments habe ich ein anderes "Design" gemacht**

**Comment by EinfachNiggo** [comment]
Das wäre supercool! :)
Ist das dann Full Inv oder 1Bar? [Ich würde FullInv sagen :D]

**Comment by lukas81298** [comment]
1. Wie kann man mit Freunden spielen?
2. Wer kann Einstellungen vornehmen?

**Comment by HDuck** [comment]
Das soltle nur dieses Queue sein,
also wir hatten ja damals ein Redstone Item das "1v1 Queue" hieß (schon etwas länger her) 
und das ist eben dass selbe nur, dass auch 2v2, 3v3 etc. ermöglicht werden
Diese Feder als Items soll es aber immernoch geben, damit man mit freunden Spielen kann also der Graue Farbstoff soll es **nicht** ersetzen
=> also ist dieser Graue Farbstoff ein weiteres Item beim 1v1

Ich würde vorschlagen, dass dieses 1v1 Queue 1 Hotbar + Rüsstung ist,
und der rest einfach Full Inv. + Rüsstung.


Falls man mit anderen einstellungen mit freunden Spielen will, kann man immernoch das jetzige Item nutzen,
aber wenn du willst, habe ich auch eine andere Idee, wo man auch einstellungen machen kann

**Comment by HDuck** [comment]
Hier der 2. Vorschlag:
Wie gesagt, wenn man mit freunden spielen will, soll man die Feder benutzen, 
bei diesem kann man jetzt auch die Einstellung setzen:
___

Screenshot zum Bildlich vorstellen: http://prntscr.com/7afy14

Also man hat bei /battle ein Grauen Farbstoff (beispielsweise).
Wenn man diesen Rechtsklickt öffnet sich die GUI wie bei dem Screenshot.

- Die Graue Wolle hat keine Bedeutung, nur Deko
- Die Schwerter stehen wieder für 1v1, 2v2, 3v3, 4v4 oder 5v5
- bei dem Amboss kann man die Einstellungen machen  
(Wenn man beispielsweise dass 2v2 ändern möchte, dann muss man auf den Amboss gegenüber vom Goldschwert klicken)
- Wenn man ein "Quick-Battle", machen will, ohne einstellungen zu setzen, drückt man einfach auf die Schwerter, und man wird dann in eine zufällige Queue hinzugefügt

**Die Einstellungen**
Hier ein Screenshot zum Bildlich vorstellen: http://prntscr.com/7afzgd

- Die Eisengitter sind nur zur Deko und übersichtlichkeit da
- Mit dem Roten Glass kommt man wieder zum 1. Menu 
- Man kann nicht auf die Schwerter da oben drücken, diese stehen nur dafür, welches Item man hat
- Man kann nur auf die Suppen bzw. Pilze klicken.

Beispielsweise man will ein 2v2 mit dem Steinschwert haben mit 32 Pilzen: 
Dann geht man auf die 32 Pilze unter dem Steinschwert und klickt dieses an

Außerdem sollen diese wieder einen Untertitel haben, wie viele Spieler gerade drinnen sind.

Wenn gerade zu wenig Spieler da sind, kann man auch einfach in das Random Queue wie ich oben geschrieben hab:
Bei dem 1. Menu muss man einfach auf ein Schwert drücken, und man wird in eine Zufällige Queue hinzugefügt

___

Ich hoff so ist es besser auch mit einstellungen und dass es nicht arg zu Kompliziert ist :)

**Comment by lukas81298** [comment]
Vielleicht machen wir das mal später.

**Comment by HDuck** [comment]
kk c:
Aber wäre noch gut, wenn du wieder den **1v1 Zombie fixen** könntest oder dieses **1v1 Item** (Redstone -> Zucker so wie früher)) addest

**Comment by lukas81298** [comment]
Ist doch schon wieder da.
