### ISSUE TITLE
Kit Portal

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#30]
Kit: Teleporter oder Portal:

Items: Blauer Farbstoff, Roter Farbstoff

Wenn man mit dem Blauen Farbstoff einen Block rechtsklickt, dann wir der Block zu Blauen Wolle Replaced.
Wenn man den Roten Farbstoff auf einen Block Rechtsklickt, dann wird es durch rote Wolle Replaced.

Wenn man Dann auf diese Wolle geht, wird man zur anderen Wolle teleportiert.

Die zwei Wollen verschwinden automatisch nachdem sie 15 Sekunden auf dem Boden waren.
Dann hat man ein Cooldown von 45. Sekunden.

Das Kit ist so wie Endermage aufgebaut:
- Wenn man das Portal setzt, müssen 2 Blöcke über der Wolle platz sein (kein suffucaten)
- Man kann nicht bei Lava etc. Magen

Ich hoffe du hast das Prinzip verstanden. :)

**Comment by LabyStudio** [comment]
Ich würde es lieber wie eine Portal gun haben ;)
