### ISSUE TITLE
/csuicide für Mods (suicide death wird nicht dazugezählt) 

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#302]
Hey Lukas,

Ich wollte dich fragen, ob du so ein Command wie "/csuicide" machen könntest:
=> User haben dafür keine Rechte nur für Mods

**Was kann der Command?**
Wenn man den eingibt ist das genauso wie /suicide, aber das wird nicht als death zugezählt 

**Warum?**
Weil ich finde das ist richtig doof, wenn immer die Stats kaputt gehen, wenn man sich killen muss, falls da ein Hacker oder sonnstwas ist, da man gerade im Fight ist 

*(Ich weis, ich kann genauso im Fight einfach /Admin eingeben, aber ich finde das ist bisl abuse undso, daswegen geb ich immer /suicide ein - aber so gehen halt die stats kaputt und der Spielspaß sinkt :s)* 

Also fall sowas möglich ist, wäre es echt super wenn du das machen könntest
aber kannst dir dafür zeit nehmen und erstmal wichtigeres machen ^^

**Comment by EinfachNiggo** [comment]
Wird 100% abused.

**Comment by HDuck** [comment]
Soll daswegen nur für Mod sein ^^

aber wenn Mods abusen naja ..
dann sollte er meiner Meinung auch kein Mod sein
