### ISSUE TITLE
Nametag über Spieler

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#304]
Der Spieler "JulienPvP" hat über Form dashier gewünscht:

"Es wäre cool, wenn jemand einen Rang hat, dass der Name über dem Spieler auch farbig ist, also nicht Tab sondern der NameTag" 

http://prntscr.com/7b8u3d

**Comment by EinfachNiggo** [comment]
Finde das nicht so cool, werde so schon genug getargetted ._. ^^

**Comment by CraftingExpertDE** [comment]
@EinfachNiggo /nick

**Comment by HDuck** [comment]
oder /tag, dann isses ja weg :o

**Comment by lukas81298** [comment]
Wurde jetzt teilweise eingefügt, klappt aber noch nicht bei jedem Spieler.
