### ISSUE TITLE
Verbesserung 1v1FPS

### ISSUE THREAD

**Issue by xBlackJack** [MineKits/MineKits#306]
Viele sagen Sie hätten gerne ein 1v1FPS warp. Falls du nicht weißt was das ist, das ist so ein "Kasten" wo viele Spieler gegeneinander kämpfen. Also man frag vorher ob man ein 1v1 möchte. Falls du nicht verstehst  was ich meine frag mich oder ander im ts die meinsten sollten das wissen was das ist. Das gabs frühe auf vielen Kitpvp servern. z.B Kitpvp.de
~xBlackJack

**Comment by HDuck** [comment]
Lukas wollte ja sowas nicht machen weil:
- Trashwarp
- Random PvP'er die man Tempbannen muss

Gehen das RandomPvP'en könnte man eig. ein Plugin machen:
Man muss 10 Sekunden lang einen Spieler Rechtsklicken, und er dich, dann können nur die 2 sich Hitten

**Comment by EinfachNiggo** [comment]
Anil dann können die ja gleich ein normales 1v1 machen ;D
