### ISSUE TITLE
Kit Illuminati | Komisch zu bedienen, verursacht lags

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#307]
http://prntscr.com/7ds630
Hey Lukas oder Laby,
mich haben paar leute wegen Kit Illuminati Angeschrieben:

1. Bei leuten die ein etwas schlechteren PC haben, kommt es zu FPS einbrüchen,
kann man das nicht iwie anders umsetzen

2. Es ist komisch zu bedienen, wo ich ihnen zustimmen muss:
Wenn man das Illuminati 3eck Spawn, 
Spawnt ja ein Dreieck und dieser Strahl ( http://prntscr.com/7ds630 )
Wenn man auf diesem Strahl steht, wird man angezogen zum Dreieck.
Man kann aber nicht bestimmen, wo der Strahl hinzeigt, daswegen verstehen auch viele das Kit nicht.

Ich hätt eine andere Idee, wie man das mit dem "strahl" umsetzen könnte:

- Wenn man sein Kit Aktiviert, kommt wie gewöhnlich dieses Dreieck
- Wenn sich jemand auf den Punkt (oder eins daneben also radius=2) stellt, wo man das Kit Aktiviert hat, wird er zu dem Enderauge von dem Dreieck hochgezogen und erleidet Fallschaden
- Der Illuminat wird nicht hochgezogen

Also statt dem Strahlt, muss man sich nur unter diesem Dreieck stellen
=> Sollte auch die lags beheben, da der strahl rallativ viele Partikel macht

**Comment by lukas81298** [comment]
Kit entfernt
