### ISSUE TITLE
Kit Cloner

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#31]
Kit Cloner (aufgabaut wie Wisp):

Wenn man sein Item Klickt, Spawnen 5 Spieler die aussehen wie du und sie bewegen sich.
Die Clone Despawnen Automatisch nach 10 sekunden falls sie noch nicht getötet worden sind.
Cooldown: 40 sek.

Wenn es möglich ist, sollten die Clone auch ein Cape haben, damit man sich von dem Clon nicht unterscheidet.

**Comment by lukas81298** [comment]
Wird in Minecraft 1.8 problematisch, könnte aber möglich sein :) Find ich gut

**Comment by EinfachNiggo** [comment]
Dojo.

**Comment by HDuck** [comment]
@EinfachNiggo  ist eigentlich ja von MCPVP aber egal xD

**Comment by EinfachNiggo** [comment]
Asooo xD ich dachte an Minion Leader :P
