### ISSUE TITLE
Stats Bug

### ISSUE THREAD

**Issue by xBlackJack** [MineKits/MineKits#310]
Wenn man /stats (Spieler) macht, dann bekommt der, den ich die stats wissen will, die stats angezeigt.
Zum Beispiel wenn ich /stats 2Lifeted4you mache, dann bekommt er eine art inventar, wo die stats angezeigt werden. Man selber bekommt nicht angezeigt.
Bitte fixen :)

**Comment by HDuck** [comment]
Wurde schon Reportet :D
https://github.com/MineKits/MineKits/issues/309

Hab das andere geclosed

**Comment by lukas81298** [comment]
Fixed
