### ISSUE TITLE
Kitidee Timelord

### ISSUE THREAD

**Issue by xBlackJack** [MineKits/MineKits#311]
Bekannt durch  mcpvp, falls du nicht weiss wie das geht frag uns im ts.
(rechtsklick kititem - spieler im bestimmen radius eingefrohren)

**Comment by HDuck** [comment]
Ich glaube Lukas wollte keine Kits mehr von anderen Servern "klauen/übernehmen" ^^ Nur eigene Ideen soweit ich weis

**Comment by lukas81298** [comment]
Ja. Ich finde wir haben genug Kits vom ehemaligen MCPVP. Jetzt ist es an der Zeit für eigene Ideen.
