### ISSUE TITLE
3 Achivments gehen nicht

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#313]
Das Achivment Noob; DoubleKill; Spiderman geht nicht.

Noob: Sterbe 5x ohne einen zu töten | Geht nicht
DoubleKill: Töte 2 leute gleichzeitig (bzw in einer Zeitspanne) | Geht nicht
Spiderman: Platziere 5 Cobwebs | Geht nicht

& noch eine Frage:
Werden keine weiteren Achivments von den 26 die ich vorgeschlagen hatte umgesetzt? Ich find da waren schon weitere guten dabei weil nur 8 von den gemacht wurden - oder wolltest du die irgentwann anders hinzufügen? ^-^

- Ente :)

**Comment by lukas81298** [comment]
Manche hören sich einfach an, sind aber schwer umzusetzen.

**Comment by HDuck** [comment]
**Naked** geht übrigens auch nicht,
wollte kein extra issue dafür öffnen

Naked: Töte ein Spieler bei Feast/NoSoup, während du keine rüssi hast
