### ISSUE TITLE
10 Kit Ideen! 

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#314]
Hab mir mal ein paar Kits ausgedacht, hoffe dir gefallen die c:
___

**===Kit Übersicht:===**
Bieber; Knockbacker; Lifestealer; Technician; Mixer; Penguin; Priest; Plague; Zombie; Smith
___
**Kit Biber**

*Fähigkeit:*
- Holz platzieren (von mir aus diese "Unechten Blöcke" wenn es anders nicht geht - wäre aber toll, wenn man sie nicht sofort mit Rechtsklick zum verschwinden bringt) 
Man hat ca. 10 Blöcke und pro Kill bekommt man auch mehr 
- Nachdem man im Wasser war, bekommt man für ca. 3 Sekunden Speed 3

*Was kann man damit beispielsweise machen?*
- Im Notfall sich mit den Blöcken hochbauen
- Sich mit den Blöcken einbauen (bei dem 1x2 Länge 10-gang beispielsweise)
- Speed 3 vom Wasser nehmen und weglaufen/comboen

*Anderes:*

Upgrades:
1. Man startet mit mehr Holz
2. Man bekommt länger Speed
___

**Kit Knockbacker** *(oder anders?)*

*Kit Item:* Redstoneblock

*Fähigkeit:*
Wenn man sein Kititem in der Hand hat, bekommt der Spieler, welcher dich hittet, 50% des Schadens, den er dir gibt (oder weniger Prozent wenn das geht, bzw wenns zu OP ist) 

Damit es nicht zu OP ist:
Sobald man das Kititem in der Hand hat, muss man erst eine Sekunde warten, bis dieser "Rückangriff" startet

Beispiel:
Jemand macht macht dir 3 Herzen schaden, während du dein Kit Item in der Hand hälst:
Er bekommt 1,5 Herzen Schaden

*Beispiels Situation*
- Beim refillen/craften das Redstone in die Hand nehmen 
- Wenn dich die Person gerade Comboed, kann man sein Kititem in die Hand nehmen

Kontra: 
- Während man das Item in der Hand hat, kann man nicht wirklich Soupen, bzw. man muss mehr Soupen als der andere 

___

**Lifestealer** *(oder anders?)*

*Kit Item:* Redstone Torch

*Fähigkeit:*
- Schlage jemanden mit dem Kit Item, so verliert er 3,5 Herzen und du bekommst die 3,5 Herzen & ein ~3 Sekündigen Regeneration 2 schub 

*Beispiels Situation:*
- Man hat wenig Suppen => Jemanden hitten
- Man recraftet schnell => Jemanden hitten und von der Regeneration überleben

*andere Sachen:*
- Cooldown 40 Sekunden

Upgrades:
- Cooldown -5 Sekunden
- Regeneration +X Sekunden 
- Nimm 4 Herzen weg 

BEI NOSOUP VERBOTEN!
___

**Kit Technician** 

*Kit Item:* Dispenser 

*Fähigkeit:*
Vergleichbar mit dem Geschütz von CTF

- Setze dein Dispenser, dann wird ein Dispenser über einem ZAUN gesetzt.
Dieser Dispenser schießt dann Pfeile zu den Spielern im Radius von 4 Blöcken (wenn es mehrere im Radius gibt, werden die alle anderen gleichzeitig getroffen) 
Wenn ein Pfeil geschossen wird, soll ein Cooldown von ca. einer 1/2 - 1 Sekunde kommen.
Der Techniker selbst soll nicht getroffen werden
Der Dispenser despawnt nach 10 Sekunden

*andere sachen:*

Cooldown: 45 Sekunden

Upgrades:
1. Radius erhöhung +1 (oder 2)
2. Dispenser ist +5 Sekunden da

___

**Kit Mixer**

*Fähigkeit* 
- Sehr geringe Chance pro hit, dass die GANZE Hotbar des Gegners vermischt wird 
(Also in der Hotbar sind dann mindestens 3 leere Slots und mindestens 1 leere Bowl [wenn 2 Bowls da sind, sollen sie nicht gestackt weerden], das Schwert kann auch in das Inv gelangen) 

Im Chat soll dann auch eine Nachricht erscheinen, wo man sieht, dass seine Hotbar vermischt wurde "Die Hotbar von <PLAYER> wurde gemixt." oder so

*Upgrades:*
- Mindestens 3 Bowls in der Hotbar 

Cooldown: -Nop-

___

**Kit Penguin**

*Kit Item:* Eisblock

*Fähigkeit*
- Man wird in die Richtung "geslidet" in die man schaut, vergleichbar mit Superman, doch man fliegt nicht in die Luft, sondern man bleibt am Boden. 
Während man Slidet, "gleitet" man über dem Wasser, falls man in die richtung von Wasser schaut.

Außerdem bekommt man ein schwarzen Lederhelm (Durability 0), da Pinguine ein schwarzen Kopf haben und unter dem Pinguin wird dann Eis gesetzt (so wie die Gold/Emerald/Iron Boots)
(Natürlich nur, während er "slidet") 
(falls vor ihm ein Block ist, soll der Effekt von dem Kit Snake kommen => Er geht automatisch hoch)
Man wird dann ca. 8 Blöcke nach vorne geboosted/"geslidet" 

*Beispiels Situation*
- Weglaufen zum Recraft

*andere sachen*

- Cooldown: 40 Sekunden

___

**Kit Priest** *(oder anders z.B healer?)*

**Fähigkeit:*
- Kleine Chance pro hit (10% 5%? muss man testen) volle Herzen + Regeneration 1 für 5 Sekunden  zu bekommen 

BEI NOSOUP VERBOTEN

___

**HIER NOCH PAAR KITS, EXTRA FÜR MINEHG SPEZIALLISIERT:**

___

**Kit Plague** *(oder anders? Dirty?)*

*Kit Item:* Die schwarze Schallplatte (ID: 2266) 

*Fähigkeit:*
- Rechtsklicke ein Block mit der Schallplatte, um ihn in Dirt zu verwandeln.
Man kann in der Invis-Zeit Workbenche nicht Rechtsklicken!! Nach der Invis-Zeit schon
Außerdem kann man keine Kisten Rechtsklicken 
(Nach ca. 10 Dirt umwandlungen kommt der Cooldown fürs Rechtsklicken) 
- Schlage mit der Schallplatte, um Dirt damit zu setzen 
(Nach ca. 10 Dirt setzungen komm der Cooldown fürs Linksklicken) 

*Beispiele, wenn man es gebrauchen kann*

- Man ist in einer Trap, einfach das Holz (oder Workbench u. anderes Trap Material) zu Erde verwandeln und man ist Raus 
- Towern bei Block-Knappheit
- Wenn man unten beim Sein feststeckt weil die Pickaxe kaputt ist

*andere sachen:*

Cooldown: 
- Fürs Rechtsklicken 30 Sekunden Cooldown (Cooldown wird erst eingesetzt, wenn man die 10 Dirt "Umwandlungen" gemacht hat
- Fürs Linksklicken: 50 Sekunden Cooldown ( -//- )

___

**Kit Zombie** *(oder anders?)*

*Kit Item:* Zombiekopf

*Fähigkeit:*
- Rechtsklicke ein freundlichen Mob mit dem Kit-Item, so wird er zu einem Zombie.
Dieser Zombie greift dich nicht an (wenns geht, auch nicht wenn man ihn Hitted)
(Andere Zombies sollen ihn schon angreifen) 

*Beispiels Situation*
- In der nähe sind gerade viele Mobs, dann kann man sie als Hilfe nehmen

___

**Kit Smith**

*Fähigkeit:*

Alles was man in den Ofen legt, wird Doppelt so schnell gebraten als Normal. 
(Oder vlt. Instand fertig?)

___

Das wars!
Würde mich freuen wenn was davon umgesetzt wird c:  
~Ente

**Comment by EinfachNiggo** [comment]
Technician ist von Dojo, der Rest ist echt cool :D

**Comment by HDuck** [comment]
Technician ist von Capture the Flag [MCPVP] ^-^
Hab wennschon die geklaut
Naja egal c:

**Comment by lukas81298** [comment]
Lifestealer und Priest sind relativ einfach umzusetzten, das werde ich warscheinlich heute machen. Technican wird warscheinlich Engineer genannt werden, das dauert aber noh etwas, da erst die lags behoben werden.

**Comment by lukas81298** [comment]
Die anderen Kits werden dann mal im Laufe der Zeit umgesetzt!
