### ISSUE TITLE
1v1 invis

### ISSUE THREAD

**Issue by lejaden** [MineKits/MineKits#315]
Fixt mal diesen bug, welcher schon länger bekannt ist, dass man nach einem 1v1 wieder jeden Spieler sieht!

**Comment by lukas81298** [comment]
Wurde noch nicht reported. Erklär das mal bitte.

**Comment by lejaden** [comment]
Was? Das ist der bekannteste Bug. Nach einem 1v1, sieht man nur noch die Personen, die nach dir gejoint sind und die Person, gegen die du gefightet hast.

**Comment by HDuck** [comment]
Ich weiß nicht, was bei dir da nicht geht o.o
Ich hab ein 1v1 gemacht und konnte danach wieder jeden sehen der Online ist

Infos:
Version 1.8
Standart Kit: Diaschwert + Rüssi + 1 Hotbar

**Comment by lejaden** [comment]
Jo, staffmember geht alles, aber normale Spieler eben nicht.

**Comment by lukas81298** [comment]
Das ist jetzt sehr komisch. Ich werds heute morgen mal debuggen.

**Comment by HDuck** [comment]
Stimmt, es liegt wirklich daran, dass man Staffmember ist,
aber an der Version liegt es nicht ^^ (Habs mit der 1.8 getestet)

Achja Lukas außerdem was mir aufgefallen ist:
Bei dem 1v1 kamen richtig viele "You don't have permissions for this area." Nachrichten wegen dem Gras, .. kannst du das ausschalten?
