### ISSUE TITLE
Neue Ideen!

### ISSUE THREAD

**Issue by lejaden** [MineKits/MineKits#317]
Wir brauchen allgemein neue Ideen, um MineKits nicht sterben zu lassen. Viele User haten den Server schon, da es einfach zu viele laggs und paar große buggs gibt! Als Beispiel nehme ich mir den mdtraining.eu server. Ist ein ziemlich kleiner Server(15 player), dennoch viel interessanter als MineKits zurzeit. Dort gibt es zB nicht nur die LavaChallange, sondern auch Sachen wie ArrowChallange, DamageChallange. Außerdem auch viele events, die nur auf dem Server zu finden ist. Also zusammengefasst sollte MineKits zunächst die laggs reduzieren und die vorhandenen buggs fixen. Als 2. Schritt brauchen wir einfach eine neue Idee!

**Comment by lukas81298** [comment]
Der 1. ist ja bereits in Arbeit.
Bei dem 2. kannst du dir ja mal Gedanken machen.
