### ISSUE TITLE
Retro KitPvP

### ISSUE THREAD

**Issue by lukas81298** [MineKits/MineKits#319]
Hallo,

ich will euch heute mal eine meiner Meinung nach recht coole Idee vorstellen: RetroPvP. Das ganze würde auf einem externen Server gehosted, aber durch beispielsweise ein Portal mit MineKits verbunden.

Wenn man das erste Mal auf den Server joined, bekommst man Eisenrüstung, ein Eisenschwert und ein volles Inventar Suppen. Durch einen Sponge wird man in eine Arena geboosted, in der man mit anderen PvPen kann. Wenn man einen tötet, erhält man mehr Suppen und Credits. Die Anzahl von beidem hängt von dem Anteil des Schadens ab. Desweiteren gibt es Refill Stationen mit einem Cooldown. 

Shop
Am Spawn gibt es einen Shop, in dem man sich bessere Sachen kaufen kann. Zusätzlich kann man z.B. enchantete Items in einen öffentlichen Shop stellen und für einen eigenen Preis verkaufen (siehe Raid). Am spawn gibt es auch EnderChests in die man Items packen kann.
Es gibt keine Kits!

To-Do Liste:

1.a (ALLE) Meine Ideen konstruktiv bewerten / verbessern. 

1b (ALLE) besserer Name

2 (ALLE) Ideen ggf. ergänzen

3 (BUILDER) Maps bauen

4 (DEV) Plugins entwickeln 

5 (ALLE) Alles austesten. Bugs melden. Balancement.

6 (DEV) Fehler beheben.

7. (Ich) Laggfreies hosting suchen 

8. (ALLE) Promotion

* Aufgabe von Mods, Admins ggf. Buildern
** Aufgabe von Buildern unter Aufsicht von den Admins
*** Aufgabe von den Developern (Deniz, Daniel und mir)

Ich hoffe euch gefällt das Konzept. Bitte befolgt nun Punkt 1. + 2. Auch Kritik am Aufbau sollte ggf.  geäußert werden.

**Comment by HDuck** [comment]
Ich kann mir das schon gut vorstellen, erinnert mich etwas an den aller ersten GHG Server c:
MIr würde das sehr gefallen, besonders ohne Kits und eben richtig Oldschool 

Aber in erster Linie, wäre ich dafür, dass erstmal die Lags bei MineKIts behoben werden, bevor etwas neues angefangen wird, da sehr viele Spieler aufgehört haben zu spielen, wegen diesen starken Lags :/ Egal ob neuer Host oder sonnstwas, da muss irgentwas unternommen werden (falls es nicht schon iwie bestellt wurde)

Zu der To-Do List:

1.a)
Wie gesagt, ich fänd sowas "neues" echt schön, doch vorerst die Lags beheben
Meine Zweifel hätte ich villeicht im bereich User bekommen 

1.b)
RetroPvP hört sich eigentlich gut an, aber da fehlt vlt. das "Mine" im Namen (MIneKits; MIneRaid; MineHG) leider fällt mir da kein Name ein (vlt "MineRetroPvP" ?! "MineVanillaPvP"?!)
2)
Ich hätte noch eine Frage zum Shop:
- Werden die User die Items verkaufen weil sie sie irgentwie gewonnen haben? Oder ist das ein Öffentlicher Shop
- Was werden Ränge bringen? (Mehr Credits?)
- Wird es irgentwas geben, für die SG/Hive Spieler, sprich NoSoup? (Dafür weniger Credits pro kill wennschon) 
- Wirds da auch ein LMS geben? Wenn ja, mit /lmspanel, oder mit Oldschool /lms :3?

5)
Ich würd mich gerne für das Testen bereitgeben c: 

6.2) 
Wenn ich die möglichkeit habe, wäre ich gerne Moderator(+)

**Comment by lukas81298** [comment]
Die Lags sollten durch eine neue Map und ein neues Hostsystem in naher Zukunft behoben sein.
