### ISSUE TITLE
Tipp für /stats

### ISSUE THREAD

**Issue by CraftingExpertDE** [MineKits/MineKits#32]
Du siehst ja die ersten Top-50 User aber was ist wenn du nicht dirn bist und unbedingt wissen willst wie viel noch fehlt bis in die Top-50, dann mach unten rechts in dem Stats-Inventar deinen Rang(z.B. 234. lukas81298, etc..) wäre hilfreich und gut.

**Comment by LabyStudio** [comment]
Finde ich gut!

**Comment by HDuck** [comment]
Wäre geil in welchem Rang man gerade ist! :+1:

**Comment by lukas81298** [comment]
Ist eingebaut
