### ISSUE TITLE
/mine Feature 

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#320]
Hab mir mal paar gedanken gemacht für neues bei MineKits,
dann hab ich diese Idee bekommen ^-^ Hoffe sie gefällt dir
Es ist ein etwas Komplizierteres Feature 
___

**VOR-Information**

Es gibt eine stelle am Spawn (wo andere mit Fly rechten aber nicht hinkommen!!) wo es viele
10x11x10 hohle Bedrockkästen gibt.
Screenshot zur veranschaulichung: http://prntscr.com/7kt6k2 (Graue Blöcke nur zum Abzählen, beim Plugin soll es nicht so werden)
___

**Was ist in den Bedrockkästen?**

Wenn man /Mine eingibt, wird man zu einen der Bedrockkästen teleportert
und diese werden dann aufgefüllt mit Blöcken (Gras, Stein, Erde, Erze), 
aber das soll immer Random sein, also das die Erze sollen nicht immer beim selbem Platz sein.

(Screenshots damit mans vorstellen kann:
Hier von oben: http://prntscr.com/7ktltw
Hier von der Seite (Glass als Wand): http://prntscr.com/7ktm2f

In der 1. Schicht von dem Kasten ist immer Gras
In der 2. Schicht von dem Kasten ist immer Erde
In der 3. Schicht von dem Kasten ist immer Stein
In dem Restlichen Teil ist dann Stein, Kohleerz, Eisenerz, Golderz, Diamanterz, Emeralderz verteilt.
Das soll dan Prozentuall engesetzt werden sprich:
Stein gibts am meisten, 
Kohle gibts als 2. meisten
Eisen gibts als 3. meisten
Gold ist schon etwas Seltener
Diamant ist auch sehr Selten
Emerald soll es nur 1x geben 
___

**Was macht /Mine?**
Wenn man ein "Mine-Ticket" hat, kann man /Mine eingeben.
Und dann wird man zu einem Bedrockkasten teleportiert und man hat eine Goldaxt.

Man kann mit der Goldaxt genau 1 Grassblock abbauen (oder Rechtsklicken) und das hat dann den Effekt wie bei Jackhammer (Es werden alle Blöcke bis nach ganz unten abgebaut, aber nicht so schnell sondern 1 Block pro Sekunde)
Screenshot: http://prntscr.com/7ktpa2

und für den Loot den man macht, bekommt man dann Preise
___

**Was bekommt man für Preise?**
- Stein: 10 Credits 
- Kohle: 25 Credits
- Eisen: 50 Credots
- Gold: 100 Credits
- Diamant: 250 Credits
- Emerald: 1h Emerald Rank bzw. wenn man einen besseren Rang schon hat 500 Credits 
Wenn jemand ein Emerald findet soll auch eine Broadcast kommen:
"&a<Player> found a Emerald in the mine!" 

*Die Credit anzahl bzw. Preise können auch erhöht/erniedrigt werden.* 
*Es können natürlich auch andere belohnungen gesetzt werden - wie du willst*

___
**Wie bekommt man ein Mine-Ticket?**

- Wenn das System eingeführt wird, soll jeder 1 Ticket Gratis bekommen
- Wenn man ein LMS gewinnt (zu dem Natürlichen Pre-Set- Credit Preis noch das dazu)
- Wenn man eine MineHG runde mit mindestens 15 (?) Spielern gewonnen hat
- Wenn man ein Level höher ist (/levels)
- Wenn man 2 Quests schafft
- Jedes 3. Achivment man schafft => 1 Ticket

*Wenn dir da ein Punkt nicht gefällt, einfach nicht machen

___

**Spawn-Item**
Man hat am Spawn ein Papier mit dem Titel "MineTicket" (es soll im Menu sein)
Wenn man das Anklickt öffnet sich der Kommand "/Mine",
sodass das MineTicket - GUI öffnet: http://prntscr.com/7ku7ju

- Das rote Glass ist da, wenn man kein Ticket hat
- Wenn man ein Ticket hat, ist da Papier statt dem Glass (mit dem Tag "You have [X] Tickets]) 
- Die 3 Bücher sind so kleine FAQ's wie das geht:

1. Buch: "Was muss man bei /Mine mache"
2. Buch: "Wie bekommt man ein MineTicket?"
3. Buch: "Was bekommt man für die jeweiligen Erze?"

___

**Zusatz Informationen**

- Wenn man bei der Mine ist, kommt da auch eine kurze erklärung "Du musst einen Block mit deiner Goldaxt abbauen und hoffen, dass du gute Erze findest" oder sowas, damit keine Fragen kommen

- Wenn man 1 Minute lang nichts gemacht hat, wird man einfach zum Spawn Teleportiert (damit da kein Bug auftaucht)

Ein zweifel habe ich aber: Wenn es ein Reload gibt, machts vielleicht was kaputt :s

___

Ich hoffe das ist Umsetzbar und nicht zuu übertrieben, nur ich bin der ansicht, dass MineKits mal was neues braucht c: 
Hoff' auch, dass es dir gefällt 

Im Prinzip ist das so ein Glücksspiel ähnlich wie eine Dojo Chest aber ganz anders

**Comment by lukas81298** [comment]
Hm. Hört sich gut an  Wir müssen dann aber etwas gegen Xrayer machen.

**Comment by HDuck** [comment]
Stimmt, das wollte ich noch ansprechen, hab es aber vergessen ._.

Aber ich glaube das kann man schon lösen, oder?
Bei NoCheatPlus gibts ja glaube auch so eine Protection,
dass einfach alle Erze/Steine durch Bemostes Cobblestone; Obsidian; usw. ersetzt wird ( http://miney.me/i/e26f5e )
Weis nicht, ob das noch in der 1.8 so ist aber naja ._.
Freut mich das es dir gefällt c:

**Comment by HDuck** [comment]
Achja, ich wollte nochwas ersetzen:
Ich fänds langweilig, wenn man nur Credits gewinnen kann (und eine Chance auf Emerald)
Ich fänd noch sowas toll:



- Emerald: 1h Emerald Rank bzw. wenn man einen besseren Rang schon hat 500 Credits Wenn jemand ein Emerald findet soll auch eine Broadcast kommen: "&a found a Emerald in the mine!"

- Diamant: 250 credits, oder eine chance ein weiteres Mixed Kit (3 Slots) für 1 Stunde bekommen 

- Gold: 100 Credits, oder eine Chance einen Exp - Boost zu bekommen
 
- Eisen: 50 Credits, oder eine Chance 

Der rest so wie oben

___

Wenns möglich wäre, dass man ein **Gratis** Casino Ticket bekommt (zum normal Preis dazu)
Aber das "Credit Inset" kommt drauf an, was man bekommt:

- Emerald: 100 Credit Inset 
- Diamant: 50 Credit Inset
- Eisen: 25 Credit Inset


___

Hoff das ist nicht zuu übertrieben oder sowas ._.

Ich dachte mir aber dass es langweilig ist, wenn man nur Credits gewinnen kann ^-^

~Ente

**Comment by EinfachNiggo** [comment]
-Sehr coole Idee! Würde ich feiern.
  - Aber dass man nur einen Block abbaut und dann alles drunter zählt, finde ich etwas langweilig. Vielleicht kann man ja machen, dass man zB nur genau 10 Blöcke abbauen kann. Welche man abbaut bleibt einem selber überlassen. Somit macht das denke mehr Spaß ;P

**Comment by HDuck** [comment]
wäre auch nice c:
nur ich war mir nicht sicher ob man das umsetzen kann ;ü
