### ISSUE TITLE
/Aimtest - feature

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#322]
Hey Lukas ^-^
Hab mir wieder paar gedanken zu Ideen bei MineKits gemacht, damit es was neues gibt =D
Hoffe dir gefällt dieser Vorschlag :D 
___

**Kurzbeschreibung**
Wenn man /aimtest eingibt, wird man zu verschiedenen Übungs-Stationen Teleportiert, um besonders sein Aim zu Üben. Sozusagen auch eine alternative zur Lavachallenge; Clicktest (Statt Soup/Clicken eben Aim).

___

**Was macht /Aimtest?**
- Man wird alle 30 Sekunden in die nächste Übungsstation (Unten sind welche) Teleportiert und da kann man dann üben 
- Wenn man jede Station 1x gemacht hat, wird man wieder zum Spawn teleportiert 

___

**Station 1**
- Bild zum Vorstellen: http://prntscr.com/7lqw8z

- Ziel: Den Villager 1x hitten; dann kommt sofort der neue
- Wenn man innerhalb von [2 ?] Sekunden den Villager nicht getroffen hat, spawnt ein neuer
- Punktsystem: Wenn man den Villager trifft: +1 Punkt; Wenn man ihn nicht trifft bzw. er despawnt so bekommt man kein Punkt. (Damit es sowas wie eine Top liste gibt

*Was hat die Wolle zutun?*
- Der Spieler der das Training macht (also du) steht immer bei der Roten wolle (er kann da nicht weg gehen)
- Bei der gelben Wolle spawnen die Villager

___

**Station 2**
- Bild zum Vorstellen: http://prntscr.com/7lqzzs (Die Arena darf selbstverständlich viel größer sein)

- Ziel: So viele Pilze wie möglich abzubauen
- Die Pilze sollten auch wie bei EarlyHG respawnen
- Punktsystem: Pro Pilz 1 Punkt 

___

**Station 3**
- Bild zum Vorstellen: http://prntscr.com/7lr1zp ; http://prntscr.com/7lr25v

- Ziel: Aus der Kiste die Items rausnehmen (perfekt für Survival Games auch) 
- Immer wenn man ein Item raus nimmt, kommt ein anderes hinzu
- Es dürfen keine Items doppelt in der Kiste sein z.B. 3 Eisenbarren (um bugs zu vermeiden also das Eisen Doppelklicken)
- Punktsystem: Pro Item das rausgenommen wird 1 Punkt

___

**Station 4**
Wenn du noch eine Idee hast, kannst du sie gern machen 

___

**Noch weitere sachen die in meinem Kopf sind:**
- Bei einem Reload könnte das krittisch werden (bsp. man wird nicht aus der Arena teleportiert oder man kann dabei die Items aus der Kiste nehmen) Aber vlt. kannst du da ja irgentwie machen, dass man gekillt wird, bevor ein Reload gemacht wird oder sowas :o

- Man kann das auch mit dem /Challenge-Feature verbinden, falls du das machst ( #288 Kurz: Man muss immer verschiedene Aufgaben machen bsp. Töte diesen Bot; Überlebe 10 sek in der Lava)
Beispiels-Challenge: Sammle innerhalb von 10 Sekunden 20 Pilze; Treffe den Villager innerhalb 10 Sekunden 5 mal; Sammle innerhalb von 10 Sekunden 20 Items aus der Kiste

- Für diesen Test beim Villager kann man auch sehr einfach Hacker fangen und auch beim Pilzeabbauen (Nuker wenn er die Blöcke von hinten trifft) oder auch diese Chest-Loot Hacker (gibts bei Huzuni | bsp. er nimmt alle Items auf einmal weg => Hack)

.

- **WICHTIG** Jeder sollte eine eigene Arena haben, sprich am Spawn wo man nicht Hinfliegen kann, (wie bei /mine) sind von jeder Station ~10 Stück. 
Warum? 
- Bei Station 1: Man kann villeicht den Villager vom anderen Treffen & man kann ihn nicht so leicht detecten) 
- Station 2: Wenn jemand Pilze abbaut, und jemand andere sie aufhebt, wäre es gemein
- Bei Station 3: Falls jemand mit dem "Chest Loot Hack" spielen sollte, wäre es besser, dass jeder Seine eigene Kiste hat. Dann kann man genau sehen, wem diese Kiste gehört.

.

- Bei Station 3 wäre es wichtig, dass es kein Chestrefill gibt

___

Hoffe dir gefällt sowas =D 
Wie gesagt, ich suche eben paar Ideen, damit es was neues auf MineKits gibt :3 

~ Ente

**Comment by LabyStudio** [comment]
Done
