### ISSUE TITLE
6 (kleine) Bugs + 1 Wunsch

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#323]
HIer sind 6 kleine Bugs,
die standen zwar schon im Report Chat, aber ich glaub so ist es (für dich) Übersichtlicher 

___

1. Bei einem Globalmute können Mods nicht in den Chat schreiben.
2. Besonders an Laby: Wurde der Bug gefixt, dass die Rüsstung ausgezogen wird, wenn man jemanden am Spawn hittet (/cosmetic) ? 
Also wurde er gefixt und man muss nurnoch reloaden? Oder muss das noch gemacht werden? 
3. Wenn ich einen für 5 Minuten Mute, steht bei meiner sicht "Du hast ihn 5 Min. gemuted" bei dem anderen steht, dass er 45 Jahre gemuted ist. (Hab angst leute zu Muten, daher sag bitte bescheid, wenn das gefixt ist)
4. Bei /menu steht immernoch "Boots" statt "Cosmetic"
5. Besonders an DJD glaub ich: Das Feast spawnt nicht ( http://prntscr.com/7m4gxc )
6. Manchmal werden User einfach so random gekickt. Hier die Kickreason: http://prntscr.com/7m4jhw

___

Der "Wunsch":
Könntest du so eine TOP 3 Statue ( http://prntscr.com/7m96qp ) auch machen, für die Daily TOP 3 Spieler? Also die 3 besten Spieler von "/stats => Daily "
Das würd ein richtig guten Anreiz geben zu spielen :) 
Wäre echt nice wenn du das machst 

___

~Ende Ente

**Comment by lukas81298** [comment]
6. Müsste gefixed sein

**Comment by lukas81298** [comment]
6. auch

**Comment by HDuck** [comment]
Ok

Achja noch ein weiterer Bug, wollte kein Extra teil dafür öffnen:

7. Bei den Usern kommen immernoch die "You don't have permissions for this area" meldungen, kannst du dass ausschalten?

**Comment by lukas81298** [comment]
Die Nachricht sollte auf dem neuen host dann auch weg sein.

**Comment by lukas81298** [comment]
Sollte inzwischen alles behoben sein, auch wenn noch nicht alles live ist.
