### ISSUE TITLE
1v1 Bugs: TP-Schneebälle werfen + Invis Gegner

### ISSUE THREAD

**Issue by lejaden** [MineKits/MineKits#324]
Wenn man jemanden herausfordert, der jenige animmt und kurz davor, sneakt und sich irgendwohin tpt, wird man nicht in die Arena teleportiert! Außerdem ist man in der 1v1 Arena ab und zu invis für den Gegner!

**Comment by HDuck** [comment]
Bug 1 (mit dem Schneeball Teleport) kann man so fixen:
Man macht einfach eine "XYZ" Region, und in der kann man einfach keine TP-Schneebälle schießen (wie bei der NoKit region keine kits gehen) bzw. dass es einfach in der region 1v1 nicht geht

Bug 2: 
Den gibts schon seit Anfang des 1v1 System's - kp wie man das Fixen soll ^^ 
Vielleicht wird das ja gefixt, wenn Lukas das neue 1v1 System anfängt (er wollte ein neues - einfacheres machen)

**Comment by lukas81298** [comment]
Sollte mit dem neuen 1v1 System behoben sein.
