### ISSUE TITLE
Wenn man Feast verlässt buggt man [Wichtig]

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#325]
Bug von /form:

Wenn man bei /warp Feast zu dem Sand Biom geht (geht besimmt auch auf den anderen seiten) im Gamemode 0,
so buggt man einfach, und kann sich nicht bewegen.

Dieser Ort: http://prntscr.com/7nkpwg

bzw. das geht auch bei EarlyHG auch..
also überall beim Border, wo man normalerweise weg gepusht wird.

Denke da fehlt Laby's Plugin

**Comment by lukas81298** [comment]
Ist bereits bekannt und sollte an Labys plugin liege. Er hat gemacht, dass man sich im hell biom nicht bewegen kann.
