### ISSUE TITLE
/kitmixing | Man kann kein Kit removen

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#326]
Man kann bei /kitmixing sein Kit nicht removen. Beispielsweise Snail weg machen und dafür Viper rein.

Also wenn man dann auf das Snail Kit (das man weg haben will; [Beispiel]) Shift+Rechtsklickt, wird es nicht entfehrnt, sondern es bleibt einfach

=> Man kann sein MixedKit nicht editieren 

Bitte fixen du Illuminati :*  :D

**Comment by HDuck** [comment]
Ich glaube du hattest mal vor paar (3) Wochen gemeint, dass es iwie nicht geht,

wie wär so ein Item bei /kitmixing, dass einfach alle Kits bei einem MixedKit removed? 
Vielleicht würde irgentwie das klappen ..

___


Manche Spieler haben halt das Problem,
dass sie 3 Slots haben, mit Folgenden Kits:

1. 5 Sterne Kit
2. 4 Sterne Kit
3. 1 Stern Kit

und sie wollen 2 5-Sterne Kits einfügen => Geht nicht, da sie den 3. Slot nicht resetten können

(nur ein beispiel) 


~Ente

**Comment by HDuck** [comment]
vlt. hilft das irgentwie weiter:

Wenn man alle Kits von einem MixedKit Shift+Clickt,
danach sofort Relogt, sind die Kits von dem MixedKit entfernt

**Comment by lukas81298** [comment]
Es gibt jetzt einen Button, mit dem man alle Kits entfernen kann.
