### ISSUE TITLE
Items in den Feast-Kisten

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#33]
Hey Lukas,
beim Feast sind ja rellativ viele Pfeile, aber es gibt nur ein Kit welchem es was Bringt (Archer)

=>
Wie wäre es, wenn es noch ein Bogen in den Feastkisten gibt?
Der Bogen sollte aber wenig Durability haben wegen Enchantig

**Comment by lukas81298** [comment]
lässt sich machen

**Comment by lukas81298** [comment]
ist umgesetzt
