### ISSUE TITLE
Kit Mixing OP combinationen + BUG 

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#332]
Hab paar Mixing Bugs gesucht,
und hab die noch rausgefunden:

- **Hulk + Airstrike**
Man Hulkt einen, und dann Airstrike Item rechtsklicken => Man wird nicht hoch teleportiert aber man hat die Platformaus Glass ist einfach unten

- **Airstirke + Endermage**
Mit Airstrike nach oben gehen, und dann einen Glass block schlagen => Er wird hoch teleportiert & stierbt an fallschaden.

- **Ninja + Stomper**
Auf dem Tower: Man fightet ganz normal, dann springt man Runter, wenn man dann im Flug ca. 20 Blöcke unten ist, Sneaken und er bekommt viel Stomp schaden => sehr op

**ZU DEN BUGS:**

- Wenn jemand Combatloggt, steht zwar im Chat, dass er Combatlogged ist, aber man bekommt den Kill für ihn nicht. 

- Bei /menu steht statt "Ranks" immernoch "Levels" [Nametag Item]

**Comment by lukas81298** [comment]
Gefixed
