### ISSUE TITLE
Viele verschiedene Ideen & Wünsche!

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#333]
Ich hatte mir in den letzten Wochen gedanken gemacht,
was man noch verbessern / neumachen / fixen könnte,
hab mir extra Notizen gemacht ^^
(Die Bugs sind bei anderen GitHub-Issue Seiten)
Ich fang einfach mal an, hoffe du kannst irgentwann davon was umsetzen
___

~~Beim Kit Mixing: Dem Kit MLG weniger Sterne (von 3 auf 1), da es ja nicht wirklich op ist~~
~~Beim Kit Mixing: Dem Kit Phantom mehr sterne (von 2 auf 3)~~
~~Kit MLG Upgrade: "Man kann maximal 7,5 Herzen Fallschaden bekommen" (Wenn es einem nicht gefällt muss er ja nicht Upgraden)~~
~~Wenn man auf Cobweb springt kein Fallschaden. 
Seit der 1.8 ist es so, dass man nur Überlebt, wenn man Leertaste gedrückt hält, und auf ein Cobweb springt.. kannst du das machen, dass man immer überlebt?~~

Jetzt zu den Wahrscheinlich aufwendigeren:

~~**/bugtest oder /testmode (NUR FÜR STAFF)**
Wenn man den Command eingibt, werden die Stats von der Person nicht verändert, wenn er Stierbt/Tötet.~~
~~Damit es nicht zu Abuse kommt: Die Stats sollen wirklich garnicht verändert werden, wenn man jemanden Tötet, wird es auch nicht zu den Stats gezählt.
Wozu der Command?~~ 
~~Wenn man gerade dabei ist paar Bugs zu finden, ist es echt sehr nervig, wenn die Stats so runter gehen, so geht (mir) der Spielspaß etwas verloren.~~
Beispiel: Jemand sagt, wenn man Das und Das macht, viel zu OP ist, oder wenn jemand einen Bug hat und man Testet ihn, ob er wirklich geht und davon bekommt man viele Tode dazu gerechnet~~ => Jetzt gibt es /testmode!

B. **/spend Command** (viele User haben sich sowas gewünscht) (oder anders vlt. /sponsor)

Kurz: Spendier jemand anderen ein Kit, aber es wird dir in Raten zurückgezahlt.

Gib /spend <Name> <Kit> ein, so bekommt der andere die Anfrage,
ob er das Kit annehmen will oder nicht.
Falls er das Kit schon hat, erscheint bei dir, dass er das Kit schon hat und es nicht geht

Wenn er das Kit angenommen hat, zahlt er den Preis zurück, aber eben nicht sofort, sondern Nach und nach.
Pro kill, den die Person dann macht, bekommt der "Spender" die hälfte vom Geld vom Kill (auch wenn er offline ist) 

C. **/bounty neu machen** 
Viele spieler haben schon gesagt, dass Bounty sinnlos ist, (ich weiss, Laby meint das soll auch für LMS'e Dienen, aber ist jetzt nicht wirklich besonders)
Ich habe mir dazu was neues ausgedacht:

- Man kann nur der Person ein Bounty geben, die dich zuletzt gekillt hat und man muss mindestens ~400 Creidts zahlen. 
- Wenn die Person, die unter Bounty steht reloggt, soll er immernoch unter Bounty stehen (Oder die Person bekommt sein Geld zurück)
- "/Bounty Top", da sieht man alle derzeit lebenden Bounty leute, und wie viel man für sie bekommt (sortiert nach der Anzahl, wie viel Geld man bekommt)  
- Alle ~7 Minuten eine Broadcast, falls jemand noch unter Bounty stehen sollte

___

~ Ente

**Comment by lukas81298** [comment]
Punkt 1-3 werde ich morgen machen, das wird aber erst mit dem neuen 1v1 system online gehen.
Punkt 4 muss ich mal ausprobieren, sollte aber auch gehen. Schein ja ein mc bug zu sein.
Das mit der Kit sponsoring ist zwar kompliziert, lässt sich aber umsetzten. Nur das mit dem zurückzahlen wird schwer. Wenn könnte man es nur so machen, dass man einen Anteil der Credits bekommt.

**Comment by HDuck** [comment]
Okey Nice :)
Außerdem wäre auch Kit Priest etwas zu hoch eingestuft beim Kit Mixng:
Wie wäre es von 5 Sternen auf 3 oder 4?
Immerhin hat das jetzt auch nicht die OP Fähigkeit

**Comment by lukas81298** [comment]
Punkt 1-4 sind abgearbeitet.

**Comment by lukas81298** [comment]
Lol Issue #333 @HDuck

**Comment by HDuck** [comment]
Lolo hhahahah

**Comment by LabyStudio** [comment]
Bounty entfernt.
