### ISSUE TITLE
1v1 Bug: Wenn man verliert, verliert man das DiamantSchwert-Item

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#337]
Bug von /form:

Wenn man ein 1v1 Verliert,
wird man zwar automatisch zur Lobby Teleportiert und man bekommt die 1v1 Items,
außer das Diamant-Schwert ("1v1 Tool") ansonnsten sind die anderen 2 Items da.

**Comment by lukas81298** [comment]
Jetzt ist es ein Goldschwert

**Comment by HDuck** [comment]
Wurde nicht gefixt.
Nach dem Tod hat man zwar jetzt ein Schwert,
aber ein Steinschwert (kein Dia bzw Gold Schwert.)

**Comment by lukas81298** [comment]
Man kann es aber benutzen.

**Comment by HDuck** [comment]
Nein, geht nicht.
Man muss von 1v1 zum Spawn und wieder zurück,
damit es wieder geht
