### ISSUE TITLE
Gladiator verbessern

### ISSUE THREAD

**Issue by LabyStudio** [MineKits/MineKits#34]
Der Gladiator, der einen ,,gladiatort'' hat meistens immer mehr Supppen, undso ist es fast unmöglich, dass man ihn killt. Also schlage ich vor, dass wenn man einen Spieler ,,gladiatort'' nur ein volles Inventory suppen hat.
~Schweini

**Comment by HDuck** [comment]
Wie wäre es dass einfach genau beide wie du gesagt hast Full Inv Suppen haben, UND genau 16 Rote Pilze 16 Braune Pilte und 16 Bowls hat,
damit man auch chancen hat, falls man am anfang gecomboed wurde oder so:)

**Comment by lukas81298** [comment]
Das ganze würde aber dazu führen, dass man einfach einen gladiatort wenn man selbst keine Suppen mehr hat und erneut neue Suppen erhält.

**Comment by HDuck** [comment]
Stimmt.
Wäre ein Trick um sich einfach Suppen zu erneuern

Meinermeindung nicht so pille
