### ISSUE TITLE
Sofort wieder Gladiatoren nach einem 120 sek. Kampf

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#344]
Es ist zwar kein Bug, trotzdem wünschen sich paar (ua. ich) 

Wenn man im Gladiator Kasten kämpft, löst sich dieser Kasten nach 120 Sekunden auf, wenn der Kampf zu lange war,
aber man kann gleich nach dem Kampf SOFORT wieder Gladiatoren,
was sehr nervig ist. 
( http://prntscr.com/7rdw91 )

Könnte man es nicht so machen, dass der Cooldown erst gezählt wird, wenn der Kampf vorbei ist?

**Comment by lukas81298** [comment]
Ist jetzt so.
