### ISSUE TITLE
Kit Mixing OP 

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#347]
Mich haben paar angeschrieben,
dass **Poseidon + Fisherman** zu OP ist

Stärke 1 und man zieht den gegner immer an sich

**Comment by lukas81298** [comment]
Langsam blockieren wir echt alle combos :D Ich mach gleich noch.

**Comment by HDuck** [comment]
Ja haha :D
Aber mich haben schon einige angeschrieben, dass das MixedKit von der person zuu op ist, daswegen ^.^
