### ISSUE TITLE
Bugs von /form

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#348]
Hier die derzeitigen Bugs von /form 

1. Bei /shop kann man sein Schwert nicht Umbenennen  (noch nicht ganz fertig)
2. Wenn man Fire Resistance hat, bekommt man trotzdem schaden von Kit Magma (Lavaeimer Kit=
3. Nach einem 1v1 hat man ein Steinschwert statt einem Goldschwert (klappt aber trotzdem) 
4. Die Preise von Viper/Snail sind komisch:
 Viper: Raiting: 5 Sterne | Kostet 1500
 Snail: Raiting: 4 Sterne | Kostet 2000 
(vlt. beide Gleich stellen? oder Viper auf 2000 coins setzen)
5. Wunsch von User: Eine "Tafel", wo steht, welche Mods / features erlaubt sind.
Also am spawn bei /warp rules einfach eine Tafel,
wo steht, ob (in seinem Fall) Better Sprint erlaubt ist.
(Kann man von mir aus bei /faq hinzufügen, oder erst beim neuen Spawn) 
6. Thor ist anscheinend zu OP 
Ich habs getestet, und es ist wirklich zuu op.
Wenn jemand sich gerade nicht bewegt, und man unter ihm ein Blitz einschlägt,
schauen seine Herzen so aus:
 Anfangs 10
 dann 7
 dann 4
 dann TOT
Also stierbt man schon durch einen guten Treffer.
(✓)
Kannst du das so machen, dass nur 1 Blitz kommt, welcher ~3 Herzen schaden macht im radius von ~ 2 Blöcken? 

**UPDATE**
Es sind jetzt noch weitere Bugs gemeldet, ich schreib sie einfach hier rein:

7. Kit Fisherman: Wenn man sich selbst hookt, und dann vom Tower spring und sich dann zu sich selbst zieht, bekommt man kein Fallschaden.
8. Iron spieler können sich nicht zu Default taggen.
9. Es ist nicht direkt ein Bug, doch grappler können sich an Fly-Personen hooken.  (✓)

~~ENTE

**Comment by LabyStudio** [comment]
Thor fixed
