### ISSUE TITLE
MineHG Startzeit unsyncron mit MineKits-Info-Broadcast

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#349]
Ein etwas wichtigerer und nerfigerer Bug:

Die MineHG-Startzeit ist nicht syncron mit dem Informations Broadcast bei MineKits.

Beispiel:
Auf MineKits steht als Broadcast:

MineHG starts in 45 sec. [Klick here to join]
MineHG starts in 30 sec. [Klick here to join]
...

Wenn man dann auf MineHG ist, steht da, dass es erst nach 6 Minuten startet. 

Die Broadcast bei MineKits kommen also immer zu früh

**Comment by lukas81298** [comment]
Ist mir bewusst..Ich muss die Zeit beider Server noch mal synchronisieren

**Comment by HDuck** [comment]
https://github.com/MineKits/MineKits/issues/361
Hab da jetzt alle MineHG bezogenen Bugs zusammengefasst 
// Ich close dann dashier ^-^
