### ISSUE TITLE
Kit: Anti

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#351]
**Kit: Anti** (oder "Antikit" oder was anderes)

___

**Kurzbeschreibung:** Immun gegen alle 5-Sterne Kits (von dem Kit-Raiting)

___

**Liste der 5 Sterne Kits und wie es gegen Kit Anti sein soll:**
- Anchor: Man kann ihm Knockback geben und er dir
- Gladiator: Er kann dich nicht Gladiatoren
- Grappler: Er kann sich nicht an dich Hooken
- Kangaroo: Er kann im Radius von 3 Blöcken bei dir nicht Kangaroon
- Priest: Egal wie oft er dich hittet, er wird nicht geheilt
- Pyro: Er kann dich nicht anzünden
- Snake: Er kann im Radius von 3 Blöcken nicht weg mit dem Kit
- Viper: Er kann dich nicht vergiften
- Stomper: Er kann dir kein Stomp-Schaden geben

___ 

Ich hoffe du verstehst, was das Kit kann.. 

So ein Kit haben sich sehr sehr viele Spieler gewünscht (besonders Anti-Stomper/Anchor) 
Wäre also sehr gut, wenn du das machen könntest

**Comment by lukas81298** [comment]
Hört sich gut an. Ich habe jetzt alles außer Anchor, Snake und Kangaroo gemacht. Die letzten beiden sind hinsichtlich Performance problematisch. Bei Anchor wird es etwas komplizierter, aber ich werde es wohl hinbekommen ;)
Ich habe es jetzt so gemacht, dass sich das Kit nicht mixen lässt.

**Comment by HDuck** [comment]
Freut mich, dass du das Kit machst c: :+1: 
Die wichtigsten wären Stomper; Anchor; Gladiator ^-^

**Comment by lukas81298** [comment]
Ok, Anchor sollte soweit auch klappen :D

**Comment by HDuck** [comment]
Echt nice, dass du das Kit gemacht hast!

Aber bei der Kitbeschreibung (http://prntscr.com/80mzxf) sollte lieber stehen, dass es gegen einige 5-Sterne-Kit* geht.
Mich fragen jetzt schon Spieler, ob das auch gegen Kit Snail/Fisherman.. usw. klappt ^-^
