### ISSUE TITLE
Achivment Fehler

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#352]
Achivment **Naked** *(jemanden ohne Rüsstung bei Feast töten)* geht nicht
Achivment **Spilerman** *(Cobweb setzen)* klappt nicht
Achivment **Noob** *(5mal hintereinander sterben ohne ein Kill zu machen)* geht nicht

Achivment **Sniper** *(jemanden mit dem Bogen treffen; 50Blöcke entfehrnung)* ist etwas falsch:
=> Wenn man selbst vom Pfeil getroffen wird bekommt man das Achivment

___

Weil die Achivment's nicht gehen, wollte ich testen, ob die anderen funktionieren...
kannst du mir sagen wie man die Folgenden Achivments bekommt (geht auch per Skype)?: 

- Buisnessman
- Dueller
- Murder
- Ported
- No Escape
- Survived
- Tryharder
- Relaxed

~Ente

**Comment by lukas81298** [comment]
die achievements sollten jetzt gefixed sein!
