### ISSUE TITLE
PotPvP warp/Kit

### ISSUE THREAD

**Issue by xBlackJack** [MineKits/MineKits#356]
Wie schon gesagt fände ich das gut, wenn es ein kit mit pots geben würde ( http://puu.sh/jvkjA/321c258320.png) oder ein warp. 
Das wollen viele.

**Comment by HDuck** [comment]
Wir hatten ja schon damals (ca. ~1 Jahr) ein PotPvP Plugin/Warp.
Wenn Lukas das noch hat können wir es ja einbauen,
wenn es den leuten gefällt bleibt das einfach drinnen :D 

Mir würde PotPvP gefallen :+1:

**Comment by lukas81298** [comment]
Wenn es den Leuten gefallen hätte, wäre es noch drin. Wenn ich Zeit hab, mach Ichs vllt. mal neu.
