### ISSUE TITLE
Fly modus für Premium ändern

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#359]
Hier das Original von /form: http://prntscr.com/82x34g

Kurz zusammengefasst:

Da manche mit Gold mit dem Fly-Rang abusen, während kein Mod online ist oder Spieler Irritieren, hat er das Vorgeschlagen:

1. Im Flymodus dürfen Premium-Spieler keine Kisten öffnen (Mods sollen das schon machen können, nicht das da jetzt der fehler auftaucht^^)
2. Im Flymodus dürfen Premium-Spieler keine Items aufsammeln
3. Im Flymodus können Premium-Spieler nicht vom Grappler gehookt werden
4. Die Spieler sind Unsichtbar im FlyModus (ich fänd das jetzt aber nicht soo gut, vlt. wird das iwie abused)

**Comment by lukas81298** [comment]
1 - 3 ist gefixed.
