### ISSUE TITLE
 Automatisches Kit

### ISSUE THREAD

**Issue by LabyStudio** [MineKits/MineKits#36]
Wenn man jetzt zu EarlyHG oder Feast von Spawn aus geht und man kein Kit ausgewählt hat, hat man auch kein Kit. Wie wäre es, wenn wir es so machen, dass wenn man vom Spawn aus zu EarlyHG läuft und man kein Kit hat, das normale Early Kit bekommt& das selbe bei Feast, nur mit dem normalen PvP Kit.
~Schweini

**Comment by lukas81298** [comment]
Implementiert
