### ISSUE TITLE
Verschiedene Ideen/Wünsche

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#360]
Ich habe hier noch weitere (keine) Ideen/Wünsche

1. Wenn jemand per MSG Spamt, soll das auch angezeigt werden für Mods (Wie wenn man per MSG beleidigt)
2. Mir ist aufgefallen, dass das Plugin noch drinnen ist, wenn man ein Ei wirft, kommen Blitze.. das kann man doch in die Feastkisten einfügen, oder? (✓)
3. Wenn man /achivments eingibt, sollten die Achivments angezeigt werden  (✓)
4. Bei /menu "/help" und vlt. "/shop" einfügen (✓)
5. Bei den TOP 3 Spielern sollen auch die Namen auf dem Schild stehen (für 1.7 Spieler und manchmal werden die Statuen nicht für die 1.8 angezeigt) Also da einfach den Namen auf's Schild http://prntscr.com/82xaz7 (✓)
6. Eine Daily TOP 3 Statue (also das selbe wie das jetzige, nur eben für die Täglichen TOP 3 Spieler)
7. Bei /cosmetic soll man ein Outfit Speichern können, damit man das nicht immer neu machen muss (Wäre MEGA wenn das gemacht wird!)
8. Man soll nur Spieler Gladiatoren können, die dich in den letzten ~7 Sekunden geschlagen haben (Keine RAGE-Spieler mehr für Killsteals)
9. Eine "nofly-<name>" region wo man nicht als Premium fliegen kann (gut für LMS-Bereiche)
(✓)

**Comment by lukas81298** [comment]
Ich hab ein ✓ hinter alle Punkte gesetzt, um die ich mich gekümmert habe.
