### ISSUE TITLE
Feature Ideen

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#362]
Ich habe mir paar Features ausgedacht (waren schon seit paar Monaten in einer .txt Datei) Ich schreib sie mal auf, vlt. gefallen sie dir ja ^-^

___

**Snowball Shop**

**Kurzbeschreibung:** 
Man soll die Farbe von dem Schneeball am Spawn ändern können (http://prntscr.com/82xj7j)

**GUI's:**

- Wenn man z.B "/Snowball" bzw. im Menu drauf drückt: http://prntscr.com/82xn6z
- Wenn man auf den Smaragt geht: http://prntscr.com/82xnem
- Wenn man auf die Wolle geht: http://prntscr.com/82xnms
- Wenn man auf den Clayblock geht: http://prntscr.com/82xnqh
- Wenn man auf das Glass geht: http://prntscr.com/82xntg

**Infos:**
- Ein Schneeball kostet ca. ~300 (musst du wissen)
- Wenn man einen Schneeball selected hat, soll es nach einem Relog immernoch so bleiben

Ich fänd das richtig richtig Cool! Ich hoffe das ist möglich :3 
Würde mich freuen c: 

___

**Daily Gift**
(Hab mich etwas von Subway Surfers inspirieren lassen xD)

**Kurzbeschreibung**
vlt. kennst du das von Subwaysurfers: http://prntscr.com/82xph3 
Jeden Tag, wenn man zum 1. mal Joint, öffnet sich eine GUI wo man dann jeden Tag ein kleines Geschenk bekommt und beim 5. Tag bekommt man ein besonderes Geschenk

**GUI**
1. Tag wo man Joint: http://prntscr.com/82xt8d http://prntscr.com/82xu2q
2. Tag http://prntscr.com/82xtfj
3. Tag http://prntscr.com/82xtjg
4. Tag http://prntscr.com/82xtn6
5. Tag http://prntscr.com/82xtxj

**Beschreibung**

- Wenn man auf die Hellgrüne Wolle drückt, bekommt man sein Daily Gift (Geschenke stehn unten)
- Wenn man versucht auf die Graue Wolle/Enderchest zu Klicken, kommt der Soundeffekt: "snare.ogg" (einfach ein Soundeffekt, dass man weiß, dass es nicht geht) 
- Im Chat steht, was man gewonnen hat (bsp: Du hast 30 Coins bekommen)

**Geschenk Beispiele**
*(Es soll nicht immer das selbe sein, z.B Tag 1 immer Coins, Tag 2 immer Xp...)*

- Coins 
- XP
- XP boost 
- Casino Gratis Ticket (Inset 50)
- Da steht, wie man ein Achivment bekommt, welches man noch nicht hat
- **MEHR fallen mir gerade nicht ein, wäre super, wenn du noch welche Hinschreibst/selbst ausdenkst**

Am 5. Tag (Special Gift):
- Random Snowball 
- Ein Casino Gratis Ticket (inset 500) 
- Jump & Run Ticket (siehe unten)
- Gratis Kitupgrade auf ein Random Kit 
- Starker XP Boost
- Ein Random Gratis Kit (geht nicht bei Premium Usern) (Nur 1x möglich!!)
- Ein Random Kit wird geupgradet (nur, wenn man noch nicht alle Upgrades hat)
- **Mehr fallen mir nicht ein aber bei Ideen kannst du ja welche Hinschreiben**

Ich weiß nicht, ob ich das genau genug erklärt habe, doch ich denke man versteht das Prinzip
Ist jetzt nicht die beste idee, aber vlt. gefällt sie dir - war eine Spontane Idee

___

**Jump and Run Ticket**

**Kurzbeschreibung:**
Man kann sich ein Jump and Run Ticket verdienen, wenn man dieses Jump and Run hinbekommt, bekommt man ein Geschenk. Das Jump and Run  wird jede 2 Wochen geändert

**Wie verdient man sich eins?**

- Daily Gift Tag 5
- MineHG gewinnen
- Die 3 Daily Quests machen
- UpRanken

**Was kann man bekommen wenn man das J&R schafft?**
- Random Snowball
- Casino Gratis Ticket (500 inset) 
- XP Boost
- Coins

**Wichtige sachen dazu:**

- Da soll man kein Kit benutzen können
- Da soll man kein Fly benutzen können

Ich denke das Prinzip erklärt sich von selbst 
=> Jump and Run schaffen => man bekommt sein Geschenk  

___

Bin etwas Müde, falls du was nicht verstanden hast, kann ich es nochmal erklären xD
(vlt. sind da GrammatikFehler oder sowas ^^)

Ich hoffe echt, dass du das mit dem Schneeball-Shop machst, das ist das beste von allen! :) 

~Ente

**Comment by EinfachNiggo** [comment]
- Feature 1: Sehr, sehr cool! Macht das bitte! Vielleicht kann man ja auch noch den Sound ändern (> kaufbar).
- Feature 2: Noch cooler, als cool! Das muss wirklich gemacht werden :D 
- Feature 3: Finde ich echt unnötig.

**Comment by HDuck** [comment]
danke danke! :D 

hab mir später auch gedacht das dieses Jump&Run voll unnötig ist xD

**Comment by EinfachNiggo** [comment]
@Lukas darf das hier nicht vergessen! :P

**Comment by EinfachNiggo** [comment]
Ups, ich meinte @Lukas82198

**Comment by EinfachNiggo** [comment]
.. Ne jetzt kb mehr

**Comment by lukas81298** [comment]
Ich glaube, dass wir die schneebälle komplett entfernen, da es ja das boots system gibt.
