### ISSUE TITLE
1v1 Kit Bug

### ISSUE THREAD

**Issue by xBlackJack** [MineKits/MineKits#364]
Wenn man bei 1v1 jemand anfragt und "Present III" auswählt, sollte man (wie beschrieben http://puu.sh/jDwMg/e119ba75d5.png ) 32x Pilze bekommen. 
Man bekommt aber im 1v1 64x. ( http://puu.sh/jDwQ6/8c8fbe977d.jpg )

~xBlackJack

**Comment by lukas81298** [comment]
Lässt sich schnell beheben. Vermutlich hab ich einen falschen Index vergeben.

**Comment by lukas81298** [comment]
Sollte nun auch gefixed sein. Ich hab es noch nicht live geschaltet!
