### ISSUE TITLE
Combatlog: Man bekommt den Kill nicht

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#365]
(Ist schon sehr lange so, aber immernoch nicht behoben)
Wenn jemand Combatlogt, steht zwar im Chat, dass er Combatlogged ist,
aber man bekommt nicht den Kill.

**Comment by lukas81298** [comment]
Das sollte eigentlich invischen gehen :O Bist Du Dir sicher?

**Comment by HDuck** [comment]
Jup, das wird immer öfter in Form's geschrieben (heute auch schon)
Aber ich teste es nochmal

**Comment by lukas81298** [comment]
sollte auch gefixed sein
