### ISSUE TITLE
KIt idee

### ISSUE THREAD

**Issue by xBlackJack** [MineKits/MineKits#366]
Ein Kit wo man ganz normal soups hat, nur als kititem eine angel. 
Da es viele Spieler gibt die als abewechslung mal soup spielen anstatt sg. 
Das würde ich auch als 1v1 Kit vorschlagen.

~xBlackJack

**Comment by lukas81298** [comment]
Also das normale PvP Kit mit einer Angel? Dann würde ich vorschlagen, dass die Angel x (upgradeable) Durability Schaden hat und sich wieder auflädt, wenn man einen Spieler schlägt. Ähnlich wie bei Jetpack. Hat jemand eine Idee für den Namen des Kits.

**Comment by HDuck** [comment]
Namens Vorschläge

- Kit Rod
- Kit RodPvP
- Kit Survivor [Mein Favorit]
- Kit SG

**Comment by EinfachNiggo** [comment]
Close please.
