### ISSUE TITLE
Kitidee

### ISSUE THREAD

**Issue by xBlackJack** [MineKits/MineKits#369]
http://puu.sh/jDJHL/bb113dd9db.png

**Comment by lukas81298** [comment]
Sagt mir nicht wirklich zu. Andere Meinungen?

**Comment by HDuck** [comment]
Naja,
ist ja eigentlich nur "Ninja Teleportation" + "Eine Wolke aus Partikeln die 4,5 Herzen Schaden macht".

Ich würds wennschon machen, dass man jemanden Rechtsklickt und man dann hinter einem TP't wird - also ohne sich aufzuladen

Wäre eigentlich garnicht so schlecht
