### ISSUE TITLE
Daily Quests [1v1 Quest] bug

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#370]
Herausforderung bei Daily Quest: "Gewinne 15 1v1's"

Wenn man jemanden beim 1v1 killt, zeigt es trotzdem "Du hast 0/15 1v1's gewonnen" an.

**Comment by lukas81298** [comment]
Ich schau morgen mal.

**Comment by lukas81298** [comment]
Ok, sollte gefixed sein.Kann noch etwas dauern, bis wir es live schalten!
