### ISSUE TITLE
1v1 Bug: Wenn man beim Countdown /suicide eingibt

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#372]
1v1 Bug:

Wenn man beim Countdown bei 1v1 /suicide eingibt,
bekommt man einen Slowness effekt (der wird nicht beim Inventory angezeigt)
Wenn man diesen Effekt hat, kann man nicht Sprinten/ Laufen, nur Springen.

Wenn man dann /suicide eingibt, wird er immernoch nicht weggenommen.
Erst wenn man noch ein 1v1 macht verschwindet dieser effekt.

**How 2 fix**

In den ersten 3 Sekunden (oder wie lange der cooldown ist) kann man nicht /suicide eingeben (beim 1v1)

**Comment by lukas81298** [comment]
gefixed
