### ISSUE TITLE
Flashing Egg Textur in den Kisten kaputt?

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#373]
Bei mir sind die "Flashing Egg"'s in den Kisten verbuggt (die Textur)
http://prntscr.com/88uq55
Die ID ist 344 (Normale Ei Textur)

Könnte auch sein, dass es nur bei mir ist (MInecrat 1.8) (Am TexturePack liegt es nicht, habe es mit Default getestet)

**Comment by lukas81298** [comment]
Ok, hab es gefixed. Es war 344:1 anstatt 344:0 :D
