### ISSUE TITLE
Kit: Timebomb

### ISSUE THREAD

**Issue by xBlackJack** [MineKits/MineKits#375]
If the timebomber rightclicks his fire-charge to another player, a fire-charge will be placed randomly in the enemys inventory. After 10 seconds the timebomb will explode and deals 5 hearts of damage. This Kit has an cooldown of 25 seconds.
This Kit can be upgrade:
Level1:
15 Seconds cooldown
Level 2:
The Timebomv explodes after 7,5 seconds.

**Comment by EinfachNiggo** [comment]
Good idea.

**Comment by lukas81298** [comment]
This would be just used to troll players and many of the would be annoyed.
