### ISSUE TITLE
/FAQ Bug

### ISSUE THREAD

**Issue by xBlackJack** [MineKits/MineKits#376]
Bei FAQ - reports 
Eine dieser Infos kann man nicht lesen, da sie über den Bildschirm geht. Ich konnte diese Info nur lesen, da ich 2 Bildschirme habe und es über diese gezogen habe. Diese Info ist auch falsch, das muss noch korrigiert werden. ^^ ( /report player )

**Comment by lukas81298** [comment]
Welche genau?

**Comment by xBlackJack** [comment]
Da wo steht das wenn man einen Hacker sieht, dass man /report machen muss.
Einfach eben mal überarbeiten.
Am 29.08.2015 00:45 schrieb "Lukas" <notifications@github.com>:

**Comment by lukas81298** [comment]
Habs geändert. Wird nach einem Reload aktiv!
