### ISSUE TITLE
Survival Games Plugin +Features

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#38]
Wie wäre es mit einem Survival Games Plugin? 
Wir hatten die Idee ja schonmal früher, 
doch sie wurde nicht umgesetzt..

Jedenfalls wäre das sehr effectiv, wenn auch NoSoup KitPvP kommt, denn so können wir auch Spieler anlocken, welche nicht SouPvP können (GommeSpieler etc.)

Das system sollte eigentlich genau so wie jedes andere Survival Games Plugin aufgebaut sein,
kann aber auch andere Features besitzen, z.B auch so Items wie bei den Feast Kisten (launcher Item) oder auch so Kit Items die man benutzen kann. 
Beispiele für Kit Items: Die Items sollten alle immer nur 1x benutzbar sein
- Launcher Slimeball
- Gladiator Item
- Aura Item
- Levitator Item
- Ninja Blindness Kugel
etc. Ich denke du/ihr wisst was ich meine.

Hoffe das wäre Umsetzbar bzw gefällt dir

**Comment by LabyStudio** [comment]
Ich glaube wir nehmen da lieber das alte Tournament System

**Comment by HDuck** [comment]
Das hatte ich mir auch überlegt, 

ABER:
Viele Spieler meinen auch das wir sehr stark von anderen Servern klauen würden (Dojo)

Kit Prisoner, Hedgedog [..]

und wenn wir nochmal das Tournament reinmachen würden, würde sich das bestimmt noch mehr reizen

**Comment by lukas81298** [comment]
Ich glaube nicht, dass es sich llohnt dies umzusetzen
