### ISSUE TITLE
"nostats-" Region fehler (Wichtig)

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#381]
Du hast ja die nostats Region so gemacht, dass die Kills nicht mehr gezählt werden,
doch es gibt noch 2 fehler:

1. Beim Scoreboard steht zwar, dass man kein Kill bekommt, doch da steht, dass die Killstreak erhöht wird wenn man einen tötet 
=> Machen, dass man keine Killstreakpunkte bei einer nostats region bekommt.

2. Im chat steht trotz nostats region "You earned 10c for killing xx" "You earned 10 experience." 
=> Sollte man eig. nicht bekommen 

Wäre echt sehr sehr wichtig, damit das LMS System Morgen geht ^-^

**Comment by HDuck** [comment]
Wurde nicht ganz behoben:
Man bekommt zwar keine XP mehr, dennoch bekommt man credits plz beheben

**Comment by lukas81298** [comment]
Man bekommt keine Credits, es wird nur die Nachricht angezeigt. Ich kümmer mich trotzdem drum.
