### ISSUE TITLE
1v1 Bowls Droppen

### ISSUE THREAD

**Issue by xBlackJack** [MineKits/MineKits#382]
Wenn man ein 1v1 macht und seinen Recraft aussversehen droppt, bekommt man seine Pilze wieder, aber seine Bowls nicht. Hier nochmal gezeigt: 
https://www.youtube.com/watch?v=oJXWAiQOX0c&feature=youtu.be

**Comment by lukas81298** [comment]
Dann würde man aber nicht quickdroppen können...

**Comment by xBlackJack** [comment]
LOL stimmt ^^
Am 06.09.2015 21:45 schrieb "Lukas" <notifications@github.com>:
