### ISSUE TITLE
Lms HideAndSeek Spectator Bug

### ISSUE THREAD

**Issue by CraftingExpertDE** [MineKits/MineKits#384]
Als Spectator kann man auf der HideAndSeek Map türen und Trapdoors öffnen, was dem Seeker nen Vorteil bringt, weil er den Sound der Trapdoor/Tür hört xD

**Comment by lukas81298** [comment]
Man kann es temporär mit nem WorldGuard flag beheben
 Laby müsste sich dann mal um etwas dauerhaftes drum kümmern.

**Comment by LabyStudio** [comment]
Ehm du weißt schon das man selbst schuld ist ne´?
