### ISSUE TITLE
Kit Creeper Bug

### ISSUE THREAD

**Issue by CraftingExpertDE** [MineKits/MineKits#385]
Es funktioniert nicht und es buggt http://puu.sh/k4ic5/2870665834.png

**Comment by lukas81298** [comment]
Ok, morgen kümmern Daniel oder ich uns drum.

**Comment by lukas81298** [comment]
Ich kann den Fehler irgendwie nicht nachvollziehen. Das Kit wird jetzt entfernt, da eh kaum einer damit spielt. Wenn ich mehr Zeit habe, mache ich es vielleicht neu ;)

**Comment by HDuck** [comment]
Der Bug wurde eig. schon vor 1 Monat gefixt von LabyStudio - sicher, dass das Kit zurzeit nicht geht?

**Comment by lukas81298** [comment]
Ich schau mal
