### ISSUE TITLE
Kit FnS

### ISSUE THREAD

**Issue by CraftingExpertDE** [MineKits/MineKits#388]
http://puu.sh/kdgNy/4ada071129.png

**Comment by lukas81298** [comment]
Als ich verstehe den Namen nicht so ganz.

**Comment by HDuck** [comment]
So nennen die SG Spieler das Feuer platzieren unter einem Spieler

(Beispielsweise GApplen = Goldapfel essen)
sind halt einfach so ankürzungen ;)
