### ISSUE TITLE
/fly änderungen

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#389]
Hey Lukas (oder Laby) du hattest ja schon den FlyModus etwas überarbeitet, damit man nicht so gut abusen kann, dennoch gäbe es noch was, was man machen könnte:

- Man kann im Flymodus keine Pfeile/Angel/ andere Projektile (Schneebälle) werfen
- Man kann nicht /fly eingeben, wenn man bereits ein Kit hat

(Es ist so, dass wenn man /fly macht und ein Kit wählen will NICHT geht, aber wenn man vorher ein Kit wählt und dann /fly es geht) 

 ~Duck

**Comment by lukas81298** [comment]
Sorry, dass es so lange gedauert hat. Ich kümmer mich dann morgen drum.

**Comment by lukas81298** [comment]
fixed!
