### ISSUE TITLE
FAQ 

### ISSUE THREAD

**Issue by xBlackJack** [MineKits/MineKits#390]
FAQ - RULES - Which client mods are allowed
Anstatt LualMod -> LabyMod ( http://puu.sh/kgFOW/7f9fe00e32.png ) 

FAQ - TEAMSPEAK - Donator Rank on minekits
Message zu Lang, nur mit gui größe normal sichtbar ( http://puu.sh/kgFU6/56ade1c1d9.png )

**Comment by lukas81298** [comment]
fixed
