### ISSUE TITLE
Wieder /reports Command einführen

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#391]
Mich haben paar Mods gefragt, ob man die letzten Reports sehen kann (wie früher /reports)
Seit dem neuen Report System gibts das ja nicht mehr..

Könntest du sowas wie **/reports** wieder einführen, wo einfach die letzten  ~10 Reports angezeigt werden? Ist schon sehr nützlich

~Duck ;3

**Comment by lukas81298** [comment]
Ich habe es jetzt wieder eingeführt. Es werden die letzten 10 Reports angezeigt, wenn die Spieler noch online sind.
