### ISSUE TITLE
3 feature Ideen 

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#394]
Ich hatte mir vor langem (ca. vor 3 Monaten) schon paar Notizen gemacht was man bei MineKits noch so machen könnte - vlt. gefällt es dir ja ;D

___

**Änderungen beim WarpSelector (/warp):**

*Erklärung:* Wenn man das Warp-menu öffnet, steht bei jeder Map (feast, ehg, mlg...) wie viele Spieler bei den dort sind. (besonders nützlich, wenn nicht viele im Server ist und man nicht alleine bei einer Map sein will) 

*Screenshots:* 
http://prntscr.com/8psswz
http://prntscr.com/8pst6m
___

**WaterBoots für den neuen Spawn:**

*Erklärung:* Da der neue Spawn aus 40% Wasser besteht, hab ich mir gedacht, dass diese WaterBoots (wie bei z.B Delphin /boots damals) nicht schlecht wären, also es gibt dann viele verschiedene Arten von Boots, die dir was auf dem Wasser geben. (siehe unten; etwas schlecht erkärt :0)
*Waterboots Ideen:*
- Dolphin Boots: Man Springt auf dem Wasser wie ein Delphin (wie beim alten /boots)
- Jesus Boots: Man kann auf dem Wasser laufen
- Snowman Boots: Wenn du auf dem Wasser gehst, wird Wasser unter dir durch Eis ersetzt 
- Wenn dir diese Idee gefällt würd ich mir noch weitere ausdenken 

*Wichtig dazu* Bei einem Reload sollte es so sein, dass z.B die Schnowman Boots nicht das Wasser kaputt machen indem das Eis nicht despawnt. (So wie bei Gladiator Kästen, wo das Glass nicht despawnt)

___

**/Souptest** 

*Erklärung:* 
Es gibt ja Aimtest, Clicktest, MLG etc. da hab ich mir gedacht wie wär ein Souptest (das selbe wie warp Lava).
Wenn man /souptest eingibt, gibt es 3 Schwierigkeitsstufen: Easy, Norma, Hard. (Die GUI ist so wie bei /aimtest also auch mit den TOP 10 Stats für die 3 Schwirigkeiten) 
- Bei Easy bekommt man 1,5 Herze Schaden jede halbe Sekunde
- Bei Normal bekommt man 2,5 Herzen Schaden jede halbe Sekunde (das ist der LavaDamage)
- Bei Hard bekommt man 4,5 Herzen Schaden jede halbe Sekunde

*Wichtig dazu:* Die Stats sollen davon nicht verschlechtert werden (entweder wird man zu einer NoStats Arena geportet oder du machst es per Plugin, dass der Tod nicht zählt)

___

~Ente

**Comment by EinfachNiggo** [comment]
I really like the first feature!

**Comment by lukas81298** [comment]
1. könnte zu performance problemen führen. Mal schauen...

2. Die Dolphin boots werde ich machen, der rest ist ohne weiteres nicht möglich.

3. Wäre vom SwagPvP geklaut.
