### ISSUE TITLE
8 Kit Ideen! 

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#396]
Ich hatte bei meiner .txt datei noch einige Kitideen:

___

(1-3) = meine Bewertung 1 = naja ||| 3 = sehr gut
**ÜBERSICHT:**
- Kit Hacker (2)
- Kit Burrover (2)
- Kit Bouncer (2)
- Kit Virus (1)
- Kit Platformer (3) !
- Kit Arrow (3000) !
- Kit Line (3) !
- Kit Nude (3) !

außerdem wär es noch gut, wenn du weitere Kits von Nr. 314 machst! :)
https://github.com/MineKits/MineKits/issues/314
___

**Kit Hacker**
*Ability:*
- Man hat ein Item, wenn man dieses Rechtsklickt, aktiviert man ein zufälligen hack für X 

Sekunden.

*Hack Arten:*
- Forcefield (Man gibt jedem Spieler im Hit-Radius 3 Herzen Schaden [soviel wie ein Schwert])
- Speed (So als hätte man Speed 3, nur dass es kein effekt ist)
- Fly (man kann fliegen aber nicht so schnell)
- Autosoup (Immer wenn man Damage bekommt, füllt sich das sofort auf, doch man verliert eine Suppe 

in der Hotbar)
- FastHeal (Regeneration 2 Effekt, aber man sieht den effekt nicht) 
- AntiKnockback (Man bekommt einfach kein Rückstoß => Anchor ohne sounds)

*Damit man weiß, dass er echt nicht hackt:*
Der "Hacker" hat dabei immer ..
- Schwarze Partikel über ihm (so wie eine schwarze Wolke)
- Schwarzen Helm/Schuhe
- ODER im Chat steht nur für die Spieler in der nähe "<Player> the hacker activated <Hack art>" 

oder so
- oder halt was, damit jeder weiß, dass es nur ein Kit ist

*Sonnstiges:*
- Bei NoSoup verboten (Wegen den Heal-hacks)
- Cooldown 50 Sekunden

*Upgrades*
- Cooldown -5 sek
- länger hacken
- cooldown - 5 sek

___

**Kit Burrower**

*Ability:*

- Wenn man Sneakt, ist man ein Block im Boden (unter dir spawnt aber immer ein "Fake Laub Block" 

wie bei Blink) 
 => http://prntscr.com/8s7z0l
- Wenn man Springt (**ohne dabei W zu drücken* bzw laufen) wird man 2 Blöcke nach oben geportet 

(unter dir ist wieder ein Fake-Laub-Block)
 => http://prntscr.com/8s7z5i

*Was bringt das?*
- Man kann damit den gegner verwirren wenn man aufeinmal im Block bzw. über ihn ist 

*Sonnstiges:*
- Wenn man einmal die Ability benutzt hat, hat man einen 10 sekunden cooldown dafür, aber man kann 

noch die andere Ability nutzen
(bsp. ich sneake einmal => 10 sekunden cooldown, aber kann dabei immernoch die Leertaste-Ability 

benutzen)
- Dieses Laub despawnt natürlich auch wie bei blink nach der Zeit

*Upgrades:*
- -3 sek. cooldown

___

**Kit Bouncer**

*Ability*
- Kurz: für dich sind die Blöcke so wie trampoline
- Wenn du vom Tower runterspringst bouncest du wieder leicht hoch (wie beim Trampolin bzw. 

Slimeblock) außerdem bekommt man max. 5 Herzen fallschaden
- Wenn du auf jemanden vom Tower aus springst, bounced er auch mit und er bekommt fallschaden 

(radius: 2 blöcke)
- Wenn dich jemand gegen eine Wand schlägt bouncest du wieder zurück (Wand muss mindestens 2 

Blöcke hoch sein) (als wären die Wände Trampoline) 

*Sonnstiges*
- Nicht mit Stomper mixbar
- Es sollte irgentein Sound kommen, damit man weiß, dass es nur ein Kit ist (bsp. Slime sound) vlt 

auch noch Slime Partikel 

___

**Kit Virus** (oder anders)

*Ability:*
- Kurz: Man ist sozusagen eine infizierte Person und verbreitet einen Virus
- Klicke dein Item, um jeden Spieler im Radius von 6 Blöcken zu infizieren (danach KitItem-

Cooldown)
- Alle Infizierten Spieler in deinem Radius von 3 Blöcken haben Neusea & verlieren ca. halbe 

Sekunde 1 Herz (vlt auch nerfen/buffen) 
- Wenn ein infizierter Spieler in deinem Radius von 3 Blöcken einen un-infizierten hittet, hat er 

auch den Virus/ ist infiziert.

*Sonnstiges:* 
- Wenn man Stirbt ist der Virus weg - alle sind wieder Gesund
- bzw. Wenn 1 Minute vorbei ist, sind auch wieder alle Gesund
- Kititem Cooldown: 1 Min

ok es ist nicht ganz so gut beschrieben, wie ich es mir gewünscht hatte, aber irgentein kit mit 

'nem Virus/ infektion wär schon toll ^-^

___ 

**Kit Platformer** (oder anders)

*Ability:*
- Rechtsklicke einen Spieler mit deinem Kititem, so werdet ihr 10 Blöcke nach oben auf eine Runde 

Platform (radius: 5) geportet (wie Gladiator, nur ohne Wände und nur 10 Blöcke hoch).
Die Arena besteht aus den Fake-Leave-Blöcken
Screenshot: http://prntscr.com/8s8c9o
(Bei der Wolle Spawnen dann die 2 Spieler ) 

*Sonnstiges:*
- Wenn über dem Platformer Blöcke sind, kann er das Kit nicht benutzen (z.B sie sind in einer 

Höhle und man würde Suffucaten) 
- Im gegenteil zu Gladiator, kann man einfach Runter springen aber der andere kann immernoch oben 

bleiben, bis die Platform nach 10 Sekunden despawnt.
- Cooldown: 40 Sekunden
- Wie bei Gladiator, Airstrike... kann man die Leave-Art wählen 

*Upgrades:*
- -5 sekunden cooldown 
- Platform ist 15 Blöcke hoch ?

___

**Kit Arrow** (oder anders)

*Ability:*
- Man hat 1 Pfeil und 1 Bogen.
- Man kann nur alle 20 Sekunden ein Pfeil schießen
- Wenn man mit dem Pfeil ein gegner trifft:
 => Er bekommt 2x so viel damage wie ein Normaler Pfeil
 => Der typ mit dem Arrow Kit Teleportiert sich zu ihm 

*Sonnstiges*
- Das Kit ist einfach awesome machs rein.

*Upgrades*
- -5 sekunden Pfeil-Cooldown
- Der gegner bekommt Blindness wenn man ihn trifft

___

- **Kit Line** (bitte erfinde ein besseren namen, mir fällt nix ein)

*Ability:*
- Man hat wie bei Grappler ein Item womit man eine Angel auswirft.
- Wenn man sein Item wegscrollt, soll der Spieler immernoch gehookt sein
- Wenn man ein Spieler hookt, hat er Blindness 1 und slowness 1
- Die Angel wird automatisch nach 10 Sekunden entfernt und man bekommt einen 40 sek. cooldown

*Sonstiges* 
- Erst wenn die 10 sekunden vorbei sind, bekommt er den 40 Sekunden cooldown!

*Upgrades:*
- -5 sekunden cooldown
- er bekommt noch für 5 sekunden neusea

___

**Kit Nude** (oder anders)

*Ability:*
- Man hat keine Rüsstung bei NoSoup & Feast
- Man bekommt für Kills mehr XP & Money (edit: nicht zu viel money.. vlt. +15%)
- Man kann keine Rüsstung anziehen

*Sonnstiges:*
- bei EarlyHG verboten

___

Puh! Das wars :D 
Wäre toll, wenn du besonders diese Kits übernimmst:
**Hacker ; Platformer ; Arrow ; Nude (vl. bouncer)**
bzw. bei https://github.com/MineKits/MineKits/issues/314
**Knockbacker, Technician, Penguin, (vlt Biber)**

**Comment by EinfachNiggo** [comment]
Kit Hacker: Sehr cool! Es darf nur nicht zu OP werden.
Kit Burrower: Finde ich eher unnötig.
Kit Bouncer: Gute Idee, es sollte aber noch in irgendeiner Weise dem Gegner Schaden o.ä. geben.
 Kit Virus: Gefällt mir! Vielleicht geht es ja, dass die Infizierten solange einen ZombieHead tragen! 
Kit Platformer: Ich würde die "Arena" noch etwas größer machen. Was ich cool fände, wenn der, der als erstes runterfliegt Poison bekommt, oder vll. 8 Herzen FallDMG, damit man versucht oben zu bleiben und den anderen runter zu knocken.
Kit Arrow: Cool, passt :) 
Kit Line: Finde icn relativ unnötig. 
Kit Nude: Cool, aber wenn dann nur bisschen mehr Coins, sonst spielt das jeder.. Aber Idee gut!
