### ISSUE TITLE
IDEAS FOR THE NEW UPDATE WHEN THE MAP IS FINISHED

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#398]
The new map is coming soon and as you know it's pretty big. So i have some ideas :P

**- It would be really cool and helpful if you could add some Boots especially for discovering the map/spawn.**
Basically there are 2 different types for each section.

  - Jump Boots
     - 1: You can double jump
     - 2: You can trible jump or only double jump but higher than the others

  - Water Boots
     - 1: You can jump while being in water
     - 2: Again higher than the first one

You can also change it, it's simply a basic idea.
(implemented)

- You could also add the "fly permission for a certain time" to the ingame shop. 
- You can do /fly for let's say 5/10/30 minutes. In this time you are able to fly. But not Hit others ofc. 

~~- A stats reset would also be oretty nice when the new map is finished. And every month/week the top 1 player gets emerald for a week.~~

**- Some nice prices for rank ups would also be nice.** (implemented)

- What about adding easter eggs around the map with which you can get Coins/Achievements/XP Points etc.

**- Nearly nobody really knows the casino feature. I would also higher the prices, for example a random kit, boots, 1 day iron (checkpot) and maybe the build could build kinda like a casino at the spawn so everyone sees it.**

✅ - Killstreak rewards: https://github.com/MineKits/MineKits/issues/400

- First of all thats it. Give me some feedback about what u think.
- Just ignore my faults, thanks.

~ Nico (einKoala)

**Comment by HDuck** [comment]
my opinion:
✔ = good/ I like it
✘ = :/ bad 
- Boots @ new spawn: ✔ 
- /fly Shop: ✔ 
- Statsreset: ✔  (But the old stats should be viewable on the website like @june 30th - http://prntscr.com/8san00)
- other cool prices for upranks ✔  (for example: a casino ticket)
- Eastereggs ✔ (for example "MHF_" skulls if you klick them you get money or achivments [only 1x useable]
- Higher LMS Prices about 1k to 3k ✔  (~800-3k)
- The host don't lose his money ✘✘✘✘✘ (no no no :o) 
- new prices @ casino ✔ (but If lukas do the /mine feature ✘no https://github.com/MineKits/MineKits/issues/320 )

My wishes:
- Ban Reset => more players & maybe some of them stop hacking > 2nd chance || would be great in my opinion :3


~Duck

**Comment by lukas81298** [comment]
We will reset the ban list when the new map is released. I don't want to reset the stats because not even the highest rank has been reached yet. However, we can display monthly stats by default on the website and at /stats.

**Comment by lukas81298** [comment]
I marked everything important bold and striked things we won't add. Rewards for the weekly/monthly/daily players would be really awesome and I think we will add it.

**Comment by Stark98** [comment]
On the MineKits website you can't see the names on the global ranking of players. Can this be fixed? Also, is it possible to add the nationality of the players on the website?  Would be awesome :D

**Comment by lukas81298** [comment]
Most of the things you named have been implemented. The changes to the casino will be done tomorrow!
