### ISSUE TITLE
Bugs with /fly

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#399]
As you know, /fly is pretty "buggy".
- So basically these are the things you should fix:
   - You take LavaDMG
   - You get DMG from Poison etc. -> Pots
   - You can get stomped

I don't know, if there's more :D
 ~ Nico [einKoala]

**Comment by lukas81298** [comment]
I'll fix it now.

**Comment by lukas81298** [comment]
Fixed!
