### ISSUE TITLE
Killstreak

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#400]
There's already a message in the chat, when you get a Killstreak of "x".

- What would be really cool, is:
 - So basically when you get a several amout of Kills, you will also get a special "gift".
    
      - Killstreak of 5: You get 32 of each shroomies.
      - Killstreak of 10: You get 64 of each shroomies.
      - Killstreak of 15: You get a Speed II pot.
      - Killstreak of 20: Your armour and sword etc. will get repaired.
      - Killstreak of 25: You get a Fireresistance pot.
      - Killstreak of 30: You get 10 levels.
      - Killstreak of 35: You get 10 TNT.
      - Killstreak of 40: Your armour and sword etc. will get repaired and you get 64 of each shroomies.
      - Killstreak of 45: You get a Speed II pot.
      - Killstreak of 50: You get a diamond helmet (at eHG gold or lether) which won't break and/or drop and 500 coins.
      - Killstreak of 75: You get Regeneration II for 2min and 750 coins.
      - Killstreak of 100: You get a Diamond chestplate (at eHG gold or lether) which won't break and/or drop and 1000 coins.

These are just examples, so you can mix them as you want.
 - I hope that helps :)

~ Nico [einKoala]

**Comment by lukas81298** [comment]
That's great. We'll add this soon.

**Comment by Stark98** [comment]
Great idea, but in my opinion you should start getting "gifts" at higher killstreaks like 25 and upwards!

**Comment by lukas81298** [comment]
Implemented in the new update.
