### ISSUE TITLE
Insulting

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#401]
So when you write something like "eZ" it only shows "**". 
That's good! :d
  - Maybe you could also add, that when you write a swearword you lose 1-10 (?) coins.

~ Nico [einKoala]

**Comment by lukas81298** [comment]
Someone already suggested this in the past. @LabyStudio probably has to implement this.

**Comment by lukas81298** [comment]
I don't think this would be a good idea.
