### ISSUE TITLE
Bans/Warns

### ISSUE THREAD

**Issue by ScrummerLP** [MineKits/MineKits#403]
I think we should try a new Ban-system:

**Hacking**
* 1st Time some1 is hacking: tempban for 30 Days
* 2nd Time: perm ban

**Cheating(s.th. like Autoclicker/macros, bugusing, commandabuse)**
* tempban for 15 days

**swearing/spaming**
* warn (3 warns = automatically 3 hours tempban)

**DDos threat**
* perm ban

**Teaming**
* tempban for 7 days

**Insulting Staffmembers**
* warn (3 warns = automaticaly 3 hours tempban

Thanks for Reading

Regards

*Scrummer*

**Comment by lukas81298** [comment]
1st has been implemented and will be active in the new update. The system automatically detects if someone has been banned in the past when you type /ban <player> cheating ... and chooses an appropriate time!
