### ISSUE TITLE
/report add

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#406]
In german 'cause it's only a message @coders

  - Könntet ihr vielleicht hinzufügen, dass wenn man hier "Other" auswählt ein Schild oder so kommt, auf das man dann das schreiben kann, was man meint. 

  - So ist es für die Mods leichter zu erkennen, was gemeint ist, weil wenn einer für Other reported wird, weiß man nicht, ob er nur beleidigt, oder so, oder einfach einen Hack hat, der hier nicht gelistet ist.

  - Hoffe, ihr habt das verstanden.

~ einKoala, Nico c:

**Comment by EinfachNiggo** [comment]
Hier, das meine ich! http://prntscr.com/8seilu

**Comment by ScrummerLP** [comment]
oder ein Buch, in welchem man den Hack genauer beschreiben kann.

**Comment by HDuck** [comment]
Fänd ich auch gut :+1

**Comment by lukas81298** [comment]
Ich glaube, dass das nur abused werden würde. Wir können aber gerne noch die Report Gründe ergänzen.
