### ISSUE TITLE
Staff-Commands

### ISSUE THREAD

**Issue by ScrummerLP** [MineKits/MineKits#407]
Hi Together

Here is a summary of all commands that didn't work, sorted by trialmod, mod and mod+

**Trial-Moderator**
* /reportlist
* /warns

**Moderator**
* /bc or /broadcast

**Moderator plus**
* /signedit
* /resetkit (is bugy: you can only reset your own kit)

**The following Commands can be used but aren't displayed in the Moderator-Panel:**

* /blacklist <list / add / remove / search> <word>
* alle /mkconfig commands

**Please check also, where the commands are displayed in the Mod-Panel. Some commands are displayed at Mod+ but can also be executed by normal mods (ex: /unban, /speed) & commands which don't work by T-mods also can't be executed by higher ranked mods.**

I hope I haven't forgot  something. But if I've forgot one, pls write it as comment :3

Regards

*Scrummer*

**Comment by lukas81298** [comment]
Fixed!
