### ISSUE TITLE
Team LMS!

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#408]
What about adding LMS' where you can play/fight as a team?

- My idea is:

  - General:
      - There are two teams who fight against each others until one team has lost.
      - Before the LMS starts (When the cooldown in the chat is finished) you can choose your Team "Emerald" / "Iron" or click "Random" to join a random team.

  - Equipment:
      - Full Iron with Unbreaking X and a lether helmet which can't break. 32 of each mushrooms and a Sharpness I (?) iron sword. 
      - Team Emerald has a green lether helmet, Team Iron has a grey one.

  - Price
      - The price is the same as in the other LMS'. The host can decide how many coins you win
      - But here all the team members of the winning team who are still alive win the coins.

  - Map
      - I think you also need a new map for that 'cause we don't have one which fits this mode i think.

  - Others
      - When you get killed you can watch the others like the Brackets LMS.
      - The items don't drop so the LMS doesn't take too long. (?)
      - Maybe it's possible that you get DMG (1/2 a heart per second) when you don't hit someone so you can't camp. [Also good for the normal LMS!]
      

- I hope you understood everything, I tried to explain it as good as I can.
- Ofc you can change things you don't like.

~ einKoala [Nico]

**Comment by HDuck** [comment]
LMS Name? What about "Team Deathmatch" ^,^
but I like this LMS-Idea :+1:

**Comment by lukas81298** [comment]
Zunächst sollten wir erst mal das neue EVENT System fertigstellen.--
