### ISSUE TITLE
Signs @ Lavachallenge

### ISSUE THREAD

**Issue by ScrummerLP** [MineKits/MineKits#411]
Hi together!

A Player on Minekits asked me a very good question:

"Is it possible to get the Kit **PvP** when you hit the signs in the lava challenge?"

I must say: It's a very good idea and I think also that it's good to change that.

Regards

*Scrummer*

**Comment by lukas81298** [comment]
Do you mean the kit with iron armor?

**Comment by ScrummerLP** [comment]
@lukas81298 No, just the normal pvp kit. (do /pvp) only stone sword with full inv and 32x Recraft

**Comment by lukas81298** [comment]
It's already there :O http://prntscr.com/8v5ggx

**Comment by ScrummerLP** [comment]
Not at the beginning from the Lavachallenge.... While you do the Lavachallenge.. On the way while you do the lavachallenge, there are some signs where you can click on to get a refilled inventory

**Comment by lukas81298** [comment]
So you want to add a stone sword to the refilsigns.

**Comment by Stark98** [comment]
I have another suggestion. 
I think we should make a new lava challenge called Nightmare or something similar, where you have to go a really long distance before you can refill, and where you have to open a chest and refill soups out instead of only clicking the sign!

**Comment by lukas81298** [comment]
Well, we may add this to the new map. Maybe there is some space for it ;)
