### ISSUE TITLE
Unban?

### ISSUE THREAD

**Issue by Stark98** [MineKits/MineKits#412]
Hey, this is only a suggestion and I understand if you're against it. But I think it's time for giving the banned players on MineKits a new chance. Many people have been banned during the years, for various reasons. Of course I think hackers should be punished, but many of them have probably understood that hacking will gain them nothing. 3500 players have been banned, a huge part of the playerbase, and in my opinion they should get another chance. Yes, I know that all the moderators (including me) have worked hard to remove hackers from MK, but an unban will give us more to do as moderators. Also, many of the banned players will hopefully join the server again (without hacks), and our playercount could increase. 

Again, this is only a suggestion and I understand if you don't like it! Thanks for feedback :)

**Comment by lukas81298** [comment]
The banlist will be resetted when we realease the new map.

**Comment by Stark98** [comment]
Ok! Great:)
