### ISSUE TITLE
LMS reset

### ISSUE THREAD

**Issue by ScrummerLP** [MineKits/MineKits#413]
Hey Guys :)

This is just a wish from me and it will be very nice if it's possible to make that.

Is it possible that Moderators can reset the LMS too?

Regards

*Scrummer*

Btw: It doesn't really matter when you can't do that. But it would be nice :D

**Comment by HDuck** [comment]
I think that wouldn't be so good. :/

Generally admins should never reset the LMS-Cooldown (LabyStudio said) . Its only, if (for example) Schweini is streaming and he want to host more LMS's or if there are errors  and we are trying to fix it or something like this. sorry!
