### ISSUE TITLE
Gegen welche Kits ist "Anti"?

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#415]
| - GERMAN (/But its just a question - nothing important ^^)

Lukas bei der Beschreibung von Kit Anti steht, dass es gegen viele Kits wirkt und dass es Upgrade bar ist.
Aber kannst du sagen, gegen welche Kits es genau ist? (ggf. bei der Beschreibung reinschreiben, da sich auch viele User sich das fragen) 

*Ich weiß nur, dass Stomper, Gladiator und vlt. Anchor drinnen ist*

~ Duck

**Comment by lukas81298** [comment]
Hm. Da muss ich selbst mal nachschauen. Bei den Upgrades steht auf jeden Fall was dazu.

**Comment by lukas81298** [comment]
Viper,Snail,Pyro,Priest,Anchor,Stomber (Upgrade 1),Gladiator (Upgrade 2),Rogue,Grappler
