### ISSUE TITLE
Kitmixing - die selben Items haben

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#416]
Lukas, kannst du was dagegen machen, wenn man bei einem gemixten Kit 2x das selbe Item hat, dass sie trotzdem nicht gleichzeitig los gehen?

Beispiels Mix: Archer + Hedgehog (beide ein Bogen als Item)
Wenn man mit dem Archer Bogen schießen will, kommen gleichzeitig die Hedgehog Pfeile..
man könnte vlt. die Items ändern aber vlt. lässt sich da ja was machen, oder?

~Duck

**Comment by lukas81298** [comment]
Mach am besten mal ne Liste der Kits, bei denen das der Fall ist. Mit einem Mehraufwand lässt sich da durchaus beheben (habe ich auch schon bei manchen Kits).

**Comment by HDuck** [comment]
Alle Kits mit gleichen Items:
Fisherman & Survivor => Angel
Grappler & Cowboy => Leine
Archer & Hedgehog => Bogen
Bomber & Airstrike => Anvil
Phantom & Glider => Feder
Hulk & Rider => Sattel
Zeus & Thor => Stein Axt
Escaper & Jumper & Vacuum => Enderpearl
Shadow & Tornado => Kohle


Sicher, dass du das so machen wilst? 
Langfristig wird das nicht gut, wenn man jedes Item nur 1x benutzen kann :s

**Comment by lukas81298** [comment]
Es wird ja über den Namen identifiziert.

**Comment by lukas81298** [comment]
Bei den meisten Kits ist es nun gefixed.
