### ISSUE TITLE
Kit Digger

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#42]
Kit Digger:

Wenn man sein Block-Iten auf eine stelle klickt, entsteht bei dem Ort ein 5x5x5 Loch.

Dieses Loch bleibt für 7 sekunden da, dann füllt sich nach und Nach das loch (von unten nach Oben)

Wichtig wäre es, dass bei einem Reload das Loch nichts kaputt macht.
Ob das Kit Gladiator Zellen kaputt machen soll, ist eure entscheidung :)

Cooldown: 35 Sekunden

**Comment by LabyStudio** [comment]
Nope.
