### ISSUE TITLE
Kit Idea

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#420]
- Name: I don't know :D

- Item: Chest

- Ability: You can click your item [chest] and then it spawns a minifeast under you. You can loot the four chests and you can also enchant if you want. It disapears after 15 seconds. If an enemy wants to go/jump on the minifeast he gets pushed away [@ coder, wie wenn man diese Falltüren am Spawn öffnet,  nur nicht so stark.] If you use your ability while you're normally standing on the ground you get teleported two blocks higher [> on the enchanting table]. The loot is like in the other feast chests. 

- Cooldown is 1,5 minutes to 2 minutes [?].

- Upgrade: -Cooldown will be lower
                     - Minifeast disapears after 20 seconds

Would do you think of the kit idea?

~ Nico/EinfachNiggo

**Comment by HDuck** [comment]
Awesome! 
,but I don't like this: " If an enemy wants to go/jump on the minifeast he gets pushed away"

**Comment by EinfachNiggo** [comment]
You could also change/delete that ;)

**Comment by lukas81298** [comment]
I think this would be too complicated as we would have to check if the minifeasts blocks something. This will cause too many issues...
