### ISSUE TITLE
Easteregg Feature

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#422]
**Kurz gesagt:**
Beim Spawn bzw. bei der ganzen Map sind überall Skulls versteckt, wenn man diese Rechtsklickt bekommt man dafür einen Preis. Wenn man einen Skull gefunden hat, kann man diesen nicht nochmal Rechtsklicken, jeder Skull ist immer nur 1x Klickbar.

___

**"Easteregg-<Name>" Region:**
Dieser Skull ist erst ein Easteregg, wenn er in der Region "Easteregg-<name>" ist. (Damit nicht alle Köpfe dir Preise geben (z.B Staff-wand) 
(Also den Kopf dann einfach mit Links & Rechtsklick mit der Worldedit-Axt Rechtsklicken und die Region setzen und schon ist es ein Easteregg-Skull)

___

**GUI**
Wie wär noch eine kleine GUI, wo man sehen kann, welche Köpfe man schon gefunden hat und welche nicht? 

Screenshot: http://prntscr.com/92dlq3
Wenn man den Kopf schon gefunden hat, wird er so angezeigt, wie er aussieht
Wenn man den Kopf noch nich gefunden hat wird er als Witherskeleton-Skull angezeigt

___

**Was bekommt man wenn man einen findet?**
- XP
- vlt. Coins
- Achivment wenn man [X] Stück gefunden hat

___

**Sonnstiges:**
Außerdem fänd ich es noch gut, wenn über den Skulls Feuerpartikel (oder andere Partikel) sind, damit man diese von anderen Skulls unterscheiden kann 

Achivments dafür bekommen

~ Ente 2k15

**Comment by EinfachNiggo** [comment]
Wenn man auf den Skull dann draufklickt, kommen paar Partikel mit Sound und der Skull ändert dann immer ganz schnell die Farbe, bis er stoppt und dann hat man halt was bestimmtes gewonnen. 
Man könnte ja einen bestimmten Skull für alle Eastereggs nehmen, und dann wenn man das spinnt kommen dann die Gewinne, dh es gibt einen bestimmten Skull für zB Coins (i-ein goldener Kopf).
Dann würde das ganze auch cool ausschauen :D
Ich hoffe man hat es verstanden..

**Comment by HDuck** [comment]
Jup wär sogar noch besser mit einem bestimmten Skull c:
Ich würde diese Skulls vorschlagen: "Mikano" oder "StackedGold"
Die haben ein Goldenen Kopf (so wie ein Goldblock)

"immer ganz schnell die Farbe, bis er stoppt und dann hat man halt was bestimmtes gewonnen. "
Hast du Ideen, was man gewinnen Könnte?

**Comment by EinfachNiggo** [comment]
Coins, XP, XP Boost, Random Kit (?), halt so die Standard Dinge..:P

**Comment by lukas81298** [comment]
Das ganze ist nun grundlegend implentiert. Ich muss noch ein paar kleine Änderungen vornehmen.
