### ISSUE TITLE
Liste von Herausforderungen für das Challenges System

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#423]
Das sind die "Aufträge" die man macht bei dem kommenden Challenge-System

___

DIE HERAUSFORDERUNGEN SIND NICHT SORTIERT!
(Am besten erst die Herausforderungen mit der **I** davor, danach die mit **II** dann alle mit **III** ...  oder iwie so

**Bloodlust I**: Get a killstreak of 5
**Bloodlust II**: Get a killstreak of 10
**Bloodlust III**: Get a killstreak of 15
**Bloodlust IIII**: Get a killstreak of 20
**Bloodlust IIIII**: Get a killstreak of 30

**Kit Challenge**: Mache 50 Kills mit dem Kit X.
*X = Random Kit welches man besitzt*

**Killer I**: Mache +100 Kills
**Killer II**: Mache +200 Kills
**Killer III**: Mache +300 Kills
**Killer IIII**: Mache +400 Kills
**Killer IIIII**: Mache +500 Kills

**Feast I**: Mache 25 Kills bei Feast
**Feast II**: Mache 100 Kills bei Feast
**Feast III**: Mache 200 Kills bei Feast

**EarlyHG I** Mache 25 Kills bei EarlyHG
**EarlyHG II** Mache 100 Kills bei EarlyHG
**EarlyHG III** Mache 200 Kills bei EarlyHG

**NoSoup I** Mache 25 Kills bei NoSoup
**NoSoup II** Mache 100 Kills bei NoSoup
**NoSoup III** Mache 200 Kills bei NoSoup

**1v1 I** Gewinne 25 1v1's
**1v1 II** Gewinne 50 1v1's
**1v1 III** Gewinne 75 1v1's

**Sniper I**: 10 Kills mit dem Bogen 
**Sniper II**: 25 Kills mit dem Bogen 
**Sniper III**: 50 Kills mit dem Bogen 

**TNT I**: 5 Kill mit TNT machen
**TNT II**: 10 Kill mit TNT machen
**TNT III**: 25 Kill mit TNT machen

**Boxer I** 1 Kill mit der Hand machen
**Boxer II** 5 Kill mit der Hand machen
**Boxer III** 10 Kill mit der Hand machen

**Spoilsport I** Töte 3 Spieler der vor einer Killstreak ist 
**Spoilsport II** Töte 7 Spieler der vor einer Killstreak ist 
**Spoilsport III** Töte 10 Spieler der vor einer Killstreak ist 

**Daily Quest I** Mache 1 der 3 DailyQuests
**Daily Quest II** Mache 2 der 3 DailyQuests
**Daily Quest III** Mache die 3 DailyQuests

**Miner I**: Nutze /mine 
**Miner II**: Verdiene über 1000 coins bei /mine

**Magican I**: Enchante 5x Sharpness
**Magican II**: Enchante 10x Sharpness
**Magican III**: Enchante 25x Sharpness

**Turtle I**: Töte 5 Spieler beim Sneaken 
**Turtle II**: Töte 15 Spieler beim Sneaken 
**Turtle III**: Töte 25 Spieler beim Sneaken 

**Lucker I**: Gewinne 1x im Casiono
**Lucker II** Gewinne 3x im Casiono
**Lucker III**: Gewinne 5x im Casino

-

**Tribute I** Win a LMS 
**Tribute II** Win a LMS again 
**Tribute III** Win a LMS again  

**Bei weiteren Ideen einfach ein Kommentar schreiben und ich fügs ein! **

**Comment by Stark98** [comment]
What about making a refilltest? The clock starts counting when you go into your inventory

**Comment by TrueProxxi** [comment]
Tribute I: Win a LMS
Tribute II: Win 5 LMS
...

**Comment by TrueProxxi** [comment]
(If the easteregg feature will be implemented)
Adventurer I: Find your first easteregg
Adventurer II: Find your second easteregg
...
Adventurer xyz: Find all eastereggs

**Comment by lukas81298** [comment]
Das ganze ist grundlegend fertig. Es fehlen nur ein paar Erklärungen und die Tabelle mit den Challenges muss aufgefüllt werden.
