### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Stark98** [MineKits/MineKits#425]
Hey, there are some bugs we should fix:
1. I think we should remove "Play a MineHG match every hour to earn extra xp/money"
2. In my opinion we should remove the message block system that prevents you from saying swear words. There are some bugs with this; you can't write names that contains for example "eZ". Also, it would be easier if people were able to say what they wanted to say, and if they talk inappropriately, the staff members can just mute them. This would give us more work, as well :)

**Comment by lukas81298** [comment]
The 1st one has been removed. Point 2 will be fixed with the new update.
