### ISSUE TITLE
Idea to challenge experienced players

### ISSUE THREAD

**Issue by CraftingExpertDE** [MineKits/MineKits#427]
When you begin PvP on Mk, you got 12 hearts, because your were ranked as "Unranked/Beginner", you got these 12 hearts until you earn the rank "Bronze III", since than you've got 10 hearts until you reach "Gold I". People who played so far are experienced, so they got 6 hearts, so they are more challenged in souping until they reach the end of the ranking system. But if you begin with playing and you think: You don't need the 2 "beginner hearts". You can change it in the Menu to 10;5 and other players, too. You cannot choose the 12 hearts, after you changed it to hearts like 10;5 and people who are higher than "Bronze II" can't choose this too, but you can change your hearts after you reached "Gold I" back to 10. Tell me your opinion Guys! 
~Crafting

**Comment by CraftingExpertDE** [comment]
I forgot to tell, that in the lms/1v1 regions everyone got 10 hearts!

**Comment by lukas81298** [comment]
I don't think people will like it because it is not a fair system :/ maybe we will do sth similar in future...

**Comment by HDuck** [comment]
Maybe in the Presitge Rank? (but without 12 hearts if you're unranked)

(btw. we need some Prestige-Kits because some players are already Illuminati-Ranked)

**Comment by ScrummerLP** [comment]
I also don't really like the idea that you have only 6 hearts when you are a high rank. But the beginner rank is a cool feature imo. I think especially new non-soup players get a better chance and they won't left the server directly (because the think soup is shit). Prestige Badges (or sth) are also a good idea :+1:
