### ISSUE TITLE
(kleine) Bugs beim neuen Spawn

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#429]
~~1. Bei Menü auf Killstreaks: 
KIllstreak 25, 30, 35 - Da müsste "You" und nicht "Your" stehen (oder?)~~

~~2. Bei /mine "How does it work" ist die 'unterüberschrift' in 2 verschiedenen Farben geschrieben ( http://prntscr.com/9al4b6)
Ist zwar nicht das wichtigste aber naja, wollts gesagt haben~~

3. Bei /aimtest -> Mushroom 
Da wird eine Reihe zu viel mit Mushrooms gefüllt => http://prntscr.com/9al8jh

4. **FRAGE:** was machen diese "Equipment Zombies" am Spawn?

5. **FRAGE:** Was bekommt man bei /mine, wenn man schon einen besseren Rang als Emerald hat? Coins? oder noch nicht fertig? ^^

~~6. Beim 1v1:
- Die Kit Abilitys gehen nicht (bsp. mit Hulk rechtsklicken => nix passiert)
- Wenn man beim KitSelector ausversehen abbricht und kein Kit wählt, hat man keine Suppen/Kit, sondern nur ggf. Eisenrüsstung~~

~~7. Bei MLG müsste man noch droppen deaktivieren
(jup ich weiß, ich kann das auch machen, aber ich sammle erstmal alle bugs ) ~~

8. /mine , /boots , /easteregg  in /menu hinzufügen
(oder sowas wie ein /help oder /settings command wo solche Commands stehn sind)

**Comment by lukas81298** [comment]
Punkt 1 ist gefixed.
