### ISSUE TITLE
Old spawn snowball-teleportation thingy

### ISSUE THREAD

**Issue by TrueProxxi** [MineKits/MineKits#432]
Beim alten Spawn konnte man sich ja, wenn man sneakt und klickt, mit einem Schneeball teleportieren. Und da wir jetzt einen neuen und weitaus größeren Spawn haben, mit vielen wunderschönen Gebilden, von denen ein normaler Nicht-Premium User oftmals garnichts weiß, da sie sich meistens Warpen, um von A nach B zu kommen, wäre ein schnelleres "Transportmittel" mehr als angebracht. Perfekt dafür wäre eben dieses alte Schneeball-Teleportations Prinzip, welches man natürlich nur in der Spawn Region benutzen könnte. Jedoch könnte man dieses alte Prinzip neu gestalten, in Form von Upgrades und mehr Benutzerdefinierung:

_______________________________________________________________________________

**Upgrades:**

Am Anfang hat man den gewöhnlichen, uns bekannten Schneeball. Das nächste Upgrade wäre dann der Pfeil. Der einzige Unterschied zwischen den beiden ist ihre Reichweite, der Pfeil fliegt nämlich um einiges weiter, als der Schneeball. Das letzte Upgrade wäre ein Feuerball (der der von Ghasts geschossen wird). Dieser fliegt nämlich unendlich lang in eine Richtung, weshalb er entweder nach einer bestimmten Zeit, oder nur in einer bestimmten Region exestieren kann, und wenn entweder die Zeit, oder die Region überschritten ist, getötet wird.
Hier eine kleine Verdeutlichung: http://prntscr.com/9d8of2

**Benutzerdefinierung:**

Der alte Schneeball hatte ja diese Smaragdblock Partikel. Es wäre aber um einiges cooler, könnte man sich diese Partikel frei aussuchen. Dazu würden z.B. einige, ausgewählte Block- (wie beim Smaragdblock) oder normale, richtige Partikel (z.B. Flame, Cloud oder Note) zur Verfügung stehen.

**Kosten**

Die Upgrades sollten im Verhältnis zu den Partikeln einiges mehr Kosten. Wenn z.B. ein Partikel-Effekt 500 Credits kostet, würde das Pfeil-Upgrade 2500 und das Feuerball-Upgrade 4000 kosten.
Eine weitere Möglichkeit wäre, jedoch müsste man noch darüber nachdenken, ob das wirklich Sinn macht, die Upgrades und Partikel einerseits temporär (z.B. 1 Tag, 7 Tage und 30 Tage), bis hin zu permanent kaufbar zu machen (ähnlich wie die Mixed-Kits).

_______________________________________________________________________________

Wenn ihr weitere Vorschläge oder Verbesserungen habt, könnt ihr diese gerne hier posten :D

**Comment by HDuck** [comment]
Fänd ich auch richtig nice @lukas81298 !

Weil (wie er schon gesagt hat) normale Spieler können halt den Spawn überhaut nicht erkunden, weil sie ja keine /fly Rechte oder sonnstiges haben. Man hat zwar diese Water-Boots, aber damit kommt man auch nicht wirklich weit.

Dass man die Schneebällte durch Pfeile/Feuerbälle ersetzen kann find ich auch super :+1: 

(Man könnte auch eine ähnliche GUI wie bei https://github.com/MineKits/MineKits/issues/362 "Snowball Shop" benutzen bzw. noch ein "Enchantment Bottle" Adden, wo man das zum Pfeil/Feuerball Upgraden kann ^,^)

**Comment by lukas81298** [comment]
Das Problem ist, dass das ganze ziemlich viel Performance zieht. Es wird dabei ungefähr 20 mal pro Sekunde ein Datenpaket an alle Spieler gesendet. Ich werde mal schauen, wie sich das optimieren lässt...

**Comment by ScrummerLP** [comment]
Wie wäre es wenn man einfach zusätzliche Boots macht. Beispiel:

* Doublejump boots | Kosten: 2500 Credits
* Tripplejump boots | 3500-5000 Credits

die anzahl der Sprünge kann natürlich variieren. Ich selbst finde die variante vom snowball-teleporting auch nicht sehr gut da ich selbst oft sneakend vor leuten stehe und sie hitte und auf einmal bin ich irgendwo anders. Aus dem Grund fände ich Boots besser. Man kann sie einfach ausziehen oder wieder anziehen.

**Comment by HDuck** [comment]
Hauptsache ein gutes 'Fortbewegungsmittel'

Es gibt zwar die Boots, aber die bringen dir halt überhaupt nichts (außer die Water-Boots) außerdem gibts dieses Bootssystem schon auf z.B GommeHD.net :/

Man könnte die Boots auch - wie Scrummer gesagt hat - ausbauen, sodass man mit den Boots auch was mit denen kann:
- Fart Boots: Wenn man sneakt, kommen die Furzgeräusche + man fliegt 2 Blöcke hoch 
- Cloud Boots: Man hat Wolken unter sich + man fällt langsammer runter
- Fire Boots: Feuerpartikel unter dir + Man läuft schneller
- Jumper Boots: Man kann DoubleJumps machen
- ...
aber damit könnte man auch nicht wirklich weit kommen

Perfekt waren die Schneebälle *(Ideal noch mit Proxxi's Vorschlägen)* - die gibts auf keinem Server und man könnte damit alles erkunden

Wenn es echt so viel Performance zieht, könnte man sich ja was neues ausdenken
z.B
- Die Schneebälle haben ein hohen Cooldown
- Man kann den Schneeball nur 5 mal benutzen und dann muss man ein Kill machen damit sich deine "Schneeball-Munition" auflädt
- ...
- Man hat eine art Grappler hook am spawn, nur, dass man damit viel weiter fliegt (wie bei MineHG 2013 damalige MineKits)
- Man hat ein Stock am Spawn wenn man ein Block damit hittet wird man da hin geportet
- *oder irgentwas anderes*
