### ISSUE TITLE
Ghostclients

### ISSUE THREAD

**Issue by Stark98** [MineKits/MineKits#433]
Hey! As most of you know, we have added "ghostclient" as an alternative to the /report command. But we still haven't got any way of actually exposing ghostclient-users. One way of solving this problem is of course by developing an advanced system that exposes such users. But this'll be really hard for the developers, so I don't think it's an alternative. Therefore I thought about the option of making kind of a judgement-day system (like Badlion). Players who cause many anticheat messages are probably hacking, and although we can't get them manually, we might be able to get them exposed by looking at the amount of anticheat messages they have caused. If they've caused many errors by the same type of hack throughout a long period of time, they are almost certainly hacking and should get banned. 

PS! Before starting with a system like this, it'll be very important to get rid of bugs that cause anticheat alerts and hacking alerts caused by lagging players.

**Comment by ScrummerLP** [comment]
We shouldn't only look at the hack alerts. Also the reports are important. Sometimes a player gets reported many times but he isn't causing hack alerts...

only an idea ;-)

*Scrummer*

**Comment by Stark98** [comment]
Good idea, Scrummer!

**Comment by lukas81298** [comment]
Well. It is not that easy as you think. I do not want to ban a player permanently before a human checked it. You can however see recent violations of a play by typing /vio playername
