### ISSUE TITLE
Commands beim LMS / 1v1 eingeben

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#434]
Aiim hat dir ja schon gesagt, dass man "7fly" im 1v1 eingeben kann - hast du auch gefixt.

Aber man kann "7kit <kit>" eingeben, und dann hat man die Rüsstung die man beispielsweise bei EarlyHG hat. 

Außerdem kann man "7fly" auch bei LMS eingeben 

Genauso kann man "slash<kommando>" eingeben

Am einfachsten wäre es, einfach "7<kommand>" und "slash<kommand>" zu entfernen - denk ich

**Comment by lukas81298** [comment]
Beim 1v1 ist es ja schon gefixed, ich sag Laby, dass er es rausnehmen soll
