### ISSUE TITLE
Idea for the Mods

### ISSUE THREAD

**Issue by ScrummerLP** [MineKits/MineKits#435]
Hi there,

AiimedbyBaum talked with me about a very cool feature (imo). He said that the Players on the server could better find help, when we do like a Language Tag in front of the name from each moderator. Here a few Examples:

- [GER] Scrummer
- [ENG] Stark98
- and maybe additional: [PT] ImThatGuy

Just Something like that... Or, if that is possible, country flags with colors. But that nearly impossible I think.

Regards
*Scrummer*

**Comment by lukas81298** [comment]
I can detect the country and the minecraft language, but thats both not the real language someone is speaking.

**Comment by ScrummerLP** [comment]
I think we need only one "main language" for the **mods**. Means: You don't have to detect the country. You can write it for each Mod extra you know?

**Comment by HDuck** [comment]
Einfach bei jedem Mod ein Tag davor welche Sprachen er spricht

[GER] Lukas
[GER] Schweini
[PT] ImThatGuy
[GER]<fast jeder vom Staff>
[NW] Stark68

Englisch muss ja sowieso jeder können, oder? eZ
