### ISSUE TITLE
/mine isn't working

### ISSUE THREAD

**Issue by ScrummerLP** [MineKits/MineKits#436]
Today 3 users told me that they ranked up but they haven't got a mine ticket. I also ranked up a few weeks ago but didn't got one. First I thought it was a normal bug but now several other users have the problem.....

Please fix :+1: 

*Scrummer*

**Comment by lukas81298** [comment]
You don't get a ticket for every uprank. Just for the 2nd 4th 6th 8th etc one.It is described in the /ranks menu.

**Comment by ScrummerLP** [comment]
xDD.... I'm not stupid :^) It was written in the chat that should got a ticket but I didn't had one... I ranked up to gold master and there I should get one :P

**Comment by HDuck** [comment]
Den Bug gibts anscheinend immer noch - ich eröffne wieder diesen Issue.

Skype:
[17:59:48] ProxxisBeautyPalace: the thing were you get the emerald rank by mining emerald ore in /mine seems to be bugged
[18:00:12] ProxxisBeautyPalace: AiimedByBaum and other users have reported it
[18:00:20] ProxxisBeautyPalace: and aiimed says he has proof

**Comment by lukas81298** [comment]
Das ist eine sehr genaue Beschreibung.

**Comment by HDuck** [comment]
Habe mit Aiim geredet:

/mine klappt komplett, außer, dass man den Emerald Rang bekommt .
(Er hat es auch mit einem Account getestet, welcher kein Rang hat & hat Emerald nicht bekommen)

**Comment by lukas81298** [comment]
Fixed!
