### ISSUE TITLE
Minekits 1v1 elo 

### ISSUE THREAD

**Issue by ImShizy0** [MineKits/MineKits#437]
So I was playing kohi last night, and I decided to play some ranked (elo). While playing I tought, how about making a ranked 1v1 warp (could be just in the 1v1 warp we have one, does not need to be a whole new warp tbh). Here is my idea: Basicly you will have the gold sword to 1v1 people (unranked) and a diamond sword to 1v1 people (ranked). When somebody invites you to a ranked match, it will be annouced clearly in chat (just so people arent like wtf why is this ranked I wanted to play unranked). When the guy you invite to play accepts, you will both get the same kit.

Full diamond armor: enchanted with Protection 1 - Unbreaking 1.
Diamond sword: Sharpness 1 - Unbreaking 1 - Fire aspect 1
16 ender Pearls (So you can quickly pearl a few blocks away to get some new soups in ur hotbar).
1 speed potion (speed II 1:30). & 3 extra speed 2 potion in your inventory (to the left side).
1 fire resistance potion next to the speed 2 potion in your hotbar (none extras in inventory).
32 recraft & the spots which are over after all of this is put in will be soups ofcourse.

Basicly when you win you will raise in elo, and if you lose you will go down in elo. For example:
EVERY player will start with 1000 elo. When he wins from like a 1100 he should get +25 elo. (because that one guy had kind of a lot of elo so he deserves to get a decent amount of elo for winning against him). The guy who looses will than go down -25 in elo. 

Other example: a guy with 1500 elo fights against a 900. If the 1500 wins he will only get +5 elo (since his enemy only had 900 so for the 1500 it should be easy to kill him) and the 900 will go down -5 in elo. BUT if the 900 guy will win he will gain 25 elo and the 1500 will go down by 50 elo.

I tried to put this in the minehub or however it is called but it would just bug. If someone could be nice enough to put it on there... Thank you!

Also leave some feedback & opinions about this. The reason I would LOVE to see this being introduced into minekits is because players will get something to play for within the 1v1 warp. Now it's like 1v1 and whatever. I think a lot of people would really like to see this being introduced into it. ^^

**Comment by lukas81298** [comment]
Well, ELO is quite more complicated than just "adding" and "removing" elo points. It will be too complicated!
