### ISSUE TITLE
Prisoner Kit Bug

### ISSUE THREAD

**Issue by TrueProxxi** [MineKits/MineKits#439]
So, first there was a bug where the lava just disappeared after a few seconds in the jail. Then I played with the kit for a while, and got jailed by someone and the lava disappeared. But when I tried to jail someone else, it didn't happen. So, I guess it happens randomly or something? But then I noticed another bug: once I jailed someone, I couldn't jail them again, and it just said "<Name> is already jailed!". The reason why this bug happens is that you never actually complete the lava challenge, and another consequence of that is that you can't issue any commands. You can either die, and when you do so it says that you haven't completed the lava challange, or you could just relog.
So yeah, thats it :D

**Comment by lukas81298** [comment]
I'll have a look into this later and will disable the kit for now.
