### ISSUE TITLE
Kitbeschreibung "Time Added:" falsch

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#44]
Wenn man /kit eingibt, auf ein Kit geht und dann auf das Papier (Information-Nametag)

dann stimmt das Datum vom  Kit nicht, bzw bei sehr vielen oder allen.

Wäre besser wenn man das ganz entfehrnt oder? Meiner meinung sowieso eine nicht brauchbare Information

**Comment by lukas81298** [comment]
fixed
