### ISSUE TITLE
Permban für Bans, wenn kein Cheating *DOPPELPUNKT* da ist

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#440]
Mit ist folgendes im Adminpanel aufgefallen:

Die Personen, die für Cheating: <Grund> gebannt sind, sind 30 Tage gebannt.
Aber die Personen, die für Cheating OHNE Doppelpunkt gebannt sind, sind perma gebannt.

Außerdem ist mir ein Ban aufgefallen, wo "cheating" falsch geschrieben ist, 
kann man das manuell auf der Website ändern oder soll man das Ingame Nachbessern mit "/ban <Name> cheating:..." 
Wär toll, wenn das auch auf der Website gehen würde, sind ja 4000+ Bans, da ist das etwas schwieriger

**Comment by lukas81298** [comment]
Also bei mir geht es auch nur mit 'cheating'

**Comment by HDuck** [comment]
Beim Adminpanel wird es als Perm-Ban angezeigt

Screen: http://prntscr.com/9kw09m
Achte bei den Gründen jeweils auf "cheating" & "cheating:" und wie lange sie gebannt sind
