### ISSUE TITLE
Gambler im mixedkit geht nicht

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#444]
Wenn Gambler im Mixed Kit ist funktioniert es nicht.

**Comment by lukas81298** [comment]
Ich kann das irgendwie nicht nachvollziehen. Womit wurde das Kit gemischt?

**Comment by HDuck** [comment]
Es ist egal, mit welchem Kit man es mischt, man bekommt den Knopf nicht, womit man das Kit benutzt.
Wenn man sich ein Knopf vom Gamemode Cheatet klappt es aber


=> Wenn man Gambler mixt bekommt man kein KitItem

**Comment by lukas81298** [comment]
Achso, das habe ich jetzt gefixed. Ist aber noch nicht freigeschaltet.
