### ISSUE TITLE
Kit 1v1's buggen manchmal

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#445]
Wenn man bei einem Kit 1v1 ist, ist es manchmal so, dass man im Boden buggt und so sein Kit nicht wählen kann.

Vielleicht müsste man die Spawnpoints 1 Blöck höher setzen, oder es liegt am code/feher.

**Comment by lukas81298** [comment]
Warum sollte man dann kein Kit auswählen können?

**Comment by HDuck** [comment]
Es ist so, dass man im Boden buggt, und so der Kit-selector die ganze Zeit an und auf geht.

Dann wird die Maus immer zurück gesetzt und man kann das Kit nicht wählen 
Versuchs einfach selbst ein paar mal bei mir ist es bei 3/4 versuchen passiert

**Comment by lukas81298** [comment]
Sollte gefixed sein. => Man wird einen halben Block nach oben teleportiert.
