### ISSUE TITLE
UpRank: FreeKit nicht bekommen

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#446]
Ein Spieler (xsouperdog) meint, dass er sein Random FreeKit nicht bekommen hat, als er zu Silver Master Upranked ist. 

Ich kann das leider nicht nachprüfen, ob die Funktion geht, (Hab alle Kits / Upranken dauert lange) 
vlt. kannst du dir ja XP cheaten und sehen ob es bei dir geht mit einem Alt-Acc

~Duck

**Comment by lukas81298** [comment]
Es war ein Tippfehler ;) Man bekommt ein Kit alles 5 Ränge, und nicht alle 4
