### ISSUE TITLE
Christmas Eastereggs removen

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#449]
Ich denk, jetzt isses Zeit die Christmas Eastereggs zu entfernen ...
(XMas Mode ist ja sowieso aus)

Kann ich die Skulls einfach abbauen, oder musst das das irgentwie im code machen? 

~Ente

**Comment by lukas81298** [comment]
Die Christmas Eastereggs wurden intern entfernt und können nun abgebaut werden!
