### ISSUE TITLE
Kit: Beastmaster

### ISSUE THREAD

**Issue by lejaden** [MineKits/MineKits#45]
KitItem: Bone
Cooldown: 30s
Ability: Click your bone to get 3 dogs, which are attacking your enemy
Pro: More Damage, ez refill/recraft
Contra: Dogs are 2hit

**Comment by HDuck** [comment]
Klappt leider nicht, wegen den Entitys.. hat ich auch mal vorgeschlagen
bzw Tiere sind Disabled, wenn man es auf macht ist der spawn vollter Mobs ^^
