### ISSUE TITLE
Steinschwert Damage bei 1v1 | Mushroom abbauen bei EHG

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#450]
Schweini hat bei /form gewünscht, dass Steinschwerter weniger damage machen sollen
( http://prntscr.com/9qj3hk ) ^^

**&**

Man kann keine Pilze bei EarlyHG abbauen trotz der "mushroom-6" region.

**Comment by lukas81298** [comment]
Das zweite Problem habe ich behoben.

**Comment by lukas81298** [comment]
Der Schaden ist jetzt bei -25%
