### ISSUE TITLE
1v1 Bug | Manchmal schaut es aus wie forcefield

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#453]
Schau dir dieses Video an, erklärt einiges

https://www.youtube.com/watch?v=p03qy45cuzE&feature=youtu.be

aber wie der bug auftritt weiß ich / AiimedByBaum nicht - ist einfach random

**Comment by lukas81298** [comment]
Das Problem lässt sich leider nicht ohne weiteres beheben. Ich denke mal, dass der Fehler irgendwo tief in Spigot liegt. Da die Spigot Version für 1.7.10, die wir nutzen nicht mehr aktualisiert wird, sind die Chancen gering, dass es behoben wird. Es tritt ja zum glück nicht oft auf... Gibt es den Fehler nur beim 1v1?
