### ISSUE TITLE
YouTuber Apply

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#454]
Because so many people a recently asking for the YouTuber Rank, we could add a command like /Yter (/Yterapply).
They can write down their YouTube name or/and URL. And also tell them automatically that they have to write a message to the MineKits YouTube Channel so we can check that the YouTube Channel is really owned by them.

If the staff writes /YterApplys or smth we can check all of them.
Only problem is Lukas or whoever has the MK yt Account needs to check the messages.

Idk exactly.. smth like that XD
- Nico

**Comment by lukas81298** [comment]
I actually plan to add an OAuth integration. This means that the user is redirected to the youtube login page and has to log in to request the youtube rank.

**Comment by EinfachNiggo** [comment]
That's even better! :P
