### ISSUE TITLE
MineKits YouTube Channel 

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#455]
The MineKits YouTube Channel is reeally inactive.
- So what about the idea that we will upload more regulary?!

- What we can upload:
  - Montages Made by MineKits Players ( -> reupload them.) They could also get like 2000 coins or smth
  - Ok, idk more Xd

Maybe you have some other ideas.

- Nico

**Comment by HDuck** [comment]
I'd love it, if users can submit their videos.

For example they record an Montage/Edit/Kit review/ cool clips .. etc. and send it to an seperate Email (like "video@minekits.net" or smth)


:+1:

**Comment by EinfachNiggo** [comment]
Yes, that's the idea :)

**Comment by lukas81298** [comment]
We probably need someone to manage the channel. Maybe we can do something cool on the channel

**Comment by HDuck** [comment]
Ich würde es gern machen ^-^
