### ISSUE TITLE
Wichtig: Spawntrappen bei EarlyHG mit Endermage

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#457]
Man kann bei EarlyHG auf den Berg klettern und dann mit Endermage Spieler hoch porten 
(Auch Spieler, die noch halbwegs in der No-PvP-Zone sind) 

Nachdem man einen hoch geportet hat, kann man z.B mit Grandpa einfach die Spieler runter schubsen..

**Idee zum Fixen:**

- NoEndermage - Region
- oder es irgentwie so einstellen, dass man nicht über dem Spawn Endermagen kann

Duck

**Comment by lukas81298** [comment]
Es würde doch auch klappen, wenn man einen, der in der EHG Spawn Region ist, nicht magen kann, oder?

**Comment by HDuck** [comment]
Joa schon, aber wenn er nur ein Schritt weiter geht, kann er immer noch hoch geportet werden

Teste es am besten selbst um dir das besser vorzustellen
(Man müsste ca. 6 Blöcke vom Spawn weg laufen, damit man nicht getrappt wird)

**Comment by lukas81298** [comment]
=> Neue Region, in der man nicht "gemaged" werden kann: nomage

Achtung: Änderungen sind noch nicht freigeschaltet!
