### ISSUE TITLE
Aigainst the Autoclickers!!

### ISSUE THREAD

**Issue by ScrummerLP** [MineKits/MineKits#458]
Dear Admin's / Owner's / Dev's

I just got a really nice idea to extend our Anti-cheat Plugin. It would be better in my opinion when we get **Autoclicker-alerts from 40 cps on upwards**. Additional would it be nice when the Autoclicker users **don't get kicked**. At the moment we have some trouble to warn them, when they get kicked.

Then a very new idea:
It would be nice when you add a /clicker <name> (only an example) command. This command checks a specific player for about **5-10 seconds and displays the clickspeed - average** from the player. So we can check the clickspeed. (If you maybe know; I am also "Mod" on FlowMC and there we have this command. There its very helpful)

Thans for reading

*Scrummer*

Other ideas for the command name:
/clickspeed (aliases: /cs)
/autoclicker (aliases: /ac)
/checkclicker
/checkclicks

~only ideas ;-)

**Comment by Haxorzis** [comment]
I think it's a great idea with the autoclicker idea, becouse its really annoying to wait until the autoclicker player joins again to warn him.The clickspeed average idea is also good to know! +1

**Comment by lukas81298** [comment]
40 cp/s can easily be reached when a player has a   high ping. We had that before...

**Comment by ScrummerLP** [comment]
ok.... then maybe a bit higher (or the mods have to check his connection first)

**Comment by HDuck** [comment]
Maybe if we type 
"**/clicker < name >**"
 it says 
"**< Name > did 10c/s || Ping: < players ping average >**" 

so mods can detect, if 40c/s was autoclicker or just a high ping.
Then we can ban the Autoclicker/Macro players.. I think there are many people with autoclickers but they get never banned

~duck

**Comment by ScrummerLP** [comment]
@HDuck really good :-) That would be perfect

**Comment by lukas81298** [comment]
I think djd001 will implement this soon :)
