### ISSUE TITLE
Monk alert-fix

### ISSUE THREAD

**Issue by ScrummerLP** [MineKits/MineKits#462]
If you play the Monk kit and you "Monk" someone it says in the chat: "You have been Monked!" (http://puu.sh/mYdQ9/496341d602.png) We should replace it with "Monked!" or sth.

**Comment by lukas81298** [comment]
Alright, I think the messaged screwed up xD Gonna fix it tomorrow!

**Comment by lukas81298** [comment]
Fixed! (Not online yet)
