### ISSUE TITLE
New update!

### ISSUE THREAD

**Issue by ImShizy0** [MineKits/MineKits#465]
This is what I was thinking about:
-1v1 update (seriously needed) (Maybe some new maps too)
- New warp ( The nether )
- Maybe some new kits? It's been awhile since we have added some good kits. (My kit idea later on)
-Bug fixes (obviously)

My kit idea: ''Viking''.
You start out with a wood axe (which deals dmg of stone sword, in ehg.)
In feast = Iron axe.
Every 5 killstreak you get, your axe will get a upgrade (Just as the regular Viking system works in HG). Now, ofcourse we need to balance this, any ideas on this would be nice!

**Comment by ScrummerLP** [comment]
Also a Kit idea:

The "Reflection" kit:

- Some Kit abilities from the enemies are reflected to them selves. You are NOT resistant against the Kits, like you are with the anti kit!

Option 1: You are reflecting only special Kits (Viper, Snail, etc.)

Option 2: You only reflect effects random, so you can be affected from eg. Snail, but sometimes the effect is thrown back to your opponent. (then we have to take every effects into the selection; not only special kits like viper, snail, etc.)

Additional: We can do an upgrade; Level 1: you only reflect the half of the effect, the other half will not be reflected and you get the effect.
Level 2 (maybe 4K credits): You reflect the whole effect.

**Comment by lukas81298** [comment]
1v1  System https://github.com/MineKits/MineKits/issues/466

Please create an issue for every single kit idea. That makes it easier for me to have an overview.
