### ISSUE TITLE
1v1 Recode

### ISSUE THREAD

**Issue by lukas81298** [MineKits/MineKits#466]
This is written in German because it is very complicated and I am too lazy to translate it into English. Sorry ;)

Da derzeit sehr viele Spieler (fast 50%) auf MineKits beim 1v1 warp sind, habe ich mir überlegt, das System komplett zu recoden. 

Das ganze würde dann über einen externen Server laufen (Aus Performancegründen). Über /warp 1v1 oder über doe Adresse 1v1.minekits.net wird mann dann  auf den Server joinen können.

Ist der KitPvP Server voll, wird man auf den 1v1 Server geschickt.

Zu den Änderungen am System:

- 1v1 Queue:
 - Es können 1.7 Spielern nicht mit 1.8 Spielern in einem Match landen
 - Es wird ein Elo System geben und verschiedene Elo Bereiche werden in Skill groups eingeteilt
 - Jeder Spieler kann auswählen, welche Kits und Maps vorkommen KÖNNEN.
 - Wenn man disconnected zählt es, als würde man sterben
 - Die Matches sind auf 10 Min Länge beschränkt
 - Eine Queue für unranked matches

- PotPvP 1v1 Presets

- Die Kit1v1 müssten vermutlich vorerst entfernt werden könnten aber ggf. wieder hinzugefügt werden

- Man kann auswählen, welche Spieler man in der Hub sehen kann (Keine, Alle, Premiums+Youtuber+Staff)

- 1vs1 kits ohne suppen

- Alles wird auf Englisch und Deutsch sein (Ggf. weitere Sprachen(

- Erweitertes Statistiken System, auch auf der Website einsehbar

- Events auf MineKits werden auf dem Event Server announced

- Staff, Premium und Bans sind auf allen Servern gleich

- Es wird so sein, dass später mehrere Server hinzugefügt werden können.

Das ganze ist nur eine grobe Idee. Bitte schreibe eure persönliche Meinung in die Kommentare.

**Comment by xSkyPhoenixPvP** [comment]
Sounds Great!

**Comment by ScrummerLP** [comment]
Gefällt mir auf jeden fall :D

**Comment by ScrummerLP** [comment]
Noch eine kleine Idee (bitte schreiben, wenn das in eine extra issue soll):

- Ich fände es (momentan) gut wenn die Spieler welche afk beim 1v1 stehen ebenfalls in die AFK Area geportet werden, da es ziemlich nervt wenn tausend Leute AFK dort stehen.

- Ein Tool zum spieler verstecken/anzeigen (alle, staff/yt/prem, niemand) täte meiner Meinung nach auch der jetzigen lobby gut. Ich kann mir jedoch denken, dass das mit den Warps schwierig wird, da bei uns ja alles auf einer Map ist, und nicht mit Multiworld oder BungeeCord gelöst ist.
(Das wäre mal eine Idee für die nächste map, da wir mittlerweile ja doch recht viele Spieler haben, das ganze auszulagern, auf verschiedene server; Lobby eigener server/welt, und die jeweiligen warps)

by
*Scrummer*

**Comment by lukas81298** [comment]
Da das ganze ja auf einem externen Server laufen wird, wird es schwierig, die Spieler in die afk arena zu tpen. vllt. machen wir auch eine eigene dort.

Das mit dem verstecken der Spieler kann ich gerne auf dem 1v1 Server machen. Wichtiger ist aber, dass die Reports auch auf beiden Servern zu sehen sind. 

Einen Lobby Server möchte ich ungern machen, eher zwei KitPvP auf die die Spieler dynamisch verteilt werden.
