### ISSUE TITLE
Kit: Launcher

### ISSUE THREAD

**Issue by CraftingExpertDE** [MineKits/MineKits#47]
Wenn du fallschaden bekommst, werden die gegner um dich herum, 5 blöcke in die Luft geschleudert.

**Comment by LabyStudio** [comment]
Finde ich gut!

**Comment by HDuck** [comment]
Ist eine Gute idee,
aber ist halt genau die Devastor Ability bei Dojo

**Comment by CraftingExpertDE** [comment]
lol, wusste ich nicht xD Hab einfach an ein cooles launcher kit gedacht xD
