### ISSUE TITLE
Kit: Octopus

### ISSUE THREAD

**Issue by CraftingExpertDE** [MineKits/MineKits#48]
Wenn du deine Rakete rechtsklickst spawnt da wo du stehst eine gelaunchte rakete(steig aber nicht nach oben) und wirft potions um sich rum mit negativer art(poison, insta dmg 1, etc..)  das stellt sozusagen die Tentakeln von ihm dar.

**Comment by LabyStudio** [comment]
Ehh ok..

**Comment by EinfachNiggo** [comment]
Ist das dein kack Ernst Crafting? Du schlägst hier einfach eine Dojo Ability nach der anderen vor.. ._. ^^

**Comment by CraftingExpertDE** [comment]
nein mein fake weißte
