### ISSUE TITLE
Kit: Hobbit

### ISSUE THREAD

**Issue by CraftingExpertDE** [MineKits/MineKits#50]
Rechtsklicke dein dirtblock und es spawnt um dich herum im 3x3 bereich ein Dirt Bunker.

**Comment by LabyStudio** [comment]
nope

**Comment by HDuck** [comment]
Ohh man :( Das Kit wäre echt geil

**Comment by EinfachNiggo** [comment]
Wieder Dojo ._. Es muss doch nicht alles nachgemacht sein :/
