### ISSUE TITLE
Kit: Restart

### ISSUE THREAD

**Issue by CraftingExpertDE** [MineKits/MineKits#51]
Wenn du stirbst: respawnst du an der gleichen stelle mit der gleichen Killstreak und 3 bars von soups, kannst aber 30 sekunden lang keinen hitten.

**Comment by LabyStudio** [comment]
Naja

**Comment by HDuck** [comment]
Naja das mit den 30 sekunden HItten,
wenn schon dann auch so 1 Bar oder so, sollte aber schwer sein zu coden

ps. Bei dojo ist es das Kit Jesus 1:1

**Comment by CraftingExpertDE** [comment]
Du kannst echt nur mit Dojo vergleichen xD Und wieder, ich dachte an ein cooles sec. life kit xD

**Comment by lukas81298** [comment]
Find ich um ehrlich zu sein nicht gut
