### ISSUE TITLE
Kit: Transformer

### ISSUE THREAD

**Issue by CraftingExpertDE** [MineKits/MineKits#52]
Wenn du mit deinem Ei einen Spieler triffst, verwandelst du dich in diese Person, man sieht zwar nen steve skin in der 1.7.10 aber das OF Cape^^ die denken dann das die Skin Server vllt buggen^^

**Comment by LabyStudio** [comment]
Jup ;)

**Comment by HDuck** [comment]
Ist 1:1 wie bei Dojo 
Kit Pokemon

**Comment by CraftingExpertDE** [comment]
lol, ich war nichtmal auf dojo xD Hatte das halt gerade mit laby getestet dann kam das xD
