### ISSUE TITLE
Kitbeschreibungen werden nicht immer komplett angezeigt

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#62]
Kurz und Knackig:
http://prntscr.com/6gk0ei

Der Text mancher Kits wird nicht ganz angezeigt,
du könntest es ja irgentwie so machen, dass es wie bei /form open ist,
alles Ordentlich usw.

**Comment by LabyStudio** [comment]
public static ArrayList<String> splitEqually(String text) {
		int size = 40;
		String color = "§a";
		ArrayList<String> ret = new ArrayList<String>((text.length() + size - 1) / size);

		for (int start = 0; start < text.length(); start += size) {
			ret.add(color + text.substring(start, Math.min(text.length(), start + size)));
		}
		return ret;
	}

**Comment by lukas81298** [comment]
Ab 40 Zeichen wird nun gesplittet
