### ISSUE TITLE
Kit Timelord

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#70]
Kit Timelord:
Kit Item: KEINE UHR Wegen 1v1 Item zb. Gold Barren

Wenn man sein Item Rechtsklickt, werden alle Spieler im Radius von 5 Blöcken eingefrohren.
Sie können sich dann nicht bewegen und die Maus kann man auch nicht bewegen (man schaut immer zur selben stelle)
Gleichzeitig hat man noch den Slowness effect, damit man weiss, dass man Eingefrohren ist.

Man ist genau 5 Sekunden eingefrohren, aber man kanns Upgraden
Cooldown: 40 Sekunden

Ps: Der Timelord kann sich selbst aber schon bewegen.

Hoff das ist Code'able bzw. gefällt euch

**Comment by EinfachNiggo** [comment]
Dann wäre halt Freezer bisschen unnötig, da der nur einen freezen kann. ;)

**Comment by CraftingExpertDE** [comment]
feezer wurde entfernt @EinfachNiggo

**Comment by lukas81298** [comment]
Ich will nix mehr 1 zu 1 von mcpvp umsetzten
