### ISSUE TITLE
"/tag" Bugs

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#71]
Hey Lukas,
es gab schon lange den fehler, dass der /Tag Command nicht genau Funktuniert.

bsp. Rank Diamond kann sich nciht zu Gold+ Taggen
oder man kann sich nicht zu YouTUber Tagen (vlt gewolt)

Jedenfalls hab ich das Gefühl das nicht alles Funktuniert.
z.B Ich tag mich als "Normal" und dann will ich mich als "Mod+" Taggen dann kommt Invalid Rank

und auch die Ansicht wenn man /tag macht, ist für manche Spieler sehr schwer, 
weil da nur "/tag <default, normal, Rank>" steht

**Comment by CraftingExpertDE** [comment]
also es ist ihr dürft euch nicht als youtuber taggen weil sonst laufen alle mods als youtuber rum.. das ist gewollt und das mit dem mod+ taggen geht nicht da ihr nicht die nötigen permissions habt^^ Und man meistens zu faul ist das zu machen xD
