### ISSUE TITLE
Von Statreset verliert man seine Upgrades

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#72]
Ich habe irgentwie meine KitUpgrades verloren,
ich glaube es liegt am Statresett,
ist das gewollt?

**Comment by LabyStudio** [comment]
Stimmt nicht

**Comment by lukas81298** [comment]
Man verliert seine upgrades nicht

**Comment by HDuck** [comment]
Hmm, irgentwie hatte ich sie alle verloren.. nagut könnt n BUg sein oder so:D
#closed
