### ISSUE TITLE
Kit: JetPack

### ISSUE THREAD

**Issue by CraftingExpertDE** [MineKits/MineKits#73]
Du hast ein Feuerzeug wenn du das rechtsklickst kannst du fliegen (pro rechtsklick steigst du nach oben) beim Feuerzeug geht die Durability runter und irgendwann zerbricht es(wenn es weg ist ist da nen fireball der loading.. heißt und nach 1ner minute sozusagen cooldown bekommst du es wieder und kannst wieder fliegen

**Comment by EinfachNiggo** [comment]
Klingt richtig cool! :)

**Comment by KnuddelPvPer** [comment]
Eigentlich voll geil xD
