### ISSUE TITLE
Kit Creeper Upgrades [by EinfachNiggo]

### ISSUE THREAD

**Issue by CraftingExpertDE** [MineKits/MineKits#74]
Creeper Upgrade:
- 50 Sekunden Cooldown
- Charged 1/4 so schnell
- 40 Sekunden Cooldown
- Charged nochmal 1/4 so schnell

**Comment by lukas81298** [comment]
Das mit der Charge Geschwindigkeit geht nicht so einfach, mal schauen

**Comment by lukas81298** [comment]
Ist ja jetzt im anderen Issue.
