### ISSUE TITLE
Kit Upgrades & kleinere Dinge c:

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#75]
Kit Upgrades:

CREEPER ✔
Level 1: Cooldown reduced to 50 seconds
Level 2: Charges faster (1/4)
Level 3: Cooldown reduced to 40 seconds
Level 4: Charges faster (1/4)

ENDERMAGE ✔
Level 1: Mageradius is 5 blocks

ESCAPER
Level 1: Cooldown recduced to 35 seconds ✔
Level 2: Enderpearl flys faster  x 

FIREMAN
Level 1: Immune to lava damage for 10 seconds

FISHERMAN
Level 1: Durability of fishingrod is higher

GRANDPA
Level 1: Stick with knockback IV

GRAPPLER
Level 3: Cooldown after getting hit is dividen (also halbiert)

HULK
Level 1: Get a green leather chest while carrying a player

JUMPER
Level 2: Get a enderpearl for every kill

KANGAROO
Level 3: Cooldown after getting hit is dividen (also halbiert)

LEVITATOR
Level 1: Blocks do 4 hearts of damage

MLG
Level 1: Able to MLG twice

MONK
Level 1: Cooldown reduced to 35 seconds

NINJA
Level 1: Cooldown reduced to 7 seconds

NUKER
Level 1: Cooldown reduced to 30 seconds

POSEIDON
Level 1: Get regeneration in water

PRO
Level 1: Your chest has unbreaking I

PUNCHER
Level 1: Cooldown reduced to 15 seconds

PRO
Level 1: Credit Offset set to 12%

PYRO
Level 1: Chance of setting a player on fire is higher

REAPER
Level 1: Wither time has 6 seconds

RELAXO
Level 1: 15% chance to get an extra soup
Level 2: 8% chance to get 5 mushrooms of each

RIDER
Level 3: Your horse has more hearts

ROGUE
Level 1: Disables the kit ability for 15seconds

SNOWMAN
Level 2: Able to throw 20 snowballs till the cooldown starts

SOLDIER
Level 1: Get 25% less falldamage
Level 2: Get 25% less falldamage again (insg 50%)

SPELLMASTER
Level 1: Cooldown reduced to 20 seconds

STOMPER
Level 1: Stompradius is 4 blocks

SUPERMAN
Level 1: Cooldown reduced to 45 seconds
Level 2: Superman-time has 8 seconds now

SWITCHER
Level 1: Start with 10 Switcher balls

THOR
Level 1: Cooldown reduced to 4 seconds

VACUUM
Level 1: Cooldown reduced to 7 seconds

VIPER
Level 1: Chance to poison someone of 35%

RACER (In Bike umnennen pls)
Level 1: Drive faster

- Bei der Rider-Beschreibung steht "hore" anstatt horse.

- Spellmaster / Stomper / Superman / Switcher / Tank / Thor / Tank  / Vacuum 
hat keine Kill-Beschreibung.
++
- Daily Leaderboard geht noch nicht.

- Wie wäre es mit einem automatischem MLG am Spawn? Dass man dann zB automatisch wieder hochgeportet wird usw.

- Vielleicht kann man Clicktest auch mit Doppelklick (Blockhit), dass man auswählen kann, ob Single- oder Doubleclick.

**Comment by lukas81298** [comment]
Das Daily Leaderboard geht bei mir
Clicktest @LabyStudio 
Das mit MLG am spawn versteh ich nicht so ganz

**Comment by lukas81298** [comment]
Das meiste wurde umgesetzt. MLG am Spawn kommt noch

**Comment by EinfachNiggo** [comment]
Cool, danke :)
