### ISSUE TITLE
Dojo / Kitpvp Server Nachmachen auf Minekits.. :p

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#82]
Ich finde's nicht so nice, dass wir / ihr paar Sachen von anderen Servern (hauptsächlich Dojo nachmacht)..
Das mit den Boots und so ist ja voll ok, aber ich würde keine/nicht so viele Dojo Abilitys (=Kits auf MK) nachmachen. 
Das macht MK nur einen schlechteren Ruf uundist meiner Meinung nach unnötig, da uns doch wohl eigene Ideen einfallen c:
Yoa.. Wollte ich nur mal gesagt haben ;)

PS: Github ist voll kuhhl :3

**Comment by CraftingExpertDE** [comment]
Mach mal nen Post mir neuen Kits, da dir ja so viele einfallen und keine die irgendwas mit effekte zu tun haben^^ weil das könnten wir selber etc.

**Comment by HDuck** [comment]
Hatte ich auch schon gemeit,
das kommt halt schon komisch rüber wenn wir
HEdgedog, Prisoner, Racer usw. haben, sogar mit dem selben Namen und der selben Möglichkeit

.. aber ist halt schon zuspät.. wurde schon gecodet

**Comment by lukas81298** [comment]
Racer ist eine Anlehnung an Fahrrad.

**Comment by EinfachNiggo** [comment]
@Lukas ich weiß, dann nennt es doch bitte "Bike", wäre cooler/besser ;)

**Comment by HDuck** [comment]
:+1:

**Comment by LabyStudio** [comment]
Nochmal für euch:
Wir haben auch Feast, Kits, NoSoup.. usw von MCPVP geklaut
Genau so wie Dojo! Dojo hat auch alles von MCPVP..
Dann müssten wir doch jetzt Feast und Kits auch entfernen?

**Comment by LabyStudio** [comment]
Und ich glaube auch nicht das wir den Namen "EarlyHG" erfunden haben..

**Comment by HDuck** [comment]
Soup KitPvP war/ist ursprünglich dafür da um für MCPVP zu Trainieren.
Daher auch die warps "Feast" oder eben "Early[HardcoreGames]"
Aber wenn man von Dojo klaut, klaut man von einem anderen "Trainings Server" was eher nicht so gut ist, da sie sich ja auch erstmal die Ideen anschaffen mussten..

Wird eine Hoffnungslose Diskusion.. am besten einfach nicht so viele sachen von Dojo übernehmen und bisl drauf achten und dann passt's schon

**Comment by EinfachNiggo** [comment]
Jap! *letzter part von ente*: seh ich auch so c: ganz einfach :D

**Comment by lukas81298** [comment]
Ich glaube wir haben geklärt, dass wir (nun) versuchen nix nachzumachen.

**Comment by lukas81298** [comment]
Ich glaube wir haben geklärt, dass wir (nun) versuchen nix nachzumachen.
