### ISSUE TITLE
MLG-Stelle am Spawn c:

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#84]
Wie wäre es mit einer MLG-Stelle am Spawn?
Da wir ja alles am Spawn haben (> eHG,Feast,Lava etc) könnte man doch auch das MLG Warp hier her versetzen. 
Das jetzige MLG Warp ist bisschen langweilig und viele Wissen nicht mal davon.. ^^
Ich find das eh ziemlich chillig alles am Spawn zu haben! :3 Das ganze könnte man ja auch etwas automatisieren - Vorstellung:
Zum Beispiel rechts unten am Spawn könnte man das machen, dass es da ein Loch gibt (was auch an den Bau-Stil vom Spawn angepasst ist), das ca. 50 Blöcke tief ist (> HG Höhe beim MLG'n). Unten kann man dann ja so einen kleinen Sumpf oder so machen (muss ja nicht größer als 10x10 sein), dass es halt auch bisschen uneben ist. 
Wenn man dann zu diesem Loch am Spawn läuft, bekommt man ca. 5 Blöcke davor einen Wassereimer ins Inv und die anderen Dinge wie Kit-Selector gehen weg. Dann kann man da runter springen und wenn man unten angelangt ist, wird man nach ~3 Sek. wieder hochgeportet von wo man abgesprungen ist. 
Man kann das ja auch so machen, wie beim MLG Kit, dass sich das Wasser erst gar nicht ausbreitet und automatisch despawnt, dass man unten gar nicht erst fluten kann. 
Wenn man dann wieder oben ist, kann man entweder nochmal machen, oder läuft zurück und bekommt wieder die Spawn-Items ins Inv.
Da kann man dann ja auch noch ein Scoreboard oder sowas machen;  mit "MLG failed: x" und "MLG geschafft: x".

Ja.. das war's. Hoffe das ist umsetz-/codbar c:
Sorry, dass ich so viel geschrieben hab :PP

~ Niggo c;

**Comment by HDuck** [comment]
Das wäre schon geil!

Find ich super :3

**Comment by LabyStudio** [comment]
Reicht das Kit MLG nicht?

**Comment by HDuck** [comment]
Ich fänd das eigentlich schon cool, und dann wär der Spawn nicht soo "leer", da das Jump'n Run wegen den Enderpearls sowieso erlöst ist :D

**Comment by EinfachNiggo** [comment]
Da stimm ich der Ente zu! :D
Genauso unnötig (fast) wäre dann die Lavachallenge xD.. und man kann das ja ganz chillig bei Langeweile machen c:

**Comment by HDuck** [comment]
Und so ein Kleiner Lavapool, wo man auch Soupen kann wäre ja auch nicht schlecht, und dazu noch ein Schild dran kleben, mit dem Command "/warp Lava" wenn man nicht in dem Pool soupen will, sondern auch Schwimmen..

ach meine erklärung haut nicht so hin.. schreib grad nen 3Seitigen Ausatz
