### ISSUE TITLE
Kit: Beginner - Kit: Tornado

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#85]
Startitem: Schwarzpulver

Fähigkeit: Bei Rechtsklick auf das Item werden da wo du gerade stehst Blöcke hochgewirbelt und nach 5Sekunden wieder runterge"schossen", oder wenn man das Item nochmal klickt, kann man es auch früher runterwerfen. Wenn ein Block einen Gegner trifft, bekommt der 5Herzen Schaden und 2Sekunden Nausseau 1.

Cooldown: 50 / 60 Sekunden

Kosten: kp.. bisschen teuer

Upgrade:
Level 1: Cooldown reduced to "10 Sekunden weniger"
Level 2: Nausseau effect for 4seconds
Level 3: More blocks will be "reingezogen" in your tornado

Das wars.. bb! ~ Niggo c;

**Comment by HDuck** [comment]
>"Level 3: More blocks will be "reingezogen" in your tornado"

hahaha xD

Kit Beginner ist eigentlich von PvPDojo Ability: "Noob" ^^

Aber Tornado klingt geil ;3

**Comment by EinfachNiggo** [comment]
Ouhh stimmt.. Noob :D Naja.. wenn das nicht genommen wird, ist's auch egal :P
Tornado wäre cool c:

**Comment by KnuddelPvPer** [comment]
Tornade ist mega geil aber bei dem Beginner kit muss ich der Behinderten Ente zustimmen <3

**Comment by lukas81298** [comment]
Laby hat das gemacht. Ist wohl noch nicht fertig.
