### ISSUE TITLE
Die "NoSoup-Testphase" in Maintenance?

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#86]
Hey Lukas,

wie du ja weist, ist seit gestern der NoSoup Warp undso drinne,

Ich wäre dafür, dass wir das vorerst Schließen,
in Maintenance gehen und alle Bugs nochmal rausfinden und Beheben!
Gestern war das einfach Viel zu Kaotisch.

Viele Kits wurden nur für NoSoup geschlossen.. (bsp. Prisoner)

Dafür bräuchten wir ein Extra Plugin, dass man bestimmte Kits bei NoSoup nicht benutzen kann

Generell, würde ich noch etwas Warten, Bugs finden, damit das einfach Optimal ist. 
Gestern war es einfach so, dass man sich dachte, dass es nichtmal wirklich getestet wurde..

z.B Könnte man in die Chests mehr Goldene Äpfel reinlegen etc.

Kurz:
--> Einfach mal In Maintenance gehen, alle sachen Testen/Beheben
und nochdazu vlt. das Kit-Mix Plugin einfügen, damit sich die Maintenance für die Spieler auch gelohnt hat

:)

**Comment by lukas81298** [comment]
Gestern war es einfach so, dass man sich dachte, dass es nichtmal wirklich getestet wurde..

Wurde es nicht. Laby hat es einfach so released.

**Comment by HDuck** [comment]
Schonwieder?

Nunja wir könnten es ja jetzt schonmal raus tun,
es ganz entspannt angehen .. :)

**Comment by EinfachNiggo** [comment]
Gute Idee! :)

**Comment by lukas81298** [comment]
Jetzt sollten die meisten bugs gefixed sein. Einige Kits wurden bei nosoup disabled.

**Comment by HDuck** [comment]
@lukas81298  Manche Kits sind aber immernoch disabled (bsp. Airstrike) 
Wurde es noch nicht reloadet oder vergessen
