### ISSUE TITLE
Gladiator Bug:

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#87]
Wenn man einen Gladiatort,

Fängt der Cooldown an, nicht wenn der Fight vorbei ist.

Daher entsteht dieser Bug:

Wenn man bis zum Ende im GladiatorKasten fighted (dass sich der Kasten auflöst)
kann der Gladiator dich sofort wieder Gladiatoren.

Easy 2 Fix:

Der Cooldown wird erst gezählt, wenn der Gladiator Fight vorbei ist.

**Comment by lukas81298** [comment]
Als bug würde ich das nicht bezeichnen aber das lässt sich machen.

**Comment by HDuck** [comment]
Ja mir ist nicht der Überbegriff eingefallen, aber freut mich :D
