### ISSUE TITLE
Kit Schneemann BUFF

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#88]
Wäre toll wenn man Kit Schneemann etwas stärker machen könnte,

Beispiel:

Man kann statt 10 Schneebälle 25 Werfen
oder

Man hat eine Chance von 10% dass ein Schneeball ein Effekt wie "Schwäche" gibt

denn Das kit ist echt bisl Low

**Comment by lukas81298** [comment]
@LabyStudio
