### ISSUE TITLE
Kit Terrorist Bug 

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#89]
Es gibt einen Kleinen Bug, zwar bringt es keinen was, trotzdem:

Wenn man Terrorist ist,
und seine Rüsstung auszieht außer Brustpanzer,
dann 2 Bomben untersich setzt und sie Sprengt
(WICHTIG: Dabei Suppe Rechtsklick gedrückt halten)
Stirbt man, aber gleichzeitig wird man zur stelle Geportet wo man Stierbt.

**Comment by EinfachNiggo** [comment]
Wie kommt man auf sowas? :D

**Comment by HDuck** [comment]
JanBunke kam drauf xD

**Comment by lukas81298** [comment]
Der hat zu viel geraucht.

**Comment by LabyStudio** [comment]
Kann es sein das er einfach auf QuickPlay oder so gekommen ist? xD

**Comment by HDuck** [comment]
Nein ich habs auch probiert..Komisch wie man sowas rausfinden kann aber es geht halt einfach :o
