### ISSUE TITLE
Ban-Nachricht

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#91]
hey Lukas,
wie ich dir schon gesagt hab,
haben viele ein Problem Englische u. Deutsche BanZeit zu Unterscheiden,
daher würde ich es vorschlagen eine etwas andere zu machen:

Reason: <Grund>
Banned by: <Banner>
Banned Until [English]: <Uhrzeit +Datum Englisch>
Banned Until [German]: <Uhrzeit+Datum Deutsch>

Wäre hilfreich für die, die das nicht so verstehn.. ich glaube die Ban Message-Zeit ist derzeit sogar falsch

**Comment by lukas81298** [comment]
Ich werde es einfach auf relative Zeiten umsrellen.
