### ISSUE TITLE
Ideen & Vorschläge für Minekits :)

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#92]
Hier ein paar Ideen & Vorschläge für Minekits
+ 3 Kit-Ideen! :)

1. Jeder Rang bekommt einmal pro Monat bestimmt viele Coins. Das heißt Iron bekommt zB am 1.4. 500Coins, und das jeden Monat.
Emerald 1000, Gold 2000, Gold+ 2500, Diamond 3000

2. Wie wäre es mit dem Command /spec für Premiums? Das heißt wenn ich zB eingebe /spec "IGN", dann werde ich zu diesem Spieler geportet und sitze auf seinen Schultern (wie Hulk). Dabei bin ich unsichtbar und kann dem Spieler beim fighten zu sehen, und seine Herzen sehen! 
Zusatz: Ich weiß nicht ob das geht, dass wenn er ins Inv geht der Spectator automatisch auch in sein Inv geht. 
Wenn nicht, kann man's ja machen, dass man per Rechtsklick in sein Inv sehen kann. Durch sneaken wird man wieder an den Spawn tp't, bzw da wo man zuletz stand (/spec nur am Spawn ausführbar).
Fände ich ein ganz cooles Feature!! :3

3. Wir könnten ja ein paar versteckte "Eastereggs" auf die gesamte Map einbauen. Das ist dann einfach immer ein Schild, wenn man das rechtsklickt, bekommt man je nach dem Schwierigkeitsgrads bestimmt viele Coins. Die sind dann halt über die ganze Map (> Spawn, ehg, lava etc.) ziemlich gut versteckt verteilt. 
Außerdem kann man dafür dann auch Achievemnts machen!

4. Könntet ihr vielleicht "/warp ehg" adden, da "earlyhg" so lange ist.. xD Außerdem fehlt noch ein Quickplay zu Nosoup (Nach der Maintenance halt).

5. /staff Command
Da öffnet sich dann ein GUI mit dem ganzen MK-Team.
Erste Reihe Owner - Da ist dann zB der Kopf von Lukas, sein IGN (hier in Dunkelrot) und noch "Owner"
2. Zeile Admins + Coder etc.

Vielleicht dann zum noch ein Kopf mit Diamond und sein Preis, mit Gold etc.

6. Was ich sehr nützlich fänden würde, wäre ein /help command oder so (Kann auch anders heißen). Da werden alle Commands, die für normale User ausführbar sind dann im Chat aufgelistet (zB /ms /clicktest /country etc.). Ist glaube sehr praktisch, da das ja echt sehr viele, auch nützliche Commands sind! :)

7. Ein Guide -  mit /guide kann man es ausführen. Da wird einem dann (sowas wie auf Mineplex) die Grundlagen des Servers gezeigt. ZB wird man vor ehg geportet und dann steht im Chat "Here you can fight blablabla", sodass Neulinge eine gewisse Ahnung von den Grundlagen haben. 

8. Jede Stunde einmal (jede volle Stunde), oder auch nicht soo oft eine "Partytime" (mir ist kein Name eingefallen xD). Da kommen dann am Spawn ganz viele Feuerwerke und so "Böller" aus Coins, die man einsammeln kann und sowas.. wäre vielleicht auch ganz praktisch um "User anlocken", da du da dann vll 500 Coins holen kannst.
Vielleicht fliegen dann ja auch Boots "vom Himmel" oder so. Kp.. ist mir so spontan eingefallen, aber ich denke das zieht zu viel Performance :P

~ Niggo c;

**Comment by EinfachNiggo** [comment]
6. Gehört zu 5. dazu! Wurde automatisch so geordnet :P 
Dann geht's normal weiter c:

**Comment by EinfachNiggo** [comment]
Boah sortiert das scheisse.. xD "3Kit Ideen" kommen raus und die .6." sollte mit einer 2". Zeile" ersetzt werden :p

**Comment by HDuck** [comment]
Voll Übersichtlich! :3

1. Finde ich nice!
2. 
"sitze auf seinen Schultern (wie Hulk)."

Das wäre nicht so gut, da man sich dann nicht warpen kann,
aber in der 1.8 GIbts ja ein Spectate mode, das wäre in dem Blick bestimmt nice :D
3. Finde ich cool mit Eastereggs, @Admins: NICHT mit SVS, sonnst kann man das ja öfter bedienen ^-^
4. Es gibt schon ein Warp ehg Quickplay muss Lukas/Laby einstellen
5. Super Idee! 

---

Die anderen 3 Finde ich super :D 

Naja beim 3. könnte man sich mit Fly permissions vlt. ein Vorteil holen

**Comment by EinfachNiggo** [comment]
Ups..

@HDuck man kann ja machen, dass man die Coins/Boots etc. mit /fly nicht einsammeln kann ;)

**Comment by HDuck** [comment]
Den /spectate command gibts schon aber nur für YT wegen Bug Prüfung

**Comment by lejaden** [comment]
"Partytime" wenn schon sowie mcpvp und nicht jede stunde. Eher 1-2 mal am Tag

**Comment by lukas81298** [comment]
Eastereggs sind bereits geplant. Für Ostern.

**Comment by EinfachNiggo** [comment]
Macht Sinn :D Und der Rest? :o

**Comment by lukas81298** [comment]
Quickplay für NoSoup gibts auch
