### ISSUE TITLE
3 Kit-Ideen! :3

### ISSUE THREAD

**Issue by EinfachNiggo** [MineKits/MineKits#93]
Kit CONTROLLER:
Startitem: "egal"
Fähigkeiten: Wenn du mit dem Item auf einen Spieler klickst, setzt du dich für 10Sekunden oder so auf ihn drauf und kannst ihn kontrollieren, außerdem bekommt er ein Herz dmg pro Sekunde. Wenn die 10Sekunden rum sind wirst du so 5 Blöcke hochgeworfen und fertig. 
Cooldown: 45 Sekunden
Upgrade:
Level 1: Cooldown reduced to 35 seconds
Level 2: The enemy gets 2 hearts per second
Level 3: You can control your enemy for 15 seconds

Kit FART
Startitem: Nix :P
Fähigkeiten: Wenn man 8 Sekunden sneakt wird man nach vorne geboostet (so 10 Blöcke oder so) und alle Leute die man dabei erwischt, bekommen 4Herzen Schaden, außerdem kommt nach dem Sneaken eine kurze Explosion oder so hinter einem (> Furz)
Cooldown: 40 Sekunden
Upgrade:
Level 1: Sneak 5 seconds to do the fart attack xD
Level 2: Cooldown reduced to 30 seconds
Level 3: It does 5 hearts of damage now

Kit CHEWING GUM
So.. beste Idee. Festhalten! 
Startitem: Pinkes Wollteppichbodenteil, genannt "Chewing Gum".
Fähigkeit: Wenn du deinen Kaugummi rechtsklickst, dann ist du sozusagen deinen Kaugummi für 5Sekunden, währenddessen bekommst du für die 5 Sek Regeneration 1, dann spuckst du den Kaugummi aus, da hin wo du gerade hinschaust - Da bleibt dann dieses "Teppichbodenwollblockdings" für 10 Sekunden. Dann hat man als Item kein pinken mehr, sondern einen grauen (> Papier). Jeder der da dann reinläuft kann sich, solange der Kaugummi da ist (>10 Sek.) nicht mehr bewegen, außer halt auf diesem Block und bekommt Blindness und Wither Effekt. 
Cooldown: 45 Sekunden
Upgrade:
Level 1: Cooldown reduced to 35 seconds
Level 2: You're eating the chewing gum for 10 seconds now
Level 3: The traped enemy gets wither 2 effect

Das waren dann meine Ideen, die mir beim Tennistraining eingefallen sind :P
Werden wahrscheinlich nicht alle umsetzbar sein, aber egal :)
~ Niggo c;

**Comment by lukas81298** [comment]
Controller wäre bei NoSoup viel zu op. Außerdem müsste man glaub ich eine Karottenangel dem client faken.

Fart find ich persönlich nicht so toll.

CHEWING GUM IST GOIL

**Comment by EinfachNiggo** [comment]
Wenigstens eins! :d

**Comment by lukas81298** [comment]
Ist Level 2 nicht eher schlecht?

**Comment by EinfachNiggo** [comment]
Das hab ich mich auch gefragt.. xD Musst ja nicht machen ;D ;)

**Comment by EinfachNiggo** [comment]
Was ist eigentlich jetzt mit dem Kit? ^^ :D
