### ISSUE TITLE
Idee für ehg/feast/nosoup

### ISSUE THREAD

**Issue by lejaden** [MineKits/MineKits#94]
Da es mir sehr oft passiert und auch andere Spieler sehe, die nich kein Kit haben und somit sofort sterben, hätt' ich da eine Idee. Wie wäre es, dass man ein random kit bekommt, wenn man in der ehg/feast/nosoup map ist. Somit kann man keine kills "farmen" und raget nicht 'rum, wenn man vergessen hat, sein kit zu wählen.

**Comment by EinfachNiggo** [comment]
Du kannst das beim Quickplay auswählen, 
"Last Kit", "Random Kit" und "Ask for Kit" ;)

**Comment by lejaden** [comment]
Jaa ich wollt nur schauen, ob auch die minekits mods ahnung von minekits haben c: Tolle Arbeit.

**Comment by EinfachNiggo** [comment]
xDDD
