### ISSUE TITLE
Kit: Delfine

### ISSUE THREAD

**Issue by lejaden** [MineKits/MineKits#95]
Wer kennt es nicht? Einer der beliebtesten Kits in den Endergames. 
Kititem: /
Cooldown: Wenn man geschlagen wird: 15sek
Fähigkeit: 2mal leertaste: doublejump im wasser
Upgrades: Level 1: 10sek
                      Level 2: Weiter springen.

Ich entschuldige mich für den nicht so tollen aufbau.

**Comment by HDuck** [comment]
Ability Dolphin von Dojo .. :o 

und bei MineKits gibts sowieso kaum Wasser vlt 2 kleine See'n  
wäre etwas unnötig

**Comment by lejaden** [comment]
Jaaa is ja guuuut

**Comment by EinfachNiggo** [comment]
@lejaden hat nur voll unnötig Posts, die gar nix nützen xDD
