### ISSUE TITLE
Kit: Cloudwalker 

### ISSUE THREAD

**Issue by CraftingExpertDE** [MineKits/MineKits#96]
-Ability: wenn er das Item benutzt Spawnt unter ihm eine kleine Wolke aus Wolle mit der er wenn er springt und rennt immer einen nach oben springt (vorwärts) und wenn er mit springt nur nach oben und wenn er nur rennt geht die Wolke unter ihm einfach weiter (kleines Escapekit)
-die Wolke hält 15 sec 
-30sec cooldown﻿

**Comment by lukas81298** [comment]
Versteh ich nicht wirklich. Das was ich verstehe klingt nach frozen.

**Comment by HDuck** [comment]
Rein theoretisch das Kit "Frozen" von MCPVP,
aber für ein KitPvP Server etwas unangemessen denk ich
