### ISSUE TITLE
Kit: Pikachu

### ISSUE THREAD

**Issue by CraftingExpertDE** [MineKits/MineKits#97]
-Items: Goldingot
-Ability: Wenn man mit dem Goldingot klick schlagen für 5 Sekunden (jede halbe Sekunde) Blitze auf               
dich ein. Alle Leute im Umkreis brennen und bekommen pro blitz 2 Herzen schaden.
-Cooldown 30 Sec

**Comment by HDuck** [comment]
Es gibt schon das Kit "Spellmaster" wo die Ability eingebaut ist ^^

**Comment by EinfachNiggo** [comment]
Spellmaster checkt eh keiner uns ist langweilig.. :D
Ich find's cool! :)

**Comment by HDuck** [comment]
Spellmaster wurde neu gecodet, man hat nurnnoch ein Item was man Rechtsklickt dann kommt's random :D

**Comment by lukas81298** [comment]
Ich finde, dass wir richtig coole kits brauchen. Das hier ist meiner Meinung nach echt was langweilig 😕

**Comment by EinfachNiggo** [comment]
Ja, @lukas81298 Chewing Gum ist viel besser!! :D
