### ISSUE TITLE
Password Reset bei der Website!

### ISSUE THREAD

**Issue by HDuck** [MineKits/MineKits#99]
Hey Lukas,
Sehr viele vergessen anscheinend ihr MineKits passwort.. 
könntest du ein "Reset Password" irgentwie einbauen?

(Bezogen auf die Website http://MineKits.eu)

**Comment by lukas81298** [comment]
Das ganze hab ich schon einmal vorbereitet. Ich glaube wir werden es aber mit einem Ingame Befehl realisieren.

**Comment by LabyStudio** [comment]
Ich glaube das hat sich geklärt.
